-- #2020: one unclaimed funnel run per domain, enforced by the database.
--
-- The public intake is UNAUTHENTICATED and creates merchant_audit_runs rows.
-- Its per-domain reuse was SELECT-then-INSERT with nothing atomic behind it,
-- so N concurrent requests for one domain created N rows — measured at 25/25
-- on PG 15. record_anonymous_funnel_run catches the violation this index
-- raises and re-reads the winner's row, so a race resolves to one run.
--
-- NOT "CONCURRENTLY", deliberately. This repo applies migrations in prod
-- through routes/admin_run_migration_pending.py (its own docstring: "CI is
-- billing-blocked, so there is no automatic migrate-on-deploy"), and that
-- runner executes the file inside `engine.begin()` — a transaction, where
-- Postgres refuses CREATE INDEX CONCURRENTLY outright. A first cut used
-- CONCURRENTLY and was therefore unappliable by the only mechanism that
-- actually applies it. Appliable beats theoretically-cheaper.
--
-- LOCK NOTE FOR THE OPERATOR. A plain CREATE INDEX takes a lock that blocks
-- writes to merchant_audit_runs for the build. The predicate matches only
-- unclaimed public_funnel rows, of which production has none today (the
-- producer could not fire before #2021), so the build is effectively
-- instant. If that has aged and the table has grown, build it by hand first
-- and let this migration no-op on IF NOT EXISTS:
--
--   CREATE UNIQUE INDEX CONCURRENTLY idx_funnel_run_one_per_domain
--     ON merchant_audit_runs ((partial_result_jsonb->'funnel'->>'domain'))
--     WHERE merchant_id IS NULL AND subject_type = 'public_funnel';
--
--   -- CONCURRENTLY leaves an INVALID index behind if it fails; check with
--   SELECT indexrelid::regclass FROM pg_index
--    WHERE NOT indisvalid
--      AND indexrelid::regclass::text = 'idx_funnel_run_one_per_domain';
--
-- Duplicates would fail the unique build. Verify before applying:
--   SELECT partial_result_jsonb->'funnel'->>'domain' AS d, count(*)
--     FROM merchant_audit_runs
--    WHERE merchant_id IS NULL AND subject_type = 'public_funnel'
--    GROUP BY 1 HAVING count(*) > 1;
--
-- The predicate is narrow on purpose: only UNCLAIMED rows in THIS lane. Once
-- a run is claimed it belongs to a merchant, and a second visitor to the same
-- domain must be able to start a fresh one.

CREATE UNIQUE INDEX IF NOT EXISTS idx_funnel_run_one_per_domain
  ON merchant_audit_runs ((partial_result_jsonb->'funnel'->>'domain'))
  WHERE merchant_id IS NULL AND subject_type = 'public_funnel';
