[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r pivota_infra/requirements.txt"]

[start]
cmd = "cd pivota_infra && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

