[pytest]
addopts = -ra
asyncio_mode = auto
testpaths =
    tests
python_files =
    test_*.py
python_classes =
    Test*
python_functions =
    test_*
norecursedirs =
    pivota_infra/tests
    .git
    .venv
