-- Public read-schema columns only, copied from original metadata; no data/defaults/triggers.

-- Core catalog primary keys follow db/catalog.py. This is not a full schema restore.

CREATE TABLE "catalog_merchants" (
  "merchant_id" character varying(64) NOT NULL,
  "merchant_name" character varying(255),
  "primary_platform" character varying(64),
  "status" character varying(32) NOT NULL,
  "source_system" character varying(64),
  "source_ref" character varying(255),
  "metadata_json" jsonb,
  "created_at" timestamp without time zone NOT NULL,
  "updated_at" timestamp without time zone NOT NULL,
  "last_full_sync_at" timestamp with time zone,
  "audit_schedule" text NOT NULL,
  "indexable" boolean NOT NULL,
  PRIMARY KEY ("merchant_id")
);

CREATE TABLE "catalog_products" (
  "product_key" character varying(255) NOT NULL,
  "merchant_id" character varying(64) NOT NULL,
  "platform" character varying(64) NOT NULL,
  "source_product_id" character varying(128) NOT NULL,
  "catalog_track" character varying(32) NOT NULL,
  "truth_tier" character varying(32) NOT NULL,
  "readiness_tier" character varying(32) NOT NULL,
  "source_system" character varying(64),
  "source_ref" character varying(255),
  "title" text NOT NULL,
  "description" text,
  "brand" character varying(255),
  "product_type" character varying(255),
  "category" character varying(255),
  "canonical_url" text,
  "image_url" text,
  "product_payload" jsonb,
  "freshness_json" jsonb,
  "created_at" timestamp without time zone NOT NULL,
  "updated_at" timestamp without time zone NOT NULL,
  "category_path" character varying(255),
  "category_confidence" real,
  "category_label_source" character varying(32),
  "pdp_scope" character varying(32) NOT NULL,
  "pdp_scope_source" character varying(32),
  "pdp_scope_set_at" timestamp with time zone,
  "pivota_signature_id" text,
  "pivota_canonical_url" text,
  "pivota_signature_minted_at" timestamp with time zone,
  "tags" jsonb,
  "price_tier" character varying(16),
  "use_case_tags" jsonb,
  "lifestyle_tags" jsonb,
  "demographic" character varying(16),
  "pdp_lifecycle_stage" character varying(16),
  "content_key" character varying(40),
  "last_seen_in_sync_at" timestamp with time zone,
  "sync_status" character varying(16) NOT NULL,
  "material" text,
  "material_source" character varying(32),
  "material_confidence" real,
  "care" text,
  "care_source" character varying(32),
  "care_confidence" real,
  "size_guide" jsonb,
  "size_guide_source" character varying(32),
  "size_guide_confidence" real,
  "category_label" character varying(255),
  "source_domain" text,
  "suppression_reason" text,
  "suppressed_at" timestamp with time zone,
  "suppression_metadata" jsonb,
  "content_changed_at" timestamp without time zone NOT NULL,
  "category_kind" character varying(16),
  "claim_state" character varying(16) NOT NULL,
  "resolved_vertical" character varying(16),
  "llm_attributes" jsonb,
  "seller_ref" text,
  "seed_kind" text,
  "gtin" text,
  "rating_value" numeric,
  "rating_count" integer,
  "pdp_will_render" boolean,
  "pdp_will_render_computed_at" timestamp with time zone,
  "recall_doc" text,
  "recall_market" text,
  "recall_tool" text,
  "recall_availability" text,
  "recall_doc_updated_at" timestamp with time zone,
  PRIMARY KEY ("product_key")
);

CREATE TABLE "catalog_skus" (
  "sku_key" character varying(255) NOT NULL,
  "product_key" character varying(255) NOT NULL,
  "merchant_id" character varying(64) NOT NULL,
  "platform" character varying(64) NOT NULL,
  "source_product_id" character varying(128) NOT NULL,
  "source_variant_id" character varying(128) NOT NULL,
  "sku" character varying(128),
  "barcode" character varying(128),
  "title" text NOT NULL,
  "currency" character varying(16),
  "image_url" text,
  "visible_attributes" jsonb,
  "visible_option_labels" jsonb,
  "ingredient_ids" jsonb,
  "sku_payload" jsonb,
  "readiness_tier" character varying(32) NOT NULL,
  "created_at" timestamp without time zone NOT NULL,
  "updated_at" timestamp without time zone NOT NULL,
  "source_domain" text,
  "suppression_reason" text,
  "suppressed_at" timestamp with time zone,
  "suppression_metadata" jsonb,
  PRIMARY KEY ("sku_key")
);

CREATE TABLE "catalog_offers" (
  "offer_id" character varying(255) NOT NULL,
  "sku_key" character varying(255) NOT NULL,
  "product_key" character varying(255) NOT NULL,
  "merchant_id" character varying(64) NOT NULL,
  "catalog_track" character varying(32) NOT NULL,
  "truth_tier" character varying(32) NOT NULL,
  "readiness_tier" character varying(32) NOT NULL,
  "offer_mode" character varying(32) NOT NULL,
  "channel" character varying(64) NOT NULL,
  "availability" character varying(32) NOT NULL,
  "inventory_quantity" integer,
  "currency" character varying(16),
  "list_price" numeric(12,2),
  "merchant_effective_price" numeric(12,2),
  "estimated_best_price" numeric(12,2),
  "price_confidence" numeric(5,2),
  "source_system" character varying(64),
  "source_ref" character varying(255),
  "offer_payload" jsonb,
  "created_at" timestamp without time zone NOT NULL,
  "updated_at" timestamp without time zone NOT NULL,
  "suppression_reason" text,
  "suppressed_at" timestamp with time zone,
  "source_domain" text,
  "suppression_metadata" jsonb,
  "offer_type" character varying(16),
  "market" character varying(8) NOT NULL,
  "is_first_party" boolean NOT NULL,
  "why_buy_direct" text,
  "price_checked_at" timestamp with time zone,
  PRIMARY KEY ("offer_id")
);

CREATE TABLE "external_product_seeds" (
  "id" text NOT NULL,
  "market" text NOT NULL,
  "tool" text NOT NULL,
  "destination_url" text NOT NULL,
  "canonical_url" text,
  "domain" text,
  "title" text,
  "image_url" text,
  "price_amount" double precision,
  "price_currency" text,
  "availability" text,
  "status" text NOT NULL,
  "notes" text,
  "created_by_employee_id" text,
  "attached_product_key" text,
  "attached_variant_id" text,
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL,
  "seed_data" jsonb NOT NULL,
  "utm_template" text,
  "partner_type" text,
  "disclosure_text" text,
  "external_product_id" text,
  "content_lock" jsonb NOT NULL,
  "seller_ref" text,
  "seed_kind" text,
  "search_text" text NOT NULL,
  "destination_checked_at" timestamp with time zone,
  "destination_http_status" integer,
  "destination_verdict" text,
  "destination_failure_streak" integer NOT NULL,
  "last_crawled_at" timestamp with time zone,
  "last_crawl_attempt_at" timestamp with time zone
);

CREATE TABLE "index_pipeline_state" (
  "content_key" character varying(40) NOT NULL,
  "pivota_signature_id" character varying(40),
  "merchant_id" character varying(100),
  "pipeline_stage" character varying(20) NOT NULL,
  "blocker_code" character varying(40) NOT NULL,
  "blocker_detail" text,
  "serving_eligible" boolean NOT NULL,
  "content_quality_score" real,
  "model_readiness_score" real,
  "conversion_potential_score" real,
  "quality_rules_version" character varying(32),
  "quality_scored_at" timestamp with time zone,
  "extraction_content_hash" character varying(64),
  "extractor_version" character varying(32),
  "last_extracted_at" timestamp with time zone,
  "seed_audit_status" character varying(30),
  "identity_resolved" boolean NOT NULL,
  "product_group_id" character varying(64),
  "has_image" boolean NOT NULL,
  "has_price" boolean NOT NULL,
  "description_length" integer,
  "consolidation_version" character varying(32),
  "last_consolidated_at" timestamp with time zone NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "readiness_tier" character varying(64),
  "index_eligible" boolean NOT NULL
);

CREATE TABLE "catalog_row_trust" (
  "subject_type" text NOT NULL,
  "subject_key" text NOT NULL,
  "product_key" text,
  "source_listing_ref" text,
  "content_key" text,
  "source_id" text,
  "source_domain" text,
  "source_lifecycle_state" text NOT NULL,
  "source_last_checked_at" timestamp with time zone,
  "identity_status" text NOT NULL,
  "identity_confidence" numeric(4,3),
  "matched_product_key" text,
  "matched_content_key" text,
  "matched_sellable_item_group_id" text,
  "freshness_state" text NOT NULL,
  "last_verified_at" timestamp with time zone,
  "verification_source" text,
  "serving_decision" text NOT NULL,
  "serving_reason_codes" text[] NOT NULL,
  "manual_override_id" text,
  "policy_version" text NOT NULL,
  "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE "pdp_identity_listing" (
  "source_listing_ref" text NOT NULL,
  "merchant_id" text NOT NULL,
  "product_id" text NOT NULL,
  "source_kind" text NOT NULL,
  "source_tier" text NOT NULL,
  "live_read_enabled" boolean NOT NULL,
  "sellable_item_group_id" text NOT NULL,
  "product_line_id" text NOT NULL,
  "review_family_id" text NOT NULL,
  "identity_status" text NOT NULL,
  "identity_confidence" numeric(6,4),
  "matched_by_rule" text,
  "match_basis" jsonb NOT NULL,
  "strong_identity" jsonb NOT NULL,
  "soft_identity" jsonb NOT NULL,
  "variant_axes" jsonb NOT NULL,
  "source_payload" jsonb NOT NULL,
  "review_summary" jsonb NOT NULL,
  "official_url" text,
  "official_domain" text,
  "brand_norm" text,
  "title_norm" text,
  "title_core_norm" text,
  "review_required" boolean NOT NULL,
  "review_reason_codes" jsonb NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE "merchant_stores" (
  "store_id" character varying(50) NOT NULL,
  "merchant_id" character varying(50) NOT NULL,
  "platform" character varying(50) NOT NULL,
  "name" character varying(255) NOT NULL,
  "domain" character varying(255),
  "api_key" text,
  "status" character varying(50),
  "connected_at" timestamp with time zone,
  "last_sync" timestamp with time zone,
  "product_count" integer,
  "created_at" timestamp with time zone,
  "realtime_enabled" boolean,
  "api_endpoint" character varying(500),
  "query_ttl_seconds" integer,
  "support_email" character varying(255),
  "is_primary" boolean NOT NULL,
  "order_writeback_status" text NOT NULL,
  "order_writeback_enabled_at" timestamp with time zone,
  "order_writeback_canary_order_id" text,
  "order_writeback_last_canary_order_id" text,
  "order_writeback_last_verified_at" timestamp with time zone,
  "order_writeback_last_error" text,
  "content_writeback_status" text NOT NULL,
  "content_writeback_enabled_at" timestamp with time zone,
  "content_writeback_canary_product_id" text,
  "content_writeback_last_canary_product_id" text,
  "content_writeback_last_written_at" timestamp with time zone,
  "content_writeback_last_error" text,
  "upstream_probe_at" timestamp with time zone,
  "upstream_probe_status" text,
  "upstream_probe_http_status" integer,
  "upstream_probe_failures" integer NOT NULL
);

-- Canonical election read columns; PK follows migration181. No default clock values.
CREATE TABLE content_canonical_election (
  content_key text NOT NULL,
  canonical_sig_id text NOT NULL,
  election_reason text NOT NULL,
  elected_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  PRIMARY KEY(content_key)
);
