"""`setup_scheduler.sh` must be safe to re-run against live production.

It was not, and the consequence was concrete: the three DB crons migrated in
#1892/#1894/#1895 could not be provisioned with it and were created by hand.

Three separate things made every invocation unusable, and each one is pinned below:

1. It hard-exited before touching anything, because it required `env.<env>.yaml`
   and `secrets.<env>.list` — both generated by `port_railway_env.py` from
   `railway variables --json`. Railway was decommissioned 2026-08-22, so on a
   fresh checkout those files cannot be regenerated and the exit was the outcome
   of EVERY run.
2. `sched()` applied the global `$PAUSED` to EVERY trigger on EVERY run. The
   default (1) paused relgraph-sync-cron, the per-minute
   reviews-invitation-send-cron and the commerce-index lanes; `PAUSED=0` had the
   opposite blast radius and was refused outright whenever Store Audit was armed
   — which in prod it always is.
3. Feature-flag `else` branches turned a merely-unset flag into an active
   `scheduler jobs pause`, so a run that never mentioned Store Audit still
   disarmed its four live triggers.

These tests drive the REAL script through the `GCLOUD` injection point it already
supports, against a fake that records every invocation. They assert on the
commands the script would actually issue — not on its source text, which is the
mistake that would let a rewrite pass while re-breaking the behaviour.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import textwrap
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "infra" / "gcp" / "setup_scheduler.sh"

# Everything that exists in prod today. `describe` succeeding is how the script decides
# create-vs-update and, previously, nothing else.
EXISTING_TRIGGERS = {
    "relgraph-sync-cron", "reviews-invitation-send-cron",
    "commerce-index-relgraph-cron", "commerce-index-search-index-cron",
    "commerce-index-checkout-validation-cron", "commerce-index-insight-refresh-cron",
    "store-audit-ucp-probe-cron", "store-audit-ucp-reprobe-enqueue-cron",
    "store-audit-commerce-probe-cron", "store-audit-commerce-reprobe-enqueue-cron",
    "external-seed-sentinel-nongrowth-cron", "pdp-identity-graph-backfill-cron",
    "content-canonical-election-cron", "agent-pdp-orphan-reaper-cron",
    "derive-offer-market-currency-cron", "audit-domainless-offer-currency-cron",
}

# The Store Audit preflight reads real JSON out of `run services describe web` and
# `run revisions describe`, so the fake has to answer those in shape or the script exits 2
# before reaching a single scheduler call.
WEB_JSON = (
    '{"status":{"url":"https://web-gpx4jyrubq-uw.a.run.app",'
    '"traffic":[{"revisionName":"web-00088-kaz","percent":100}]}}'
)
REVISION_JSON = (
    '{"spec":{"containers":[{"env":['
    '{"name":"STORE_AUDIT_UCP_PROBE_RECEIPT_ENABLED","value":"true"},'
    '{"name":"STORE_AUDIT_UCP_PROBE_INTERNAL_KEY","valueFrom":{"secretKeyRef":'
    '{"name":"STORE_AUDIT_UCP_PROBE_INTERNAL_KEY"}}},'
    '{"name":"STORE_AUDIT_COMMERCE_PROBE_RECEIPT_ENABLED","value":"true"},'
    '{"name":"STORE_AUDIT_COMMERCE_PROBE_INTERNAL_KEY","valueFrom":{"secretKeyRef":'
    '{"name":"STORE_AUDIT_COMMERCE_PROBE_INTERNAL_KEY"}}}'
    ']}]}}'
)

FAKE_GCLOUD = textwrap.dedent(
    """\
    #!/usr/bin/env bash
    # Records argv, then answers the few reads the script makes.
    printf '%s\\n' "$*" >> "$GCLOUD_LOG"
    case "$1 $2 $3" in
      "scheduler jobs describe")
        grep -qx "$4" "$EXISTING_TRIGGERS_FILE" && exit 0 || exit 1 ;;
      "run jobs describe") exit 1 ;;            # jobs: always "create" — irrelevant to these tests
      "iam service-accounts") exit 0 ;;
      "run revisions describe") printf '%s' "$REVISION_JSON"; exit 0 ;;
      "run services describe")
        case "$*" in *--format=json*) printf '%s' "$WEB_JSON" ;; *) echo "https://worker.example" ;; esac
        exit 0 ;;
    esac
    exit 0
    """
)

def _run(tmp_path: Path, env_overrides: dict[str, str | None]) -> list[str]:
    """Run the real script against a fake gcloud; return the recorded invocations.

    A value of None DELETES the key from the child environment. That distinction is
    load-bearing: the script separates "operator said false" from "operator said nothing"
    with `${F+set}`, which is empty only when F is genuinely absent — so a test that sets
    F="" is still testing the explicit branch.
    """
    fake = tmp_path / "fake-gcloud"
    fake.write_text(FAKE_GCLOUD)
    fake.chmod(0o755)
    log = tmp_path / "calls.log"
    log.touch()
    existing = tmp_path / "existing.txt"
    existing.write_text("\n".join(sorted(EXISTING_TRIGGERS)) + "\n")

    env = {
        **os.environ,
        "GCLOUD": str(fake),
        "GCLOUD_LOG": str(log),
        "EXISTING_TRIGGERS_FILE": str(existing),
        "WEB_JSON": WEB_JSON,
        "REVISION_JSON": REVISION_JSON,
        # Prod's real posture: both Store Audit workers armed. This is the combination that
        # made PAUSED=0 refused, so it is the one worth testing against.
        "STORE_AUDIT_UCP_REPROBE_WORKER": "true",
        "STORE_AUDIT_UCP_REPROBE_ARMED": "true",
        "STORE_AUDIT_UCP_PROBE_BACKEND_BASE_URL": "https://web-gpx4jyrubq-uw.a.run.app",
        "STORE_AUDIT_COMMERCE_REPROBE_WORKER": "true",
        "STORE_AUDIT_COMMERCE_REPROBE_ARMED": "true",
        "STORE_AUDIT_COMMERCE_PROBE_BACKEND_BASE_URL": "https://web-gpx4jyrubq-uw.a.run.app",
        **{k: v for k, v in env_overrides.items() if v is not None},
    }
    for k, v in env_overrides.items():
        if v is None:
            env.pop(k, None)
    proc = subprocess.run(
        ["bash", str(SCRIPT), "prod", "a" * 40, "b" * 40],
        capture_output=True, text=True, env=env, cwd=str(REPO),
    )
    assert proc.returncode == 0, (
        f"the script must run to completion against live-prod-shaped state.\n"
        f"rc={proc.returncode}\nstderr:\n{proc.stderr[-3000:]}"
    )
    return log.read_text().splitlines()


def _state_changes(calls: list[str]) -> set[tuple[str, str]]:
    """(verb, trigger) for every pause/resume the script issued."""
    out = set()
    for c in calls:
        parts = c.split()
        if parts[:2] == ["scheduler", "jobs"] and len(parts) > 3 and parts[2] in ("pause", "resume"):
            out.add((parts[2], parts[3]))
    return out


def test_a_plain_rerun_changes_no_existing_trigger_state(tmp_path):
    """THE headline invariant. A reconcile run must not rewrite live state.

    Before the fix this issued a `pause` for every trigger in EXISTING_TRIGGERS —
    including the per-minute reviews-invitation-send-cron, which sends mail.
    """
    changes = _state_changes(_run(tmp_path, {}))
    touched_existing = {t for verb, t in changes if t in EXISTING_TRIGGERS}
    assert not touched_existing, (
        f"a plain re-run paused/resumed existing triggers: {sorted(touched_existing)}. "
        "Re-running must reconcile DEFINITIONS only."
    )


def test_it_does_not_require_the_retired_railway_files(tmp_path):
    """It must not exit 1 looking for files `port_railway_env.py` can no longer produce."""
    assert not (REPO / "infra" / "gcp" / "env.prod.yaml").exists(), (
        "this test is only meaningful while the ported file is absent"
    )
    _run(tmp_path, {})  # _run asserts rc == 0


def test_preserve_does_not_rewrite_worker_env(tmp_path):
    """CONFIG=preserve must roll the image forward without touching env/secrets wholesale."""
    calls = _run(tmp_path, {})
    deploys = [c for c in calls if c.startswith("run deploy worker")]
    assert len(deploys) == 1, f"expected exactly one worker deploy, got {len(deploys)}"
    assert "--env-vars-file" not in deploys[0], "preserve must not rewrite the whole env"
    assert "--set-secrets" not in deploys[0], "preserve must not rewrite secret mounts"
    assert "--update-env-vars" in deploys[0], "preserve must still restamp the commit"
    assert "AUDIT_WORKER_ENABLED" not in deploys[0], (
        "preserve must not decide the worker's armed state — that is WORKERS under CONFIG=apply"
    )


def test_arm_changes_exactly_one_trigger(tmp_path):
    changes = _state_changes(_run(tmp_path, {"ARM": "content-canonical-election-cron"}))
    assert ("resume", "content-canonical-election-cron") in changes
    others = {t for _, t in changes if t != "content-canonical-election-cron"}
    assert not others, f"ARM must be surgical; it also touched {sorted(others)}"


def test_disarm_changes_exactly_one_trigger(tmp_path):
    changes = _state_changes(_run(tmp_path, {"DISARM": "reviews-invitation-send-cron"}))
    assert ("pause", "reviews-invitation-send-cron") in changes
    others = {t for _, t in changes if t != "reviews-invitation-send-cron"}
    assert not others, f"DISARM must be surgical; it also touched {sorted(others)}"


def test_a_newly_created_trigger_is_still_inert_by_default(tmp_path):
    """Preserving EXISTING state must not make NEW triggers arm themselves.

    The cutover-safety property has to survive: a trigger this run creates comes up paused
    unless the operator says otherwise.
    """
    # Pretend nothing exists yet: every trigger is a create.
    #
    # STORE_AUDIT_*_ARMED is forced false here. Those two lanes pass an EXPLICIT per-trigger
    # paused argument (sched()'s 5th positional) rather than inheriting $PAUSED, so with
    # ARMED=true they legitimately come up resumed — which is the point of having a per-lane
    # arm switch, and would otherwise mask the default this test is about.
    empty = tmp_path / "none.txt"
    empty.write_text("")
    changes = _state_changes(_run(tmp_path, {
        "EXISTING_TRIGGERS_FILE": str(empty),
        "STORE_AUDIT_UCP_REPROBE_ARMED": "false",
        "STORE_AUDIT_COMMERCE_REPROBE_ARMED": "false",
    }))
    resumed = {t for verb, t in changes if verb == "resume"}
    paused = {t for verb, t in changes if verb == "pause"}
    assert not resumed, f"newly created triggers must default to paused, but resumed {sorted(resumed)}"
    assert paused, "a create run should still be pausing the triggers it creates"


def test_store_audit_stays_armed_when_the_flag_is_not_mentioned(tmp_path):
    """A run that never mentions Store Audit must not disarm its four live triggers.

    The `else` branches read a flag that DEFAULTS to false, so "said nothing" and
    "said false" were indistinguishable and the disarm fired on a plain run.
    """
    # UNSET, not empty. An earlier version of this test set these to "" and then filtered the
    # empties out, so the base env's STORE_AUDIT_*_WORKER="true" survived and the disarm branch
    # was never reached — it passed against the unguarded code. Mutant-checking caught it.
    changes = _state_changes(_run(tmp_path, {
        "STORE_AUDIT_UCP_REPROBE_WORKER": None,
        "STORE_AUDIT_UCP_REPROBE_ARMED": None,
        "STORE_AUDIT_UCP_PROBE_BACKEND_BASE_URL": None,
        "STORE_AUDIT_COMMERCE_REPROBE_WORKER": None,
        "STORE_AUDIT_COMMERCE_REPROBE_ARMED": None,
        "STORE_AUDIT_COMMERCE_PROBE_BACKEND_BASE_URL": None,
    }))
    store_audit = {t for _, t in changes if t.startswith("store-audit-")}
    assert not store_audit, (
        f"a run that never mentioned Store Audit disarmed {sorted(store_audit)}"
    )


def test_paused_zero_with_arm_is_refused_as_ambiguous(tmp_path):
    """The two mean different things now; passing both should not silently pick one."""
    fake = tmp_path / "fake-gcloud"
    fake.write_text(FAKE_GCLOUD)
    fake.chmod(0o755)
    log = tmp_path / "calls.log"; log.touch()
    existing = tmp_path / "existing.txt"; existing.write_text("\n".join(sorted(EXISTING_TRIGGERS)))
    proc = subprocess.run(
        ["bash", str(SCRIPT), "prod", "a" * 40, "b" * 40],
        capture_output=True, text=True, cwd=str(REPO),
        env={**os.environ, "GCLOUD": str(fake), "GCLOUD_LOG": str(log),
             "EXISTING_TRIGGERS_FILE": str(existing),
             "WEB_JSON": WEB_JSON, "REVISION_JSON": REVISION_JSON,
        "WEB_JSON": WEB_JSON,
        "REVISION_JSON": REVISION_JSON,
             "PAUSED": "0", "ARM": "relgraph-sync-cron"},
    )
    assert proc.returncode == 2, "PAUSED=0 together with ARM should be refused"


# ---- Store Audit preflight: which revision serves the untagged service URL? ----------------
#
# The predicate lives in setup_scheduler.sh as an embedded `python3 -c` heredoc. These tests
# EXTRACT AND EXECUTE that exact block rather than restating it, so they exercise the shipping
# code. A restated copy would keep passing while the script itself regressed — which is exactly
# what happened on the first draft of this file.
_ACTIVE_RE = re.compile(r"python3 -c '\n(import json,sys\no=json\.load\(sys\.stdin\)\n.*?)\n'\)\"", re.S)


def _preflight_blocks():
    src = (REPO / "infra" / "gcp" / "setup_scheduler.sh").read_text(encoding="utf-8")
    blocks = [b for b in _ACTIVE_RE.findall(src) if "revisionName" in b and "percent" in b]
    assert len(blocks) == 2, (
        f"expected 2 active-revision preflight blocks in setup_scheduler.sh, found {len(blocks)}. "
        "If the shape changed, fix this extractor - do NOT restate the predicate here, or these "
        "tests stop testing the script."
    )
    return blocks


def _active_revision(traffic):
    """Run the script's OWN predicate over a traffic list; assert both copies agree."""
    payload = json.dumps({"status": {"traffic": traffic}})
    results = set()
    for block in _preflight_blocks():
        proc = subprocess.run(["python3", "-c", block], input=payload,
                              capture_output=True, text=True)
        assert proc.returncode == 0, f"preflight block failed: {proc.stderr}"
        results.add(proc.stdout.strip())
    assert len(results) == 1, f"the UCP and commerce preflights disagree: {results}"
    return results.pop()


def test_a_tagged_serving_revision_is_still_the_serving_revision():
    """The state a normal deploy leaves behind must not be refused.

    deploy_backend.sh ships every candidate with `--tag c-<sha>` and then promotes it, so the
    revision at 100% keeps its own candidate tag until a later deploy retires it. The guard
    used to require `not t.get("tag")` and so refused exactly that — observed in prod
    2026-08-26, where web-00098-kax held 100% traffic AND tag c-6f8b201ba7dc, which made
    setup_scheduler.sh unrunnable whenever Store Audit was armed.
    """
    prod_shape = [
        {"revisionName": "web-00098-kax", "percent": 100, "tag": "c-6f8b201ba7dc"},
        {"revisionName": "web-00100-nox", "tag": "c-820e3cb51eec"},  # candidate, no percent
    ]
    assert _active_revision(prod_shape) == "web-00098-kax"


def test_an_untagged_serving_revision_still_resolves():
    assert _active_revision([{"revisionName": "web-1", "percent": 100}]) == "web-1"


def test_a_traffic_split_is_still_refused():
    """The property the guard exists for. Neither half is THE serving revision."""
    assert _active_revision([
        {"revisionName": "web-1", "percent": 50},
        {"revisionName": "web-2", "percent": 50},
    ]) == ""


def test_a_zero_traffic_candidate_alone_is_refused():
    """A candidate that was verified but never promoted must not be mistaken for serving."""
    assert _active_revision([{"revisionName": "web-2", "percent": 0, "tag": "c-abc"}]) == ""
    assert _active_revision([{"revisionName": "web-2", "tag": "c-abc"}]) == ""


def test_two_revisions_at_100_is_refused():
    """Nonsensical, but the `len(active) == 1` guard is what makes it unambiguous."""
    assert _active_revision([
        {"revisionName": "web-1", "percent": 100},
        {"revisionName": "web-2", "percent": 100},
    ]) == ""


def test_both_preflights_use_the_same_predicate():
    """The UCP and commerce guards are two copies of one rule; they must not drift apart."""
    blocks = _preflight_blocks()
    assert blocks[0] == blocks[1], "the two preflight blocks have diverged"


def _secrets_for(calls: list[str], job: str) -> str:
    for c in calls:
        if c.startswith(f"run jobs create {job} ") or c.startswith(f"run jobs update {job} "):
            parts = c.split()
            return parts[parts.index("--set-secrets") + 1]
    raise AssertionError(f"no create/update recorded for {job}")


def test_search_index_key_is_not_mounted_unless_the_lane_is_armed(tmp_path):
    """A secret that may not exist must not be mounted unconditionally.

    Cloud Run resolves secret refs at create/update time, so mounting a name that does not
    exist does NOT merely leave the lane inert — `gcloud run jobs update` fails, and under
    `set -e` that aborts the whole reconcile. Confirmed in prod 2026-08-26:
    CATALOG_SERVING_INDEX_API_KEY does not exist, the live job mounted it anyway, and the
    run died there before reaching the scheduler section.
    """
    secrets = _secrets_for(_run(tmp_path, {}), "commerce-index-search-index")
    assert "CATALOG_SERVING_INDEX_API_KEY" not in secrets, (
        "the API key must not be mounted while SEARCH_INDEX_PUBLICATION_WORKER is false"
    )
    # The DSNs it genuinely needs are still there — this is a narrowing, not a removal.
    assert "DATABASE_URL=DATABASE_URL_NOVERIFY:latest" in secrets
    assert "PCI_KB_DATABASE_URL=PCI_KB_DATABASE_URL_NOVERIFY:latest" in secrets


def test_search_index_key_IS_mounted_once_the_lane_is_armed(tmp_path):
    """Arming the lane is the point at which the secret is expected to exist."""
    secrets = _secrets_for(
        _run(tmp_path, {"SEARCH_INDEX_PUBLICATION_WORKER": "true"}),
        "commerce-index-search-index",
    )
    assert "CATALOG_SERVING_INDEX_API_KEY=CATALOG_SERVING_INDEX_API_KEY:latest" in secrets


def test_no_args_value_beginning_with_a_dash_uses_the_space_form():
    """`--args "-m,..."` is rejected by gcloud, and the plan-shim cannot catch it.

    gcloud's parser reads a value beginning with `-` as the next FLAG and fails with
    "argument --args: expected one argument". The `--args=` form binds it.

    Confirmed against prod 2026-08-26: the reconcile aborted at
    derive-offer-market-currency AFTER already updating ten jobs, so this is not a
    cosmetic preference — it makes those job definitions permanently un-updatable by the
    script, and it fails halfway through rather than up front.

    This is a SOURCE-TEXT assertion on purpose. The behavioural harness records what the
    script *would* invoke; it cannot reproduce gcloud's own argument parsing, so it is
    structurally blind to this class. A source check is the only thing that catches it
    before someone runs the script against production.
    """
    src = (REPO / "infra" / "gcp" / "setup_scheduler.sh").read_text(encoding="utf-8")
    # Join backslash continuations FIRST. Review found the evasion: splitting
    # `--args` from its value across two continued lines left the inspected line
    # ending in `\`, so the extracted "value" was a backslash and the guard
    # passed while gcloud still got the broken space form.
    joined, buf = [], ""
    for raw in src.splitlines():
        buf += raw[:-1] + " " if raw.rstrip().endswith("\\") else raw
        if not raw.rstrip().endswith("\\"):
            joined.append(buf); buf = ""
    if buf:
        joined.append(buf)
    offenders = []
    for i, line in enumerate(joined, 1):
        stripped = line.strip()
        if not stripped.startswith("--args ") and " --args " not in stripped:
            continue
        # the value gcloud would receive, after `--args `
        value = stripped.split("--args ", 1)[1].lstrip()
        if value[:1] in ("'", '"'):
            value = value[1:]
        if value.startswith("-") or value.startswith("$"):
            # `$VAR` is equally unsafe: the shell expands it before gcloud sees it, so a
            # variable holding "-m,..." fails exactly the same way.
            offenders.append(f"{i}: {stripped[:90]}")
    assert not offenders, (
        "these --args use the space-separated form with a value that begins with '-' "
        "(or a variable that may): gcloud will reject them. Use --args=<value>.\n  "
        + "\n  ".join(offenders)
    )
