"""Buyer prefill on the Shopify cart permalink, and the redaction that keeps it out of logs.

The shape was verified live 2026-09-18 (36/40 Tier B merchants landed on a prefilled checkout):
    /cart/{variant}:{qty}?attributes[pivota_click_id]=...&checkout[email]=...
        &checkout[shipping_address][<field>]=...
"""

from urllib.parse import quote, quote_plus, unquote, urlparse

import httpx
import pytest

from services.outbound_links_service import (
    REDACTED,
    CartPrefill,
    build_shopify_cart_permalink,
    cart_prefill_refusal,
    redact_cart_permalink,
)


@pytest.fixture(autouse=True)
def _no_real_network(monkeypatch):
    """Nothing in this file may reach the network. Any request that is not on a MockTransport
    fails the test instead of silently going out."""

    async def refuse_async(self, request):
        raise AssertionError(f"un-mocked network request: {request.method} {request.url.host}")

    def refuse_sync(self, request):
        raise AssertionError(f"un-mocked network request: {request.method} {request.url.host}")

    monkeypatch.setattr(httpx.AsyncHTTPTransport, "handle_async_request", refuse_async)
    monkeypatch.setattr(httpx.HTTPTransport, "handle_request", refuse_sync)


JUDYDOLL = CartPrefill(
    email="ucp-probe@pivota.cc", first_name="Pivota", last_name="Probe",
    address1="1209 Orange Street", city="Wilmington", province="DE", zip="19801",
    country="US", phone="+12025550142",
)
JUDYDOLL_LINK = (
    "https://judydoll.com/cart/50041364447509:1?attributes[pivota_click_id]=clk_j"
    "&checkout[email]=ucp-probe%40pivota.cc"
    "&checkout[shipping_address][first_name]=Pivota"
    "&checkout[shipping_address][last_name]=Probe"
    "&checkout[shipping_address][address1]=1209%20Orange%20Street"
    "&checkout[shipping_address][city]=Wilmington"
    "&checkout[shipping_address][province]=DE"
    "&checkout[shipping_address][zip]=19801"
    "&checkout[shipping_address][country]=US"
    "&checkout[shipping_address][phone]=%2B12025550142"
)


def _buyer(**overrides):
    fields = dict(
        email="ucp-probe@pivota.cc", first_name="Pivota", last_name="Probe",
        address1="1209 Orange Street", city="Wilmington", province="DE", zip="19801",
        country="US", phone="+12025550142",
    )
    fields.update(overrides)
    return CartPrefill(**fields)


def _pairs(url):
    """Split the query WITHOUT a parser that would normalise the literal brackets."""
    query = urlparse(url).query
    return [tuple(p.split("=", 1)) for p in query.split("&")]


# --- no buyer: byte-identical to the builder before `buyer` existed -----------------------

# Generated by running the builder at 7b274ed5 (before this change) over these inputs.
PINNED_WITHOUT_BUYER = [
    (dict(shop_domain="teststore.com", variant_id="46123456789", click_id="clk_abc123", quantity=2),
     "https://teststore.com/cart/46123456789:2?attributes[pivota_click_id]=clk_abc123"),
    (dict(shop_domain="https://Shop.Example.com/products/x?y=1",
          variant_id="gid://shopify/ProductVariant/999", click_id="clk a/b&c=d", quantity=0),
     "https://shop.example.com/cart/999:1?attributes[pivota_click_id]=clk%20a%2Fb%26c%3Dd"),
    (dict(shop_domain="judydoll.com", variant_id="50041364447509",
          click_id="clk_permalinkprobe_judydoll_com"),
     "https://judydoll.com/cart/50041364447509:1?attributes[pivota_click_id]=clk_permalinkprobe_judydoll_com"),
    (dict(shop_domain="genabelle.com", variant_id="123", click_id=""),
     "https://genabelle.com/cart/123:1"),
    (dict(shop_domain="genabelle.com", variant_id="123", click_id="  ", quantity="3"),
     "https://genabelle.com/cart/123:3"),
    (dict(shop_domain="x.myshopify.com:443", variant_id=" 77 ", click_id="clk_ü", quantity=None),
     "https://x.myshopify.com/cart/77:1?attributes[pivota_click_id]=clk_%C3%BC"),
    (dict(shop_domain="teststore.com", variant_id="SKU-ABC", click_id="clk_x"), None),
    (dict(shop_domain="", variant_id="123", click_id="clk_x"), None),
]


@pytest.mark.parametrize("kwargs,expected", PINNED_WITHOUT_BUYER)
def test_without_a_buyer_the_permalink_is_byte_identical_to_before(kwargs, expected):
    assert build_shopify_cart_permalink(**kwargs) == expected
    assert build_shopify_cart_permalink(**kwargs, buyer=None) == expected


# --- accepting -----------------------------------------------------------------------------


def test_the_judydoll_values_produce_the_documented_shopify_keys_exactly():
    url = build_shopify_cart_permalink(
        shop_domain="judydoll.com", variant_id="50041364447509", click_id="clk_j", buyer=JUDYDOLL
    )
    assert url == JUDYDOLL_LINK
    assert cart_prefill_refusal(JUDYDOLL) is None


def test_a_non_ascii_city_round_trips_through_percent_encoding():
    city = "Chiyoda-ku 千代田区"
    url = build_shopify_cart_permalink(
        shop_domain="tieut.jp", variant_id="1", click_id="clk_t",
        buyer=_buyer(city=city, country="JP", province="JP-13", zip="100-0005"),
    )
    assert url is not None
    assert url.isascii()
    decoded = {k: unquote(v) for k, v in _pairs(url)}
    assert decoded["checkout[shipping_address][city]"] == city
    assert decoded["checkout[shipping_address][country]"] == "JP"


def test_empty_optional_fields_are_omitted_entirely_never_sent_empty():
    url = build_shopify_cart_permalink(
        shop_domain="s.com", variant_id="1", click_id="clk",
        buyer=_buyer(address2="", province=None, zip="   ", phone=None),
    )
    keys = [k for k, _ in _pairs(url)]
    for absent in ("address2", "province", "zip", "phone"):
        assert f"checkout[shipping_address][{absent}]" not in keys
    assert all(v for _, v in _pairs(url)), "no key may be emitted with an empty value"
    assert "=&" not in url and not url.endswith("=")


def test_address2_is_emitted_when_given():
    url = build_shopify_cart_permalink(
        shop_domain="s.com", variant_id="1", click_id="clk", buyer=_buyer(address2="Suite 5"),
    )
    assert "checkout[shipping_address][address2]=Suite%205" in url


def test_a_value_cannot_smuggle_extra_parameters():
    url = build_shopify_cart_permalink(
        shop_domain="s.com", variant_id="1", click_id="clk",
        buyer=_buyer(address1="1 Main&checkout[email]=evil@x.com#frag"),
    )
    keys = [k for k, _ in _pairs(url)]
    assert keys.count("checkout[email]") == 1
    assert "#" not in url
    assert dict(_pairs(url))["checkout[email]"] == "ucp-probe%40pivota.cc"


def test_a_lowercase_country_is_emitted_uppercase():
    url = build_shopify_cart_permalink(
        shop_domain="s.com", variant_id="1", click_id="clk", buyer=_buyer(country="us"))
    assert "checkout[shipping_address][country]=US" in url


# --- refusing ------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "overrides,reason",
    [
        (dict(country="USA"), "country_not_iso2"),
        (dict(country="U1"), "country_not_iso2"),
        (dict(email="a@b"), "email_implausible"),
        (dict(email="not-an-email"), "email_implausible"),
        (dict(email="a b@c.com"), "email_implausible"),
        (dict(address1="1 Main\r\nX-Evil: 1"), "address1_control_character"),
        (dict(city="Wilming\x00ton"), "city_control_character"),
        (dict(last_name="Pro\nbe"), "last_name_control_character"),
        (dict(address1="x" * 257), "address1_too_long"),
        (dict(email=("a" * 251) + "@b.com"), "email_too_long"),
        (dict(phone="202-555-0142"), "phone_not_e164"),
        (dict(first_name=""), "first_name_missing"),
        (dict(address1="   "), "address1_missing"),
        (dict(zip=19801), "zip_not_a_string"),
    ],
)
def test_refused_buyers_produce_no_link_at_all(overrides, reason):
    buyer = _buyer(**overrides)
    assert cart_prefill_refusal(buyer) == reason
    assert build_shopify_cart_permalink(
        shop_domain="s.com", variant_id="1", click_id="clk", buyer=buyer
    ) is None


def test_exactly_256_characters_is_accepted():
    buyer = _buyer(address1="x" * 256)
    assert cart_prefill_refusal(buyer) is None
    assert build_shopify_cart_permalink(shop_domain="s.com", variant_id="1", click_id="c", buyer=buyer)


def test_something_that_is_not_a_cart_prefill_is_refused():
    assert cart_prefill_refusal({"email": "a@b.co"}) == "not_a_cart_prefill"
    assert build_shopify_cart_permalink(
        shop_domain="s.com", variant_id="1", click_id="c", buyer={"email": "a@b.co"}
    ) is None


def test_cart_prefill_is_frozen():
    with pytest.raises(Exception):
        JUDYDOLL.email = "other@x.com"  # type: ignore[misc]


# --- redaction -----------------------------------------------------------------------------


def _pii_forms(value):
    return {value, quote(value, safe=""), quote_plus(value)}


def test_redaction_removes_every_buyer_value_and_keeps_host_path_and_click_id():
    red = redact_cart_permalink(JUDYDOLL_LINK)
    assert red.startswith("https://judydoll.com/cart/50041364447509:1?")
    assert "attributes[pivota_click_id]=clk_j" in red
    for value in ("ucp-probe@pivota.cc", "1209 Orange Street", "Wilmington", "19801", "+12025550142",
                  "Pivota", "Probe"):
        for form in _pii_forms(value):
            assert form not in red, form
    # keys survive, values become REDACTED
    assert "checkout[email]=REDACTED" in red
    assert red.count(REDACTED) == 9


def test_redaction_handles_the_percent_encoded_keys_shopify_re_emits_on_the_next_hop():
    hop = (
        "https://luafeejp.com/cart/52912527868213:1?attributes%5Bpivota_click_id%5D=clk_l"
        "&checkout%5Bemail%5D=ucp-probe%40pivota.cc"
        "&checkout%5Bshipping_address%5D%5Baddress1%5D=1-1+Marunouchi&cart_link_id=hNKeFU9Z"
    )
    red = redact_cart_permalink(hop)
    assert "ucp-probe" not in red and "Marunouchi" not in red
    assert "attributes%5Bpivota_click_id%5D=clk_l" in red
    assert urlparse(red).hostname == "luafeejp.com"
    assert urlparse(red).path == "/cart/52912527868213:1"


def test_redaction_also_covers_the_shop_pay_token_that_embeds_the_landing_url():
    hop = ("https://shop.app/checkout/10201629/cn/TOKEN/en-us/shoppay?shop_pay_token=eyJhbGci.PAYLOAD.sig"
           "&attributes%5Bpivota_click_id%5D=clk_p#section")
    red = redact_cart_permalink(hop)
    assert "PAYLOAD" not in red
    assert "#section" not in red
    assert "attributes%5Bpivota_click_id%5D=clk_p" in red


def test_redaction_drops_userinfo_and_redacts_a_bare_key():
    red = redact_cart_permalink("https://user:pw@s.com/cart/1:1?someone@example.com")
    assert "pw" not in red and "someone" not in red
    assert red == "https://s.com/cart/1:1?REDACTED"


def test_redaction_of_non_urls():
    assert redact_cart_permalink("") == ""
    assert redact_cart_permalink(None) == ""
    assert redact_cart_permalink("ucp-probe@pivota.cc") == REDACTED
