"""`infra/gcp/deploy_gateway.sh` — the prod gateway deploy path.

WHY THIS EXISTS. Until 2026-08-25 this script could not deploy the production gateway at all. It
hard-required `env.prod.gateway.yaml` and `secrets.prod.gateway.list`, which are git-ignored and
generated by `port_railway_env.py` from `railway variables --json` — and Railway was decommissioned
at the 2026-08-22 cutover. Every run of the script ended at that `exit 1`.

An unusable deploy script does not stop deploys. The gateway was deployed by hand with `gcloud`
instead, which runs NONE of the gates this file exists for:

  * `sweep_stale_tags()` never ran, so three tagged revisions sat pinned at minScale 2 running old
    code against live secrets until they were swept by hand;
  * `gcloud run deploy --image X` with no env flag inherits the previous revision's environment, so
    one revision carried `PIVOTA_COMMIT_SHA=6aa49526db95` on an image built from `17e7cfa8` —
    /health under-reported the deployed commit by 7 and the drift alarm reasoned about the wrong one.

So these tests are about the two properties that make the script usable and honest:

  1. a prod deploy ships CODE ONLY — it must never re-derive the live service's 382 environment
     variables from the retired platform as a side effect of shipping a commit; and
  2. the image tag and the stamped commit are the same value, written on EVERY deploy, so the
     revision cannot inherit a stale stamp.

The script is driven END TO END with `gcloud` and `curl` stubbed, and the assertions read the
recorded argv of the real `gcloud run deploy` / `update-traffic` calls. Asserting on the script's
TEXT instead would pass for a flag that is constructed and then never passed.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "infra" / "gcp" / "deploy_gateway.sh"

SHA = "17e7cfa8b91c4d2e6f0a3b5d8c7e9f1a2b3c4d5e"
OTHER_SHA = "6aa49526db95c1d2e3f4a5b6c7d8e9f0a1b2c3d4"
CANDIDATE_TAG = "c-" + SHA[-12:]

# One stale tag (no percent) plus the live 100% one. sweep_stale_tags must remove only the first:
# the JSON shape is what the script's inline python parses, and `percent` absent/0 is "stale".
TRAFFIC_JSON = (
    '{"status":{"traffic":['
    '{"tag":"c-oldoldoldold","revisionName":"gateway-00010-mar"},'
    '{"tag":"' + CANDIDATE_TAG + '","percent":100,"revisionName":"gateway-00042-xyz"}'
    "]}}"
)

GCLOUD_STUB = r"""#!/bin/sh
# Record the whole invocation, argv boundaries intact (tab-separated; no argument contains a tab).
{
  first=1
  for a in "$@"; do
    if [ "$first" = 1 ]; then printf '%s' "$a"; first=0; else printf '\t%s' "$a"; fi
  done
  printf '\n'
} >> "$STUB_CALLS"

case "$1 $2" in
  "run services")
    case "$3" in
      describe)
        case "$*" in
          *"--format=json"*)      printf '%s' "$STUB_TRAFFIC_JSON"; exit 0 ;;
          *"traffic.extract"*)    printf '%s\n' "$STUB_CAND_URL";   exit 0 ;;
          *"value(status.url)"*)  printf '%s\n' "$STUB_SERVICE_URL"; exit 0 ;;
          *)                      exit "$STUB_SERVICE_EXISTS_RC" ;;
        esac ;;
      update-traffic) exit 0 ;;
    esac ;;
  "run deploy")
    # Snapshot the merged env file NOW. The script deletes it from a `trap ... EXIT`, so by the
    # time the test reads argv the path is dangling — and a test that silently could not read it
    # would assert nothing about what `apply` actually sends.
    prev=""
    for a in "$@"; do
      [ "$prev" = "--env-vars-file" ] && cp "$a" "$STUB_ENV_FILE_COPY"
      prev="$a"
    done
    exit "$STUB_DEPLOY_RC" ;;
  "run jobs")
    case "$3" in
      create)  exit "$STUB_JOB_CREATE_RC" ;;
      # Without --wait this returns 0 as soon as the execution is CREATED rather than when it
      # PASSES, so the exit code stops meaning "healthy" and the gate opens for every deploy.
      execute)
        case "$*" in *"--wait"*) ;; *) echo "stub: execute without --wait" >&2; exit 9 ;; esac
        exit "$STUB_JOB_EXECUTE_RC" ;;
      delete)  exit 0 ;;
    esac ;;
  "logging read")  printf '%s' "$STUB_LOG_OUTPUT"; exit 0 ;;
  "auth print-identity-token") echo stub-token; exit 0 ;;
esac
exit 0
"""


class Run:
    def __init__(
        self,
        proc: subprocess.CompletedProcess,
        calls: list[list[str]],
        env_vars_file: str | None = None,
    ):
        self.proc, self.calls = proc, calls
        # Contents of whatever was passed to --env-vars-file, captured before the script's
        # EXIT trap removed it. None when no such flag was passed.
        self.env_vars_file = env_vars_file

    @property
    def rc(self) -> int:
        return self.proc.returncode

    @property
    def err(self) -> str:
        return self.proc.stderr

    @property
    def out(self) -> str:
        return self.proc.stdout

    def _match(self, *head: str) -> list[list[str]]:
        return [c for c in self.calls if tuple(c[: len(head)]) == head]

    def deploy(self) -> list[str]:
        found = self._match("run", "deploy")
        assert len(found) == 1, f"expected exactly one `run deploy`, got {len(found)}"
        return found[0]

    def traffic_calls(self) -> list[list[str]]:
        return self._match("run", "services", "update-traffic")

    def flag(self, argv: list[str], name: str) -> str | None:
        """Value of `--name value` or `--name=value`, or None when absent."""
        for i, a in enumerate(argv):
            if a == name:
                return argv[i + 1] if i + 1 < len(argv) else ""
            if a.startswith(name + "="):
                return a.split("=", 1)[1]
        return None


def _run(
    tmp_path: Path,
    env_arg: str = "prod",
    tag: str = SHA,
    *,
    config: str | None = None,
    service_exists: bool = True,
    job_execute_rc: int = 0,
    job_create_rc: int = 0,
    deploy_rc: int = 0,
    log_output: str = "",
    ported_files: "bool | str" = False,
    curl_out: str = "404",
    overrides: "dict[str, str] | None" = None,
) -> Run:
    """Run the REAL deploy_gateway.sh against stubs.

    The script is copied so `$HERE` — the only path it derives from its own location — points at a
    scratch directory. That is what lets the ported-file tests control whether those two files
    exist without writing into the repo's own infra/gcp.
    """
    here = tmp_path / "infra_gcp"
    here.mkdir()
    script = here / "deploy_gateway.sh"
    shutil.copy2(SCRIPT, script)
    # True writes both; "env" / "secrets" write just one, for the half-ported state a run
    # interrupted partway through port_railway_env.py leaves behind.
    if ported_files in (True, "env"):
        (here / f"env.{env_arg}.gateway.yaml").write_text('SOME_PORTED_KEY: "ported-value"\n')
    if ported_files in (True, "secrets"):
        (here / f"secrets.{env_arg}.gateway.list").write_text("SOME_SECRET=SOME_SECRET:latest\n")

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    (bin_dir / "gcloud").write_text(GCLOUD_STUB)
    (bin_dir / "curl").write_text('#!/bin/sh\nprintf %s "$STUB_CURL_OUT"\nexit 0\n')
    (bin_dir / "sleep").write_text("#!/bin/sh\nexit 0\n")
    for f in bin_dir.iterdir():
        f.chmod(0o755)

    calls_file = tmp_path / "calls.log"
    calls_file.touch()

    env = {
        **os.environ,
        "PATH": f"{bin_dir}:{os.environ['PATH']}",
        "GCLOUD": str(bin_dir / "gcloud"),
        "STUB_CALLS": str(calls_file),
        "STUB_TRAFFIC_JSON": TRAFFIC_JSON,
        "STUB_CAND_URL": f"https://{CANDIDATE_TAG}---gateway-abc.a.run.app",
        "STUB_SERVICE_URL": "https://gateway-abc.a.run.app",
        "STUB_SERVICE_EXISTS_RC": "0" if service_exists else "1",
        "STUB_JOB_EXECUTE_RC": str(job_execute_rc),
        "STUB_JOB_CREATE_RC": str(job_create_rc),
        "STUB_DEPLOY_RC": str(deploy_rc),
        "STUB_LOG_OUTPUT": log_output,
        "STUB_CURL_OUT": curl_out,
        "STUB_ENV_FILE_COPY": str(tmp_path / "env-vars-file.snapshot"),
    }
    env.pop("CONFIG", None)
    # The shape overrides are read from the ENVIRONMENT, so an operator who exported the incident
    # runbook's own `CONCURRENCY=20` in this shell would otherwise inject it into every test here -
    # and the default tests would pass while asserting nothing about the default.
    for shape_var in ("CONCURRENCY", "CONCURRENCY_LIMIT", "MIN_INSTANCES", "MAX_INSTANCES"):
        env.pop(shape_var, None)
    if config is not None:
        env["CONFIG"] = config
    env.update(overrides or {})

    proc = subprocess.run(
        ["bash", str(script), env_arg, tag],
        capture_output=True, text=True, timeout=120, env=env, cwd=str(tmp_path),
    )
    calls = [line.split("\t") for line in calls_file.read_text().splitlines() if line]
    snapshot = tmp_path / "env-vars-file.snapshot"
    return Run(proc, calls, snapshot.read_text() if snapshot.exists() else None)


# --------------------------------------------------------------------- the regression

def test_a_prod_deploy_needs_no_railway_ported_files(tmp_path):
    """THE REGRESSION, and the reason the gateway was being deployed by hand.

    No env.prod.gateway.yaml, no secrets.prod.gateway.list — the state of every checkout since
    Railway was decommissioned. Before this change the script exited 1 here, always.
    """
    r = _run(tmp_path, "prod", ported_files=False)
    assert r.rc == 0, f"prod deploy failed without the ported files:\n{r.err}"
    assert "port_railway_env" not in r.err


def test_shipping_code_does_not_rewrite_the_live_services_env_or_secrets(tmp_path):
    """The config rollback this change exists to make impossible.

    `--env-vars-file` and `--set-secrets` REPLACE the whole set. On the live prod gateway that is
    382 environment variables, re-derived from the retired platform, riding along with a code
    deploy — and reported as success.
    """
    argv = _run(tmp_path, "prod").deploy()
    assert "--env-vars-file" not in argv
    assert "--set-secrets" not in argv
    assert not any(a.startswith("--set-env-vars") for a in argv)


def test_the_only_env_var_a_prod_deploy_moves_is_the_commit_stamp(tmp_path):
    r = _run(tmp_path, "prod")
    assert r.flag(r.deploy(), "--update-env-vars") == f"PIVOTA_COMMIT_SHA={SHA}"


# ------------------------------------------------- the stamp cannot diverge from the image

@pytest.mark.parametrize("config,ported", [("preserve", False), ("apply", True)])
def test_the_image_and_the_stamp_name_the_same_commit(tmp_path, config, ported):
    """Both are `$TAG`. Pinned in BOTH modes, because a divergence in either is the same lie.

    Under `apply` the stamp travels in the merged env file rather than on the command line, so the
    file is read back and the two values compared.
    """
    r = _run(tmp_path, "prod", config=config, ported_files=ported)
    assert r.rc == 0, r.err
    argv = r.deploy()
    image = r.flag(argv, "--image")
    assert image is not None and image.endswith(f":{SHA}"), image

    if config == "preserve":
        stamped = r.flag(argv, "--update-env-vars").split("=", 1)[1]
    else:
        merged = r.env_vars_file
        assert merged is not None, "apply mode sent no --env-vars-file"
        stamped = [
            line.split(":", 1)[1].strip().strip('"')
            for line in merged.splitlines()
            if line.startswith("PIVOTA_COMMIT_SHA:")
        ][-1]
    assert stamped == image.rsplit(":", 1)[1]


def test_the_stamp_is_written_on_every_deploy_so_it_can_never_be_inherited(tmp_path):
    """The actual mechanism of the observed 7-commit under-report.

    Nobody set the image and the stamp to different values. A hand `gcloud run deploy --image X`
    passed no env flag at all, so Cloud Run carried the PREVIOUS revision's PIVOTA_COMMIT_SHA onto
    the new image. An absent flag is the failure, so absence is what this asserts against.
    """
    r = _run(tmp_path, "prod", tag=OTHER_SHA)
    argv = r.deploy()
    assert r.flag(argv, "--update-env-vars") == f"PIVOTA_COMMIT_SHA={OTHER_SHA}"


@pytest.mark.parametrize("environment", ["prod", "staging"])
def test_a_floating_tag_is_refused(tmp_path, environment):
    """`latest` is pushed beside `:$COMMIT_SHA` by cloudbuild.gateway.yaml, so it is always there
    to be typed — and it would stamp /health with a string that names no commit.

    STAGING IS THE ROW THAT MATTERS, and it was missing at first: prod also happens to refuse
    `latest` through the 40-character-sha rule below, so a prod-only test stays green with the
    floating-tag check deleted outright. Staging only WARNS about a non-sha tag, so it is the one
    environment where this check is the sole thing standing between an operator and a revision
    whose stamped commit is the word "latest". Asserting the reason, not just the exit code, for
    the same reason.
    """
    r = _run(tmp_path, environment, tag="latest")
    assert r.rc == 2
    assert "floating tag" in r.err, r.err
    assert not r.calls, "nothing should have been deployed"


@pytest.mark.parametrize("bad", ["17e7cfa8", "17E7CFA8B91C4D2E6F0A3B5D8C7E9F1A2B3C4D5E", "v1.2.3"])
def test_prod_refuses_a_tag_that_is_not_a_full_lowercase_sha(tmp_path, bad):
    r = _run(tmp_path, "prod", tag=bad)
    assert r.rc == 2, f"'{bad}' was accepted for prod"
    assert not r.calls


def test_staging_warns_about_a_non_sha_tag_but_still_deploys(tmp_path):
    r = _run(tmp_path, "staging", tag="local-build-1")
    assert r.rc == 0, r.err
    assert "not a 40-character sha" in r.err


# ------------------------------------------------------------------ apply stays opt-in

def test_apply_must_be_asked_for_by_name_and_still_requires_the_ported_files(tmp_path):
    r = _run(tmp_path, "prod", config="apply", ported_files=False)
    assert r.rc == 1
    assert "port_railway_env" in r.err
    assert not any(c[:2] == ["run", "deploy"] for c in r.calls)


def test_apply_rewrites_env_and_secrets_when_the_files_are_there(tmp_path):
    """`apply` must keep working — it is the only path that can configure a service from scratch."""
    r = _run(tmp_path, "prod", config="apply", ported_files=True)
    assert r.rc == 0, r.err
    argv = r.deploy()
    assert "--env-vars-file" in argv and "--set-secrets" in argv
    assert "--update-env-vars" not in argv
    secrets = r.flag(argv, "--set-secrets")
    # The DSNs port_railway_env.py's DROP_EXACT strips must still be re-mounted here.
    for name in ("DATABASE_URL=", "PCI_KB_DATABASE_URL=", "INGREDIENT_REFERENCE_DATABASE_URL="):
        assert name in secrets, f"{name} not re-mounted under CONFIG=apply"
    assert "SOME_SECRET=SOME_SECRET:latest" in secrets


def test_an_unknown_config_value_is_refused_rather_than_treated_as_preserve(tmp_path):
    r = _run(tmp_path, "prod", config="Preserve")
    assert r.rc == 2
    assert not r.calls


def test_preserve_is_refused_on_a_service_that_does_not_exist_yet(tmp_path):
    """A first revision takes traffic IMMEDIATELY — no --no-traffic, no candidate tag, no health
    gate. Creating one from a single environment variable would put an unbootable service straight
    in front of users, so this is the one case `preserve` must not attempt."""
    r = _run(tmp_path, "prod", service_exists=False)
    assert r.rc == 2
    assert "CONFIG=apply" in r.err
    assert not any(c[:2] == ["run", "deploy"] for c in r.calls)


# -------------------------------------------------- the gates the hand deploy skipped

def test_the_candidate_takes_no_traffic_until_it_has_been_verified(tmp_path):
    argv = _run(tmp_path, "prod").deploy()
    assert "--no-traffic" in argv
    assert argv[argv.index("--tag") + 1] == CANDIDATE_TAG


def test_traffic_never_shifts_when_the_in_vpc_probe_fails(tmp_path):
    """Prod ingress is internal-and-cloud-load-balancing, so the direct curl always 404s and the
    in-VPC job is the probe that actually decides. Its exit code is the verdict."""
    # The log line says 200 and the job says otherwise. The verdict is the EXIT CODE: a scrape of
    # Cloud Logging must never be able to talk the gate INTO a promotion the probe refused.
    r = _run(tmp_path, "prod", job_execute_rc=1, log_output="PROBE_STATUS=200\n")
    assert r.rc == 1
    assert r.traffic_calls() == [], "promoted a candidate that failed its health check"


def test_traffic_never_shifts_when_the_probe_job_could_not_even_be_created(tmp_path):
    """`set -e` does not fire inside probe_health, so an unchecked create was entirely silent and
    "the job exited 0" rested on a job that never existed. A stale 200 in the logs must not rescue
    it either."""
    r = _run(tmp_path, "prod", job_create_rc=1, log_output="PROBE_STATUS=200\n")
    assert r.rc == 1
    assert r.traffic_calls() == []


def test_a_healthy_candidate_is_promoted_even_when_cloud_logging_has_not_caught_up(tmp_path):
    """The 2026-08-25 shape, ported here from deploy_backend.sh: the probe exits 0 but its log line
    is not queryable yet. Reading the verdict back out of Cloud Logging stranded a healthy backend
    revision at 0%; the gateway's copy of the gate had the same unbounded-ingestion-lag guess."""
    r = _run(tmp_path, "prod", job_execute_rc=0, log_output="")
    assert r.rc == 0, r.err
    assert any("--to-latest" in c for c in r.traffic_calls())


def test_stale_candidate_tags_are_swept_after_promotion(tmp_path):
    """The gate hand deploys skipped. A tagged revision is never garbage-collected and min-instances
    is 2, so each old candidate keeps instances running forever against the secret VERSIONS that
    were latest when they booted."""
    r = _run(tmp_path, "prod")
    removals = [c for c in r.traffic_calls() if any(a.startswith("--remove-tags") for a in c)]
    assert len(removals) == 1, f"expected one sweep, got {removals}"
    argv = removals[0]
    assert r.flag(argv, "--remove-tags") == "c-oldoldoldold"
    # The LIVE revision's tag serves 100% and must survive.
    assert CANDIDATE_TAG not in r.flag(argv, "--remove-tags")


def test_the_sweep_runs_on_a_preserve_deploy_too(tmp_path):
    """The whole point: the flow that was being bypassed must be reachable by the DEFAULT path."""
    r = _run(tmp_path, "prod", config=None)
    assert r.rc == 0, r.err
    assert any(any(a.startswith("--remove-tags") for a in c) for c in r.traffic_calls())


def test_a_failed_deploy_never_reaches_the_traffic_shift(tmp_path):
    r = _run(tmp_path, "prod", deploy_rc=1)
    assert r.rc != 0
    assert r.traffic_calls() == []


@pytest.mark.parametrize("present", [True, "env", "secrets"])
def test_preserve_says_so_when_ported_config_files_are_sitting_right_there(tmp_path, present):
    """The one way the new default can bite.

    A deploy run straight after `port_railway_env.py --apply` ships the image and NOTHING ELSE,
    while still printing a promoted, health-checked success — the same shape deploy_backend.sh
    refuses for WORKERS/MOUNT_DB. Their presence on disk is the only intent signal available, so
    it must not be ignored. A warning, not a refusal: these are git-ignored build artefacts that
    can outlive by months the port that made them.

    HALF-PORTED COUNTS. `port_railway_env.py` writes two files, and a run interrupted between
    them leaves one — which is when an operator most needs telling, and the case a `&&` here
    would silently drop. Hence the parametrize, and hence `||` rather than `&&` in the guard.
    """
    r = _run(tmp_path, "prod", ported_files=present)   # preserve is the default
    assert r.rc == 0, r.err
    assert "CONFIG=apply" in r.err
    assert "IGNORES" in r.err
    # It must still be a preserve deploy — the warning does not change what is sent.
    assert "--env-vars-file" not in r.deploy()


def test_preserve_is_quiet_when_there_is_no_ported_config_to_ignore(tmp_path):
    """The normal case — a fresh checkout. Warning on every deploy would train people past it."""
    r = _run(tmp_path, "prod", ported_files=False)
    assert r.rc == 0, r.err
    assert "IGNORES" not in r.err


def test_apply_can_still_create_a_service_from_scratch(tmp_path):
    """`apply` on a service that does not exist is now the documented way to stand one up, and it
    was the one path through this script with no coverage at all.

    `--no-traffic` and `--tag` are REJECTED by gcloud on service creation, so a candidate flow that
    leaked into the first deploy would fail the whole thing.
    """
    r = _run(tmp_path, "staging", config="apply", ported_files=True, service_exists=False)
    assert r.rc == 0, r.err
    argv = r.deploy()
    assert "--no-traffic" not in argv
    assert "--tag" not in argv
    assert "--env-vars-file" in argv
    # A first revision already holds 100%; shifting traffic to itself is not attempted.
    assert not any("--to-latest" in c for c in r.traffic_calls())


# ─────────────────────────────────────────────────────────────────────────────────────────────────
# THE SHAPE OVERRIDES
#
# `preserve` keeps env and secrets but REASSERTS the shape, so every gateway deploy re-sends
# --concurrency/--min-instances/--max-instances. The 2026-09-15 pivota-pg CPU incident was mitigated
# by hand-setting the live gateway to concurrency 20 / min 4; without these overrides the next
# scripted deploy would have silently restored 80 / 2 while reporting success.
#
# Each knob is pinned in BOTH directions. A test that only checks the default passes when the flag
# does nothing; a test that only checks the override passes when the default has drifted. Before
# these existed the whole suite passed identically with the override code removed.
# ─────────────────────────────────────────────────────────────────────────────────────────────────


def test_unset_overrides_keep_the_prod_shape_constants(tmp_path):
    r = _run(tmp_path, config="preserve")
    assert r.rc == 0, r.err
    assert r.flag(r.deploy(), "--concurrency") == "80"
    assert r.flag(r.deploy(), "--min-instances") == "2"
    assert r.flag(r.deploy(), "--max-instances") == "20"


@pytest.mark.parametrize("name", ["CONCURRENCY", "CONCURRENCY_LIMIT"])
def test_either_concurrency_name_reaches_gcloud(tmp_path, name):
    """CONCURRENCY_LIMIT is the repo's vocabulary; CONCURRENCY is the incident runbook's. An
    operator reaching for this mid-incident must not get 80 because they typed the other one."""
    r = _run(tmp_path, config="preserve", overrides={name: "20"})
    assert r.rc == 0, r.err
    assert r.flag(r.deploy(), "--concurrency") == "20"


def test_disagreeing_concurrency_names_are_refused(tmp_path):
    r = _run(tmp_path, config="preserve", overrides={"CONCURRENCY": "20", "CONCURRENCY_LIMIT": "40"})
    assert r.rc == 2
    assert "disagree" in r.err
    assert not r.calls or all(c[:2] != ["run", "deploy"] for c in r.calls)


def test_agreeing_concurrency_names_are_accepted(tmp_path):
    r = _run(tmp_path, config="preserve", overrides={"CONCURRENCY": "20", "CONCURRENCY_LIMIT": "20"})
    assert r.rc == 0, r.err
    assert r.flag(r.deploy(), "--concurrency") == "20"


@pytest.mark.parametrize("bad", ["0", "default", "007", "-5", "abc", "20 --min-instances 0"])
def test_a_concurrency_that_would_silently_widen_is_refused(tmp_path, bad):
    """`0` reads as UNLIMITED and `default` CLEARS the limit - both restore the 80 this override
    exists to hold off, while the deploy reports success. They must fail before any revision
    exists, not after."""
    r = _run(tmp_path, config="preserve", overrides={"CONCURRENCY": bad})
    assert r.rc == 2, f"{bad!r} was accepted: {r.err}"
    assert all(c[:2] != ["run", "deploy"] for c in r.calls)


@pytest.mark.parametrize(
    "overrides,flag,expected",
    [
        ({"MIN_INSTANCES": "4"}, "--min-instances", "4"),
        ({"MIN_INSTANCES": "0"}, "--min-instances", "0"),
        ({"MAX_INSTANCES": "8"}, "--max-instances", "8"),
    ],
)
def test_instance_overrides_reach_gcloud(tmp_path, overrides, flag, expected):
    r = _run(tmp_path, config="preserve", overrides=overrides)
    assert r.rc == 0, r.err
    assert r.flag(r.deploy(), flag) == expected


@pytest.mark.parametrize("overrides", [{"MIN_INSTANCES": "04"}, {"MIN_INSTANCES": "two"}, {"MAX_INSTANCES": "0"}, {"MAX_INSTANCES": "0x10"}])
def test_malformed_instance_overrides_are_refused(tmp_path, overrides):
    r = _run(tmp_path, config="preserve", overrides=overrides)
    assert r.rc == 2, r.err
    assert all(c[:2] != ["run", "deploy"] for c in r.calls)


def test_an_override_reaches_the_candidate_revision_itself(tmp_path):
    """The candidate IS the revision that gets promoted - `update-traffic --to-latest` carries no
    shape flags - so an override that only landed on a later call would never take effect."""
    r = _run(tmp_path, config="preserve", overrides={"CONCURRENCY_LIMIT": "20"})
    assert r.rc == 0, r.err
    deploy = r.deploy()
    assert "--no-traffic" in deploy
    assert r.flag(deploy, "--concurrency") == "20"
    assert deploy.count("--concurrency") == 1
    for call in r.traffic_calls():
        assert "--concurrency" not in call


# ─────────────────────────────────────────────────────────────────────────────────────────────────
# THE SHAPE IS ANNOUNCED BEFORE IT IS APPLIED
#
# The overrides above are only half a control. A successful run used to print exactly one line -
# `deployed gateway -> ... (100% traffic)` - which is byte-identical whether CONCURRENCY_LIMIT=20
# took effect or the operator fat-fingered the prefix and shipped the default 80. Mid-incident that
# is the difference between a mitigation held and a mitigation silently reverted, with nothing on
# screen to tell them apart.
#
# Every test here asserts the PRINTED value against the RECORDED ARGV of the same run. Asserting the
# text alone would pass for a line that prints `concurrency=20` while gcloud receives 80 - which is
# the whole failure the line exists to catch, reproduced inside its own test.
# ─────────────────────────────────────────────────────────────────────────────────────────────────

SHAPE_RE = re.compile(
    r"^shape: concurrency=(?P<c>\S+) \((?P<c_src>[^)]*)\) "
    r"min-instances=(?P<min>\S+) \((?P<min_src>[^)]*)\) "
    r"max-instances=(?P<max>\S+) \((?P<max_src>[^)]*)\)$",
    re.M,
)


def _shape(r: Run) -> dict[str, str]:
    """The printed shape line, and the same three flags as gcloud actually received them.

    Returned together on purpose: every assertion below gets to compare the two halves, and a
    helper that returned only the text would quietly re-enable the failure mode being tested.
    """
    m = SHAPE_RE.search(r.out)
    assert m, f"no `shape:` line on stdout:\n{r.out}"
    deploy = r.deploy()
    return {
        **m.groupdict(),
        "argv_c": r.flag(deploy, "--concurrency"),
        "argv_min": r.flag(deploy, "--min-instances"),
        "argv_max": r.flag(deploy, "--max-instances"),
    }


def test_the_printed_shape_is_the_shape_gcloud_gets_with_no_overrides(tmp_path):
    r = _run(tmp_path, config="preserve")
    assert r.rc == 0, r.err
    s = _shape(r)
    assert (s["c"], s["min"], s["max"]) == ("80", "2", "20")
    assert (s["argv_c"], s["argv_min"], s["argv_max"]) == (s["c"], s["min"], s["max"])
    # Concurrency's fallback is a literal 80 shared by both environments, not a per-env constant,
    # and is labelled so - an operator told `prod constant` would go looking for a value the script
    # does not have.
    assert s["c_src"] == "default"
    assert (s["min_src"], s["max_src"]) == ("prod constant", "prod constant")


def test_the_printed_shape_is_the_shape_gcloud_gets_with_the_incident_overrides(tmp_path):
    """The literal 2026-09-15 mitigation shape, and the case that makes the SOURCE tag load-bearing.

    MAX_INSTANCES=20 is also the prod constant, so the printed VALUE is `20` whether the override
    was read or dropped on the floor. Only the source tag separates "my override landed" from "the
    default happened to agree with me" - which is the question the operator is actually asking.
    """
    r = _run(
        tmp_path,
        config="preserve",
        overrides={"CONCURRENCY_LIMIT": "20", "MIN_INSTANCES": "4", "MAX_INSTANCES": "20"},
    )
    assert r.rc == 0, r.err
    s = _shape(r)
    assert (s["c"], s["min"], s["max"]) == ("20", "4", "20")
    assert (s["argv_c"], s["argv_min"], s["argv_max"]) == (s["c"], s["min"], s["max"])
    assert (s["c_src"], s["min_src"], s["max_src"]) == ("CONCURRENCY_LIMIT", "MIN_INSTANCES", "MAX_INSTANCES")


@pytest.mark.parametrize("name", ["CONCURRENCY", "CONCURRENCY_LIMIT"])
def test_the_printed_source_names_the_concurrency_variable_that_was_read(tmp_path, name):
    """Both names work, so the line has to say which one it took. An operator who typed the alias
    and saw the canonical name echoed back would have no way to tell the alias was honoured."""
    r = _run(tmp_path, config="preserve", overrides={name: "20"})
    assert r.rc == 0, r.err
    s = _shape(r)
    assert s["c"] == s["argv_c"] == "20"
    assert s["c_src"] == name


def test_a_zero_min_instances_prints_as_an_override_not_as_the_constant(tmp_path):
    """MIN_INSTANCES=0 is a legitimate override (scale to zero) whose value is falsy. Reported as
    `prod constant` it would read as "your override was ignored" on the one deploy where it was not."""
    r = _run(tmp_path, config="preserve", overrides={"MIN_INSTANCES": "0"})
    assert r.rc == 0, r.err
    s = _shape(r)
    assert s["min"] == s["argv_min"] == "0"
    assert s["min_src"] == "MIN_INSTANCES"


def test_the_printed_shape_follows_the_environments_own_constants(tmp_path):
    """Staging's constants differ from prod's in both value and name. Pins the line to the env the
    script resolved rather than to a prod-shaped string that happens to be right one time in two."""
    r = _run(tmp_path, "staging", config="preserve")
    assert r.rc == 0, r.err
    s = _shape(r)
    assert (s["min"], s["max"]) == ("1", "4")
    assert (s["argv_min"], s["argv_max"]) == (s["min"], s["max"])
    assert (s["min_src"], s["max_src"]) == ("staging constant", "staging constant")


def test_the_shape_is_printed_before_the_deploy_it_describes(tmp_path):
    """Order is the point. Printed after the promote it is a receipt for a shape already serving
    traffic; printed before, a `(default)` where an override was expected is still cancellable with
    ^C. `verifying candidate at` is echoed strictly after `run deploy` returns, so it anchors this."""
    r = _run(tmp_path, config="preserve", overrides={"CONCURRENCY_LIMIT": "20"})
    assert r.rc == 0, r.err
    shape_at = r.out.index("shape: concurrency=")
    assert shape_at < r.out.index("verifying candidate at"), r.out
    assert shape_at < r.out.index("(100% traffic)"), r.out


# ─────────────────────────────────────────────────────────────────────────────────────────────────
# THE RUNBOOK QUOTES THIS LINE, SO THE RUNBOOK IS PINNED TO IT
#
# docs/runbooks/operating_on_gcp_production.md teaches the operator to read the `shape:` line by
# showing two of them verbatim, and its whole argument rests on which SOURCE TAG appears where.
# Prose about output drifts silently from the output. It drifted once while this was being written:
# the second block was first pasted from a run that omitted MAX_INSTANCES rather than misspelling
# it, so it showed `(prod constant)` for a variable the documented command actually sets.
#
# A runbook that quotes output the script cannot produce is worse than one that quotes none: it is
# read mid-incident, and it teaches the operator to accept a line that never appears.
# ─────────────────────────────────────────────────────────────────────────────────────────────────

RUNBOOK = REPO / "docs" / "runbooks" / "operating_on_gcp_production.md"

# (documented line, the overrides the runbook says produce it). The second is the first with
# MAX_INSTANCES misspelt - the runbook's point is that every NUMBER is identical and only the tag
# moves, which is only true if both of these are real.
RUNBOOK_SHAPE_LINES = [
    ({"CONCURRENCY_LIMIT": "20", "MIN_INSTANCES": "4", "MAX_INSTANCES": "20"},
     "shape: concurrency=20 (CONCURRENCY_LIMIT) min-instances=4 (MIN_INSTANCES) max-instances=20 (MAX_INSTANCES)"),
    ({"CONCURRENCY_LIMIT": "20", "MIN_INSTANCES": "4", "MAX_INSTANCE": "20"},
     "shape: concurrency=20 (CONCURRENCY_LIMIT) min-instances=4 (MIN_INSTANCES) max-instances=20 (prod constant)"),
]


def test_the_runbook_quotes_the_shape_lines_this_script_actually_prints():
    """Both blocks must still be in the runbook, in order, exactly as written."""
    doc = RUNBOOK.read_text()
    quoted = re.findall(r"^shape: .*$", doc, re.M)
    assert quoted == [line for _, line in RUNBOOK_SHAPE_LINES], (
        "docs/runbooks/operating_on_gcp_production.md no longer quotes these lines in this order:\n"
        + "\n".join(quoted)
    )


@pytest.mark.parametrize(
    "overrides,documented", RUNBOOK_SHAPE_LINES, ids=["as-documented", "MAX_INSTANCES-misspelt"]
)
def test_the_documented_shape_line_is_byte_exact_and_matches_gcloud(tmp_path, overrides, documented):
    r = _run(tmp_path, "prod", config="preserve", overrides=overrides)
    assert r.rc == 0, r.err
    printed = [l for l in r.out.splitlines() if l.startswith("shape:")]
    assert printed == [documented], f"runbook quotes:\n  {documented}\nscript printed:\n  " + "\n  ".join(printed)
    # And the documented line is not merely text the script emits - it is the shape gcloud got.
    s = _shape(r)
    assert (s["argv_c"], s["argv_min"], s["argv_max"]) == (s["c"], s["min"], s["max"])


RUNBOOK_GATEWAY_COMMAND = re.compile(
    r"^(?P<prefix>(?:[A-Z_]+=\S+ )+)bash infra/gcp/deploy_gateway\.sh prod <full sha>$", re.M
)


def test_the_runbooks_gateway_command_is_the_one_this_script_accepts(tmp_path):
    """The runbook's headline gateway invocation, RUN rather than grepped. A command whose variable
    names have drifted from the script's is a mid-incident dead end - and the misspelt-variable
    failure it warns about is precisely the one it would then be causing.

    A `name in script_text` check cannot catch that: the old names survive in comments, and as
    substrings of a renamed variable. So the prefix is parsed out of the runbook and handed to the
    real script, and every shape knob must come back tagged with the name that was passed - not
    `(default)` or `(prod constant)` - and reach gcloud with the documented value.
    """
    commands = RUNBOOK_GATEWAY_COMMAND.findall(RUNBOOK.read_text())
    assert len(commands) == 1, f"expected one documented prod gateway command, found {commands}"
    prefix = dict(kv.split("=", 1) for kv in commands[0].split())
    assert prefix.pop("CONFIG") == "preserve"
    assert set(prefix) == {"CONCURRENCY_LIMIT", "MIN_INSTANCES", "MAX_INSTANCES"}, prefix

    r = _run(tmp_path, "prod", config="preserve", overrides=prefix)
    assert r.rc == 0, r.err
    s = _shape(r)
    assert (s["c_src"], s["min_src"], s["max_src"]) == ("CONCURRENCY_LIMIT", "MIN_INSTANCES", "MAX_INSTANCES")
    assert (s["argv_c"], s["argv_min"], s["argv_max"]) == (
        prefix["CONCURRENCY_LIMIT"], prefix["MIN_INSTANCES"], prefix["MAX_INSTANCES"],
    )
