"""`infra/gcp/deploy_gateway.sh` — the prod gateway deploy path.

WHY THIS EXISTS. Until 2026-08-25 this script could not deploy the production gateway at all. It
hard-required `env.prod.gateway.yaml` and `secrets.prod.gateway.list`, which are git-ignored and
generated by `port_railway_env.py` from `railway variables --json` — and Railway was decommissioned
at the 2026-08-22 cutover. Every run of the script ended at that `exit 1`.

An unusable deploy script does not stop deploys. The gateway was deployed by hand with `gcloud`
instead, which runs NONE of the gates this file exists for:

  * `sweep_stale_tags()` never ran, so three tagged revisions sat pinned at minScale 2 running old
    code against live secrets until they were swept by hand;
  * `gcloud run deploy --image X` with no env flag inherits the previous revision's environment, so
    one revision carried `PIVOTA_COMMIT_SHA=6aa49526db95` on an image built from `17e7cfa8` —
    /health under-reported the deployed commit by 7 and the drift alarm reasoned about the wrong one.

So these tests are about the two properties that make the script usable and honest:

  1. a prod deploy ships CODE ONLY — it must never re-derive the live service's 382 environment
     variables from the retired platform as a side effect of shipping a commit; and
  2. the image tag and the stamped commit are the same value, written on EVERY deploy, so the
     revision cannot inherit a stale stamp.

The script is driven END TO END with `gcloud` and `curl` stubbed, and the assertions read the
recorded argv of the real `gcloud run deploy` / `update-traffic` calls. Asserting on the script's
TEXT instead would pass for a flag that is constructed and then never passed.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "infra" / "gcp" / "deploy_gateway.sh"

SHA = "17e7cfa8b91c4d2e6f0a3b5d8c7e9f1a2b3c4d5e"
OTHER_SHA = "6aa49526db95c1d2e3f4a5b6c7d8e9f0a1b2c3d4"
CANDIDATE_TAG = "c-" + SHA[-12:]

# One stale tag (no percent) plus the live 100% one. sweep_stale_tags must remove only the first:
# the JSON shape is what the script's inline python parses, and `percent` absent/0 is "stale".
TRAFFIC_JSON = (
    '{"status":{"traffic":['
    '{"tag":"c-oldoldoldold","revisionName":"gateway-00010-mar"},'
    '{"tag":"' + CANDIDATE_TAG + '","percent":100,"revisionName":"gateway-00042-xyz"}'
    "]}}"
)

GCLOUD_STUB = r"""#!/bin/sh
# Record the whole invocation, argv boundaries intact (tab-separated; no argument contains a tab).
{
  first=1
  for a in "$@"; do
    if [ "$first" = 1 ]; then printf '%s' "$a"; first=0; else printf '\t%s' "$a"; fi
  done
  printf '\n'
} >> "$STUB_CALLS"

case "$1 $2" in
  "run services")
    case "$3" in
      describe)
        case "$*" in
          *"--format=json"*)      printf '%s' "$STUB_TRAFFIC_JSON"; exit 0 ;;
          *"traffic.extract"*)    printf '%s\n' "$STUB_CAND_URL";   exit 0 ;;
          *"value(status.url)"*)  printf '%s\n' "$STUB_SERVICE_URL"; exit 0 ;;
          *)                      exit "$STUB_SERVICE_EXISTS_RC" ;;
        esac ;;
      update-traffic) exit 0 ;;
    esac ;;
  "run deploy")
    # Snapshot the merged env file NOW. The script deletes it from a `trap ... EXIT`, so by the
    # time the test reads argv the path is dangling — and a test that silently could not read it
    # would assert nothing about what `apply` actually sends.
    prev=""
    for a in "$@"; do
      [ "$prev" = "--env-vars-file" ] && cp "$a" "$STUB_ENV_FILE_COPY"
      prev="$a"
    done
    exit "$STUB_DEPLOY_RC" ;;
  "run jobs")
    case "$3" in
      create)  exit "$STUB_JOB_CREATE_RC" ;;
      # Without --wait this returns 0 as soon as the execution is CREATED rather than when it
      # PASSES, so the exit code stops meaning "healthy" and the gate opens for every deploy.
      execute)
        case "$*" in *"--wait"*) ;; *) echo "stub: execute without --wait" >&2; exit 9 ;; esac
        exit "$STUB_JOB_EXECUTE_RC" ;;
      delete)  exit 0 ;;
    esac ;;
  "logging read")  printf '%s' "$STUB_LOG_OUTPUT"; exit 0 ;;
  "auth print-identity-token") echo stub-token; exit 0 ;;
esac
exit 0
"""


class Run:
    def __init__(
        self,
        proc: subprocess.CompletedProcess,
        calls: list[list[str]],
        env_vars_file: str | None = None,
    ):
        self.proc, self.calls = proc, calls
        # Contents of whatever was passed to --env-vars-file, captured before the script's
        # EXIT trap removed it. None when no such flag was passed.
        self.env_vars_file = env_vars_file

    @property
    def rc(self) -> int:
        return self.proc.returncode

    @property
    def err(self) -> str:
        return self.proc.stderr

    def _match(self, *head: str) -> list[list[str]]:
        return [c for c in self.calls if tuple(c[: len(head)]) == head]

    def deploy(self) -> list[str]:
        found = self._match("run", "deploy")
        assert len(found) == 1, f"expected exactly one `run deploy`, got {len(found)}"
        return found[0]

    def traffic_calls(self) -> list[list[str]]:
        return self._match("run", "services", "update-traffic")

    def flag(self, argv: list[str], name: str) -> str | None:
        """Value of `--name value` or `--name=value`, or None when absent."""
        for i, a in enumerate(argv):
            if a == name:
                return argv[i + 1] if i + 1 < len(argv) else ""
            if a.startswith(name + "="):
                return a.split("=", 1)[1]
        return None


def _run(
    tmp_path: Path,
    env_arg: str = "prod",
    tag: str = SHA,
    *,
    config: str | None = None,
    service_exists: bool = True,
    job_execute_rc: int = 0,
    job_create_rc: int = 0,
    deploy_rc: int = 0,
    log_output: str = "",
    ported_files: bool = False,
    curl_out: str = "404",
) -> Run:
    """Run the REAL deploy_gateway.sh against stubs.

    The script is copied so `$HERE` — the only path it derives from its own location — points at a
    scratch directory. That is what lets the ported-file tests control whether those two files
    exist without writing into the repo's own infra/gcp.
    """
    here = tmp_path / "infra_gcp"
    here.mkdir()
    script = here / "deploy_gateway.sh"
    shutil.copy2(SCRIPT, script)
    if ported_files:
        (here / f"env.{env_arg}.gateway.yaml").write_text('SOME_PORTED_KEY: "ported-value"\n')
        (here / f"secrets.{env_arg}.gateway.list").write_text("SOME_SECRET=SOME_SECRET:latest\n")

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    (bin_dir / "gcloud").write_text(GCLOUD_STUB)
    (bin_dir / "curl").write_text('#!/bin/sh\nprintf %s "$STUB_CURL_OUT"\nexit 0\n')
    (bin_dir / "sleep").write_text("#!/bin/sh\nexit 0\n")
    for f in bin_dir.iterdir():
        f.chmod(0o755)

    calls_file = tmp_path / "calls.log"
    calls_file.touch()

    env = {
        **os.environ,
        "PATH": f"{bin_dir}:{os.environ['PATH']}",
        "GCLOUD": str(bin_dir / "gcloud"),
        "STUB_CALLS": str(calls_file),
        "STUB_TRAFFIC_JSON": TRAFFIC_JSON,
        "STUB_CAND_URL": f"https://{CANDIDATE_TAG}---gateway-abc.a.run.app",
        "STUB_SERVICE_URL": "https://gateway-abc.a.run.app",
        "STUB_SERVICE_EXISTS_RC": "0" if service_exists else "1",
        "STUB_JOB_EXECUTE_RC": str(job_execute_rc),
        "STUB_JOB_CREATE_RC": str(job_create_rc),
        "STUB_DEPLOY_RC": str(deploy_rc),
        "STUB_LOG_OUTPUT": log_output,
        "STUB_CURL_OUT": curl_out,
        "STUB_ENV_FILE_COPY": str(tmp_path / "env-vars-file.snapshot"),
    }
    env.pop("CONFIG", None)
    if config is not None:
        env["CONFIG"] = config

    proc = subprocess.run(
        ["bash", str(script), env_arg, tag],
        capture_output=True, text=True, timeout=120, env=env, cwd=str(tmp_path),
    )
    calls = [line.split("\t") for line in calls_file.read_text().splitlines() if line]
    snapshot = tmp_path / "env-vars-file.snapshot"
    return Run(proc, calls, snapshot.read_text() if snapshot.exists() else None)


# --------------------------------------------------------------------- the regression

def test_a_prod_deploy_needs_no_railway_ported_files(tmp_path):
    """THE REGRESSION, and the reason the gateway was being deployed by hand.

    No env.prod.gateway.yaml, no secrets.prod.gateway.list — the state of every checkout since
    Railway was decommissioned. Before this change the script exited 1 here, always.
    """
    r = _run(tmp_path, "prod", ported_files=False)
    assert r.rc == 0, f"prod deploy failed without the ported files:\n{r.err}"
    assert "port_railway_env" not in r.err


def test_shipping_code_does_not_rewrite_the_live_services_env_or_secrets(tmp_path):
    """The config rollback this change exists to make impossible.

    `--env-vars-file` and `--set-secrets` REPLACE the whole set. On the live prod gateway that is
    382 environment variables, re-derived from the retired platform, riding along with a code
    deploy — and reported as success.
    """
    argv = _run(tmp_path, "prod").deploy()
    assert "--env-vars-file" not in argv
    assert "--set-secrets" not in argv
    assert not any(a.startswith("--set-env-vars") for a in argv)


def test_the_only_env_var_a_prod_deploy_moves_is_the_commit_stamp(tmp_path):
    r = _run(tmp_path, "prod")
    assert r.flag(r.deploy(), "--update-env-vars") == f"PIVOTA_COMMIT_SHA={SHA}"


# ------------------------------------------------- the stamp cannot diverge from the image

@pytest.mark.parametrize("config,ported", [("preserve", False), ("apply", True)])
def test_the_image_and_the_stamp_name_the_same_commit(tmp_path, config, ported):
    """Both are `$TAG`. Pinned in BOTH modes, because a divergence in either is the same lie.

    Under `apply` the stamp travels in the merged env file rather than on the command line, so the
    file is read back and the two values compared.
    """
    r = _run(tmp_path, "prod", config=config, ported_files=ported)
    assert r.rc == 0, r.err
    argv = r.deploy()
    image = r.flag(argv, "--image")
    assert image is not None and image.endswith(f":{SHA}"), image

    if config == "preserve":
        stamped = r.flag(argv, "--update-env-vars").split("=", 1)[1]
    else:
        merged = r.env_vars_file
        assert merged is not None, "apply mode sent no --env-vars-file"
        stamped = [
            line.split(":", 1)[1].strip().strip('"')
            for line in merged.splitlines()
            if line.startswith("PIVOTA_COMMIT_SHA:")
        ][-1]
    assert stamped == image.rsplit(":", 1)[1]


def test_the_stamp_is_written_on_every_deploy_so_it_can_never_be_inherited(tmp_path):
    """The actual mechanism of the observed 7-commit under-report.

    Nobody set the image and the stamp to different values. A hand `gcloud run deploy --image X`
    passed no env flag at all, so Cloud Run carried the PREVIOUS revision's PIVOTA_COMMIT_SHA onto
    the new image. An absent flag is the failure, so absence is what this asserts against.
    """
    r = _run(tmp_path, "prod", tag=OTHER_SHA)
    argv = r.deploy()
    assert r.flag(argv, "--update-env-vars") == f"PIVOTA_COMMIT_SHA={OTHER_SHA}"


@pytest.mark.parametrize("environment", ["prod", "staging"])
def test_a_floating_tag_is_refused(tmp_path, environment):
    """`latest` is pushed beside `:$COMMIT_SHA` by cloudbuild.gateway.yaml, so it is always there
    to be typed — and it would stamp /health with a string that names no commit.

    STAGING IS THE ROW THAT MATTERS, and it was missing at first: prod also happens to refuse
    `latest` through the 40-character-sha rule below, so a prod-only test stays green with the
    floating-tag check deleted outright. Staging only WARNS about a non-sha tag, so it is the one
    environment where this check is the sole thing standing between an operator and a revision
    whose stamped commit is the word "latest". Asserting the reason, not just the exit code, for
    the same reason.
    """
    r = _run(tmp_path, environment, tag="latest")
    assert r.rc == 2
    assert "floating tag" in r.err, r.err
    assert not r.calls, "nothing should have been deployed"


@pytest.mark.parametrize("bad", ["17e7cfa8", "17E7CFA8B91C4D2E6F0A3B5D8C7E9F1A2B3C4D5E", "v1.2.3"])
def test_prod_refuses_a_tag_that_is_not_a_full_lowercase_sha(tmp_path, bad):
    r = _run(tmp_path, "prod", tag=bad)
    assert r.rc == 2, f"'{bad}' was accepted for prod"
    assert not r.calls


def test_staging_warns_about_a_non_sha_tag_but_still_deploys(tmp_path):
    r = _run(tmp_path, "staging", tag="local-build-1")
    assert r.rc == 0, r.err
    assert "not a 40-character sha" in r.err


# ------------------------------------------------------------------ apply stays opt-in

def test_apply_must_be_asked_for_by_name_and_still_requires_the_ported_files(tmp_path):
    r = _run(tmp_path, "prod", config="apply", ported_files=False)
    assert r.rc == 1
    assert "port_railway_env" in r.err
    assert not any(c[:2] == ["run", "deploy"] for c in r.calls)


def test_apply_rewrites_env_and_secrets_when_the_files_are_there(tmp_path):
    """`apply` must keep working — it is the only path that can configure a service from scratch."""
    r = _run(tmp_path, "prod", config="apply", ported_files=True)
    assert r.rc == 0, r.err
    argv = r.deploy()
    assert "--env-vars-file" in argv and "--set-secrets" in argv
    assert "--update-env-vars" not in argv
    secrets = r.flag(argv, "--set-secrets")
    # The DSNs port_railway_env.py's DROP_EXACT strips must still be re-mounted here.
    for name in ("DATABASE_URL=", "PCI_KB_DATABASE_URL=", "INGREDIENT_REFERENCE_DATABASE_URL="):
        assert name in secrets, f"{name} not re-mounted under CONFIG=apply"
    assert "SOME_SECRET=SOME_SECRET:latest" in secrets


def test_an_unknown_config_value_is_refused_rather_than_treated_as_preserve(tmp_path):
    r = _run(tmp_path, "prod", config="Preserve")
    assert r.rc == 2
    assert not r.calls


def test_preserve_is_refused_on_a_service_that_does_not_exist_yet(tmp_path):
    """A first revision takes traffic IMMEDIATELY — no --no-traffic, no candidate tag, no health
    gate. Creating one from a single environment variable would put an unbootable service straight
    in front of users, so this is the one case `preserve` must not attempt."""
    r = _run(tmp_path, "prod", service_exists=False)
    assert r.rc == 2
    assert "CONFIG=apply" in r.err
    assert not any(c[:2] == ["run", "deploy"] for c in r.calls)


# -------------------------------------------------- the gates the hand deploy skipped

def test_the_candidate_takes_no_traffic_until_it_has_been_verified(tmp_path):
    argv = _run(tmp_path, "prod").deploy()
    assert "--no-traffic" in argv
    assert argv[argv.index("--tag") + 1] == CANDIDATE_TAG


def test_traffic_never_shifts_when_the_in_vpc_probe_fails(tmp_path):
    """Prod ingress is internal-and-cloud-load-balancing, so the direct curl always 404s and the
    in-VPC job is the probe that actually decides. Its exit code is the verdict."""
    # The log line says 200 and the job says otherwise. The verdict is the EXIT CODE: a scrape of
    # Cloud Logging must never be able to talk the gate INTO a promotion the probe refused.
    r = _run(tmp_path, "prod", job_execute_rc=1, log_output="PROBE_STATUS=200\n")
    assert r.rc == 1
    assert r.traffic_calls() == [], "promoted a candidate that failed its health check"


def test_traffic_never_shifts_when_the_probe_job_could_not_even_be_created(tmp_path):
    """`set -e` does not fire inside probe_health, so an unchecked create was entirely silent and
    "the job exited 0" rested on a job that never existed. A stale 200 in the logs must not rescue
    it either."""
    r = _run(tmp_path, "prod", job_create_rc=1, log_output="PROBE_STATUS=200\n")
    assert r.rc == 1
    assert r.traffic_calls() == []


def test_a_healthy_candidate_is_promoted_even_when_cloud_logging_has_not_caught_up(tmp_path):
    """The 2026-08-25 shape, ported here from deploy_backend.sh: the probe exits 0 but its log line
    is not queryable yet. Reading the verdict back out of Cloud Logging stranded a healthy backend
    revision at 0%; the gateway's copy of the gate had the same unbounded-ingestion-lag guess."""
    r = _run(tmp_path, "prod", job_execute_rc=0, log_output="")
    assert r.rc == 0, r.err
    assert any("--to-latest" in c for c in r.traffic_calls())


def test_stale_candidate_tags_are_swept_after_promotion(tmp_path):
    """The gate hand deploys skipped. A tagged revision is never garbage-collected and min-instances
    is 2, so each old candidate keeps instances running forever against the secret VERSIONS that
    were latest when they booted."""
    r = _run(tmp_path, "prod")
    removals = [c for c in r.traffic_calls() if any(a.startswith("--remove-tags") for a in c)]
    assert len(removals) == 1, f"expected one sweep, got {removals}"
    argv = removals[0]
    assert r.flag(argv, "--remove-tags") == "c-oldoldoldold"
    # The LIVE revision's tag serves 100% and must survive.
    assert CANDIDATE_TAG not in r.flag(argv, "--remove-tags")


def test_the_sweep_runs_on_a_preserve_deploy_too(tmp_path):
    """The whole point: the flow that was being bypassed must be reachable by the DEFAULT path."""
    r = _run(tmp_path, "prod", config=None)
    assert r.rc == 0, r.err
    assert any(any(a.startswith("--remove-tags") for a in c) for c in r.traffic_calls())


def test_a_failed_deploy_never_reaches_the_traffic_shift(tmp_path):
    r = _run(tmp_path, "prod", deploy_rc=1)
    assert r.rc != 0
    assert r.traffic_calls() == []
