"""The drift alarm's remediation text is read at the worst possible moment.

WHY THIS EXISTS. `prod-deploy-drift.yml` fires when production is behind main and
prints the commands to fix it. Nothing asserted those commands still work, so they
rotted: the worker remediation said

    WORKERS=true PAUSED=0 infra/gcp/setup_scheduler.sh prod <sha> <gateway-sha>

which is pre-#1903 phrasing (WORKERS only has effect under CONFIG=apply, and PAUSED
now applies only to triggers a run CREATES), alongside a build step whose companion
`deploy_backend.sh` invocation defaults to CONFIG=apply — which needs env.prod.yaml /
secrets.prod.list, generated by port_railway_env.py from `railway variables`, from a
platform decommissioned 2026-08-22. An operator following it at 3am gets exit 1.

A comment cannot hold this. The whole failure mode is text drifting away from the
tooling it describes while everything stays green, so the assertion has to live in
the suite that runs on every change.

Scope is the WORKER step only. The web step carries its own stale phrasing; that is
pivota-backend#1915's subject and giving it a second owner here would just make two
PRs conflict over one file.
"""
from __future__ import annotations

from pathlib import Path

import pytest
import yaml

WORKFLOW = Path(__file__).resolve().parents[1] / ".github/workflows/prod-deploy-drift.yml"


def _roll_command() -> str:
    """The gcloud invocation the remediation prints, continuations joined.

    Read as a COMMAND, not as a substring of the step. The first version of the
    positive test below asserted `"--update-env-vars" in run`, which the prose
    explaining why that flag matters satisfies on its own — so swapping the real
    invocation to the REPLACING `--set-env-vars` (which would drop the other 241
    variables) left the test green. A mutant caught it.
    """
    lines = _worker_step_run().splitlines()
    start = next(
        (i for i, ln in enumerate(lines) if ln.strip().startswith("gcloud run services update")),
        None,
    )
    assert start is not None, "the remediation prints no `gcloud run services update`"
    out = [lines[start].strip()]
    while out[-1].endswith("\\"):
        start += 1
        out.append(lines[start].strip())
    return " ".join(ln.rstrip("\\").strip() for ln in out)


def _worker_step_run() -> str:
    spec = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    steps = spec["jobs"]["drift"]["steps"]
    matches = [
        s for s in steps
        if "worker" in str(s.get("name", "")).lower() and isinstance(s.get("run"), str)
    ]
    assert len(matches) == 1, (
        f"expected exactly one worker step with a run block, found {len(matches)}"
    )
    return matches[0]["run"]


def test_the_worker_step_exists_at_all():
    """The blind spot #2010 closed: `web` was checked, `worker` was checked by
    nothing while running every cron in the repo."""
    run = _worker_step_run()
    assert "gcloud run services describe worker" in run


@pytest.mark.parametrize(
    "dead, why",
    [
        (
            "setup_scheduler.sh",
            "WORKERS only has effect under CONFIG=apply, and PAUSED no longer "
            "means what this invocation assumes (#1903)",
        ),
        (
            "deploy_backend.sh",
            "defaults to CONFIG=apply, which needs Railway-generated env files "
            "that cannot be regenerated; and SERVICE=worker also demands an "
            "ENV_PREFIX no worker env file provides",
        ),
        (
            "WORKERS=true",
            "inert unless CONFIG=apply, which is unusable since the Railway "
            "decommission",
        ),
    ],
)
def test_the_worker_remediation_invokes_no_command_that_exits_1(dead, why):
    """Each of these was printed to an operator as the fix. Each fails as printed.

    Asserted per LINE, on what a line INVOKES, rather than on the substring
    appearing anywhere in the step. The corrected text deliberately names these
    commands to say "not this one, and here is why" — guidance worth keeping, and
    a bare substring check would forbid it and push the explanation out of the one
    place an operator is already looking.
    """
    run = _worker_step_run()
    offenders = [
        ln for ln in run.splitlines()
        # A line that RUNS it: the command opens the line (after indentation),
        # or follows a `&&`/`;`/pipe. Prose that mentions it does not.
        if ln.strip().startswith(dead) or f"&& {dead}" in ln or f"; {dead}" in ln
    ]
    assert not offenders, (
        f"the worker remediation still tells an operator to run {dead!r}, which "
        f"does not work ({why}):\n" + "\n".join(f"  {o.strip()}" for o in offenders)
    )


def test_the_worker_remediation_names_the_command_that_does_work():
    """`gcloud run services update --image` with `--update-env-vars`. Verified
    2026-09-05 rolling the worker 94 commits forward: 242 env vars in, 242 out,
    none lost.

    `--update-env-vars` specifically, because it MERGES. The flags that replace
    would drop the other 241 variables the service carries, which is a documented
    way this project has broken production before.
    """
    cmd = _roll_command()
    assert cmd.startswith("gcloud run services update worker")
    assert "--image" in cmd
    assert "--update-env-vars" in cmd, (
        f"the remediation must use a MERGING env flag; this invokes: {cmd}"
    )
    # The replacing forms would drop the other 241 variables the worker carries.
    for replacing in ("--set-env-vars", "--clear-env-vars"):
        assert replacing not in cmd, (
            f"{replacing} REPLACES the service's environment; the worker carries "
            f"241 other variables and a deploy that wiped five of them is why "
            f"this is pinned. invocation: {cmd}"
        )
