"""`setup_scheduler.sh` must be safe to re-run against live production.

It was not, and the consequence was concrete: the three DB crons migrated in
#1892/#1894/#1895 could not be provisioned with it and were created by hand.

Three separate things made every invocation unusable, and each one is pinned below:

1. It hard-exited before touching anything, because it required `env.<env>.yaml`
   and `secrets.<env>.list` — both generated by `port_railway_env.py` from
   `railway variables --json`. Railway was decommissioned 2026-08-22, so on a
   fresh checkout those files cannot be regenerated and the exit was the outcome
   of EVERY run.
2. `sched()` applied the global `$PAUSED` to EVERY trigger on EVERY run. The
   default (1) paused relgraph-sync-cron, the per-minute
   reviews-invitation-send-cron and the commerce-index lanes; `PAUSED=0` had the
   opposite blast radius and was refused outright whenever Store Audit was armed
   — which in prod it always is.
3. Feature-flag `else` branches turned a merely-unset flag into an active
   `scheduler jobs pause`, so a run that never mentioned Store Audit still
   disarmed its four live triggers.

These tests drive the REAL script through the `GCLOUD` injection point it already
supports, against a fake that records every invocation. They assert on the
commands the script would actually issue — not on its source text, which is the
mistake that would let a rewrite pass while re-breaking the behaviour.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import textwrap
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "infra" / "gcp" / "setup_scheduler.sh"

# Everything that exists in prod today. `describe` succeeding is how the script decides
# create-vs-update and, previously, nothing else.
#
# ONE ENTRY IS AHEAD OF PROD: `relgraph-health-cron` is defined by the script but not yet
# provisioned. It is listed here because these tests are about RERUN SAFETY — that ARM and DISARM
# stay surgical once a trigger exists — and a permanently-absent entry would make every run of the
# script look like it touches an extra trigger, which is the assertion below, not a real finding.
# Verified: without this entry, test_arm_changes_exactly_one_trigger and its disarm partner FAIL.
# Adding it does not blunt them — a foreign trigger added to the script still fails both.
#
# (An earlier version of this note said new triggers are "created by hand". That contradicts
# `sched()`, which creates them PAUSED precisely so running this script is safe; the hand step is
# `ARM=relgraph-health-cron`, and only after a gateway image carrying PIVOTA-Agent #2171's script is
# rolled onto the job — an older image fails with npm's `Missing script`.)
# REMOVE THIS NOTE once it is live.
#
# `retailer-ingest-drain-cron` is AHEAD OF PROD on the same terms: it ships with the retailer
# ingest pipeline's infra and does not exist until someone runs this script. Without it every run
# here also creates-and-pauses it, which the ARM/DISARM surgery tests would read as a foreign
# trigger. The drain tests at the bottom that need the CREATE path pass their own empty
# EXISTING_TRIGGERS_FILE. REMOVE THIS NOTE once it is live.
EXISTING_TRIGGERS = {
    "relgraph-health-cron",
    "retailer-ingest-drain-cron",
    "relgraph-sync-cron", "reviews-invitation-send-cron",
    "commerce-index-relgraph-cron", "commerce-index-search-index-cron",
    "commerce-index-checkout-validation-cron", "commerce-index-insight-refresh-cron",
    "store-audit-ucp-probe-cron", "store-audit-ucp-reprobe-enqueue-cron",
    "store-audit-commerce-probe-cron", "store-audit-commerce-reprobe-enqueue-cron",
    "external-seed-sentinel-nongrowth-cron", "pdp-identity-graph-backfill-cron",
    "content-canonical-election-cron", "agent-pdp-orphan-reaper-cron",
    "derive-offer-market-currency-cron", "audit-domainless-offer-currency-cron",
}

# The Store Audit preflight reads real JSON out of `run services describe web` and
# `run revisions describe`, so the fake has to answer those in shape or the script exits 2
# before reaching a single scheduler call.
WEB_JSON = (
    '{"status":{"url":"https://web-gpx4jyrubq-uw.a.run.app",'
    '"traffic":[{"revisionName":"web-00088-kaz","percent":100}]}}'
)
REVISION_JSON = (
    # A revision declares the commit it was built from; deploy_worker.sh refuses one that does
    # not (it could not restamp a rollback truthfully), so the fake must carry it.
    '{"spec":{"containers":[{"image":"us-west1-docker.pkg.dev/pivota-shared/pivota/backend@sha256:'
    + "e" * 64 + '","env":['
    '{"name":"PIVOTA_COMMIT_SHA","value":"' + "e" * 40 + '"},'
    '{"name":"STORE_AUDIT_UCP_PROBE_RECEIPT_ENABLED","value":"true"},'
    '{"name":"STORE_AUDIT_UCP_PROBE_INTERNAL_KEY","valueFrom":{"secretKeyRef":'
    '{"name":"STORE_AUDIT_UCP_PROBE_INTERNAL_KEY"}}},'
    '{"name":"STORE_AUDIT_COMMERCE_PROBE_RECEIPT_ENABLED","value":"true"},'
    '{"name":"STORE_AUDIT_COMMERCE_PROBE_INTERNAL_KEY","valueFrom":{"secretKeyRef":'
    '{"name":"STORE_AUDIT_COMMERCE_PROBE_INTERNAL_KEY"}}}'
    ']}]}}'
)

FAKE_GCLOUD = textwrap.dedent(
    """\
    #!/usr/bin/env bash
    # Records argv, then answers the few reads the script makes.
    printf '%s\\n' "$*" >> "$GCLOUD_LOG"
    case "$1 $2 $3" in
      "scheduler jobs describe")
        grep -qx "$4" "$EXISTING_TRIGGERS_FILE" && exit 0 || exit 1 ;;
      "run jobs describe") exit 1 ;;            # jobs: always "create" — irrelevant to these tests
      "iam service-accounts") exit 0 ;;
      "run revisions describe") printf '%s' "$REVISION_JSON"; exit 0 ;;
      "run services describe")
        case "$*" in *--format=json*) printf '%s' "$WEB_JSON" ;; *) echo "https://worker.example" ;; esac
        exit 0 ;;
    esac
    exit 0
    """
)

def _run(tmp_path: Path, env_overrides: dict[str, str | None]) -> list[str]:
    """Run the real script against a fake gcloud; return the recorded invocations."""
    return _run_full(tmp_path, env_overrides)[0]


def _run_full(tmp_path: Path, env_overrides: dict[str, str | None],
              *, expect_rc: int = 0) -> tuple[list[str], subprocess.CompletedProcess]:
    """Run the real script against a fake gcloud; return (recorded invocations, process).

    A value of None DELETES the key from the child environment. That distinction is
    load-bearing: the script separates "operator said false" from "operator said nothing"
    with `${F+set}`, which is empty only when F is genuinely absent — so a test that sets
    F="" is still testing the explicit branch.
    """
    fake = tmp_path / "fake-gcloud"
    fake.write_text(FAKE_GCLOUD)
    fake.chmod(0o755)
    log = tmp_path / "calls.log"
    log.touch()
    existing = tmp_path / "existing.txt"
    existing.write_text("\n".join(sorted(EXISTING_TRIGGERS)) + "\n")

    env = {
        **os.environ,
        "GCLOUD": str(fake),
        "GCLOUD_LOG": str(log),
        "EXISTING_TRIGGERS_FILE": str(existing),
        "WEB_JSON": WEB_JSON,
        "REVISION_JSON": REVISION_JSON,
        # Prod's real posture: both Store Audit workers armed. This is the combination that
        # made PAUSED=0 refused, so it is the one worth testing against.
        "STORE_AUDIT_UCP_REPROBE_WORKER": "true",
        "STORE_AUDIT_UCP_REPROBE_ARMED": "true",
        "STORE_AUDIT_UCP_PROBE_BACKEND_BASE_URL": "https://web-gpx4jyrubq-uw.a.run.app",
        "STORE_AUDIT_COMMERCE_REPROBE_WORKER": "true",
        "STORE_AUDIT_COMMERCE_REPROBE_ARMED": "true",
        "STORE_AUDIT_COMMERCE_PROBE_BACKEND_BASE_URL": "https://web-gpx4jyrubq-uw.a.run.app",
        **{k: v for k, v in env_overrides.items() if v is not None},
    }
    for k, v in env_overrides.items():
        if v is None:
            env.pop(k, None)
    proc = subprocess.run(
        ["bash", str(SCRIPT), "prod", "a" * 40, "b" * 40],
        capture_output=True, text=True, env=env, cwd=str(REPO),
    )
    assert proc.returncode == expect_rc, (
        f"the script must run to completion against live-prod-shaped state.\n"
        f"rc={proc.returncode}\nstderr:\n{proc.stderr[-3000:]}"
    )
    return log.read_text().splitlines(), proc


def _state_changes(calls: list[str]) -> set[tuple[str, str]]:
    """(verb, trigger) for every pause/resume the script issued."""
    out = set()
    for c in calls:
        parts = c.split()
        if parts[:2] == ["scheduler", "jobs"] and len(parts) > 3 and parts[2] in ("pause", "resume"):
            out.add((parts[2], parts[3]))
    return out


def test_a_plain_rerun_changes_no_existing_trigger_state(tmp_path):
    """THE headline invariant. A reconcile run must not rewrite live state.

    Before the fix this issued a `pause` for every trigger in EXISTING_TRIGGERS —
    including the per-minute reviews-invitation-send-cron, which sends mail.
    """
    changes = _state_changes(_run(tmp_path, {}))
    touched_existing = {t for verb, t in changes if t in EXISTING_TRIGGERS}
    assert not touched_existing, (
        f"a plain re-run paused/resumed existing triggers: {sorted(touched_existing)}. "
        "Re-running must reconcile DEFINITIONS only."
    )


def test_it_does_not_require_the_retired_railway_files(tmp_path):
    """It must not exit 1 looking for files `port_railway_env.py` can no longer produce."""
    assert not (REPO / "infra" / "gcp" / "env.prod.yaml").exists(), (
        "this test is only meaningful while the ported file is absent"
    )
    _run(tmp_path, {})  # _run asserts rc == 0


def test_preserve_does_not_rewrite_worker_env(tmp_path):
    """CONFIG=preserve must roll the image forward without touching env/secrets wholesale."""
    calls = _run(tmp_path, {})
    deploys = [c for c in calls if c.startswith("run deploy worker")]
    assert len(deploys) == 1, f"expected exactly one worker deploy, got {len(deploys)}"
    assert "--env-vars-file" not in deploys[0], "preserve must not rewrite the whole env"
    assert "--set-secrets" not in deploys[0], "preserve must not rewrite secret mounts"
    assert "--update-env-vars" in deploys[0], "preserve must still restamp the commit"
    assert "AUDIT_WORKER_ENABLED" not in deploys[0], (
        "preserve must not decide the worker's armed state — that is WORKERS under CONFIG=apply"
    )


def test_arm_changes_exactly_one_trigger(tmp_path):
    changes = _state_changes(_run(tmp_path, {"ARM": "content-canonical-election-cron"}))
    assert ("resume", "content-canonical-election-cron") in changes
    others = {t for _, t in changes if t != "content-canonical-election-cron"}
    assert not others, f"ARM must be surgical; it also touched {sorted(others)}"


def test_disarm_changes_exactly_one_trigger(tmp_path):
    changes = _state_changes(_run(tmp_path, {"DISARM": "reviews-invitation-send-cron"}))
    assert ("pause", "reviews-invitation-send-cron") in changes
    others = {t for _, t in changes if t != "reviews-invitation-send-cron"}
    assert not others, f"DISARM must be surgical; it also touched {sorted(others)}"


def test_a_newly_created_trigger_is_still_inert_by_default(tmp_path):
    """Preserving EXISTING state must not make NEW triggers arm themselves.

    The cutover-safety property has to survive: a trigger this run creates comes up paused
    unless the operator says otherwise.
    """
    # Pretend nothing exists yet: every trigger is a create.
    #
    # STORE_AUDIT_*_ARMED is forced false here. Those two lanes pass an EXPLICIT per-trigger
    # paused argument (sched()'s 5th positional) rather than inheriting $PAUSED, so with
    # ARMED=true they legitimately come up resumed — which is the point of having a per-lane
    # arm switch, and would otherwise mask the default this test is about.
    empty = tmp_path / "none.txt"
    empty.write_text("")
    changes = _state_changes(_run(tmp_path, {
        "EXISTING_TRIGGERS_FILE": str(empty),
        "STORE_AUDIT_UCP_REPROBE_ARMED": "false",
        "STORE_AUDIT_COMMERCE_REPROBE_ARMED": "false",
    }))
    resumed = {t for verb, t in changes if verb == "resume"}
    paused = {t for verb, t in changes if verb == "pause"}
    assert not resumed, f"newly created triggers must default to paused, but resumed {sorted(resumed)}"
    assert paused, "a create run should still be pausing the triggers it creates"


def test_store_audit_stays_armed_when_the_flag_is_not_mentioned(tmp_path):
    """A run that never mentions Store Audit must not disarm its four live triggers.

    The `else` branches read a flag that DEFAULTS to false, so "said nothing" and
    "said false" were indistinguishable and the disarm fired on a plain run.
    """
    # UNSET, not empty. An earlier version of this test set these to "" and then filtered the
    # empties out, so the base env's STORE_AUDIT_*_WORKER="true" survived and the disarm branch
    # was never reached — it passed against the unguarded code. Mutant-checking caught it.
    changes = _state_changes(_run(tmp_path, {
        "STORE_AUDIT_UCP_REPROBE_WORKER": None,
        "STORE_AUDIT_UCP_REPROBE_ARMED": None,
        "STORE_AUDIT_UCP_PROBE_BACKEND_BASE_URL": None,
        "STORE_AUDIT_COMMERCE_REPROBE_WORKER": None,
        "STORE_AUDIT_COMMERCE_REPROBE_ARMED": None,
        "STORE_AUDIT_COMMERCE_PROBE_BACKEND_BASE_URL": None,
    }))
    store_audit = {t for _, t in changes if t.startswith("store-audit-")}
    assert not store_audit, (
        f"a run that never mentioned Store Audit disarmed {sorted(store_audit)}"
    )


def test_paused_zero_with_arm_is_refused_as_ambiguous(tmp_path):
    """The two mean different things now; passing both should not silently pick one."""
    fake = tmp_path / "fake-gcloud"
    fake.write_text(FAKE_GCLOUD)
    fake.chmod(0o755)
    log = tmp_path / "calls.log"; log.touch()
    existing = tmp_path / "existing.txt"; existing.write_text("\n".join(sorted(EXISTING_TRIGGERS)))
    proc = subprocess.run(
        ["bash", str(SCRIPT), "prod", "a" * 40, "b" * 40],
        capture_output=True, text=True, cwd=str(REPO),
        env={**os.environ, "GCLOUD": str(fake), "GCLOUD_LOG": str(log),
             "EXISTING_TRIGGERS_FILE": str(existing),
             "WEB_JSON": WEB_JSON, "REVISION_JSON": REVISION_JSON,
        "WEB_JSON": WEB_JSON,
        "REVISION_JSON": REVISION_JSON,
             "PAUSED": "0", "ARM": "relgraph-sync-cron"},
    )
    assert proc.returncode == 2, "PAUSED=0 together with ARM should be refused"


# ---- Store Audit preflight: which revision serves the untagged service URL? ----------------
#
# The predicate lives in setup_scheduler.sh as an embedded `python3 -c` heredoc. These tests
# EXTRACT AND EXECUTE that exact block rather than restating it, so they exercise the shipping
# code. A restated copy would keep passing while the script itself regressed — which is exactly
# what happened on the first draft of this file.
_ACTIVE_RE = re.compile(r"python3 -c '\n(import json,sys\no=json\.load\(sys\.stdin\)\n.*?)\n'\)\"", re.S)


def _preflight_blocks():
    """The ONE predicate both preflights now use, lifted out of the shared helper.

    This used to extract TWO inline copies from setup_scheduler.sh and assert they agreed —
    which was the right test for the code as it stood, and it is why the tagged-revision
    regression below was caught here in the first place. The copies are gone: both preflights
    call `serving_revision` from infra/gcp/_serving_revision.sh, so there is one predicate to
    run and nothing left to disagree.

    That consolidation was not cosmetic. A FIFTH copy of this rule lived in
    setup_store_audit_commerce_jobs.sh and still carried the `not x.get("tag")` conjunct these
    very tests exist to forbid — so that script exited 2 on every run against production. The
    guard was right, the tests were right, and the drift happened in the copy nobody was
    testing.
    """
    src = (REPO / "infra" / "gcp" / "_serving_revision.sh").read_text(encoding="utf-8")
    marker = "python3 -c '"
    i = src.index(marker, src.index("serving_revision()")) + len(marker)
    block = src[i:src.index("'", i)]
    assert "revisionName" in block and "percent" in block, (
        "could not lift the predicate out of _serving_revision.sh - fix this extractor, do "
        "NOT restate the predicate here, or these tests stop testing the shipped code."
    )
    return [block]


def _active_revision(traffic):
    """Run the shipped predicate over a traffic list. '' means it refused to answer."""
    payload = json.dumps({"status": {"traffic": traffic}})
    (block,) = _preflight_blocks()
    proc = subprocess.run(["python3", "-c", block], input=payload,
                          capture_output=True, text=True)
    # The helper signals "no single answer" with a non-zero exit and no output, where the
    # inline copies printed an empty string. Both mean the same thing to every caller.
    return proc.stdout.strip() if proc.returncode == 0 else ""


def test_a_tagged_serving_revision_is_still_the_serving_revision():
    """The state a normal deploy leaves behind must not be refused.

    deploy_backend.sh ships every candidate with `--tag c-<sha>` and then promotes it, so the
    revision at 100% keeps its own candidate tag until a later deploy retires it. The guard
    used to require `not t.get("tag")` and so refused exactly that — observed in prod
    2026-08-26, where web-00098-kax held 100% traffic AND tag c-6f8b201ba7dc, which made
    setup_scheduler.sh unrunnable whenever Store Audit was armed.
    """
    prod_shape = [
        {"revisionName": "web-00098-kax", "percent": 100, "tag": "c-6f8b201ba7dc"},
        {"revisionName": "web-00100-nox", "tag": "c-820e3cb51eec"},  # candidate, no percent
    ]
    assert _active_revision(prod_shape) == "web-00098-kax"


def test_an_untagged_serving_revision_still_resolves():
    assert _active_revision([{"revisionName": "web-1", "percent": 100}]) == "web-1"


def test_a_traffic_split_is_still_refused():
    """The property the guard exists for. Neither half is THE serving revision."""
    assert _active_revision([
        {"revisionName": "web-1", "percent": 50},
        {"revisionName": "web-2", "percent": 50},
    ]) == ""


def test_a_zero_traffic_candidate_alone_is_refused():
    """A candidate that was verified but never promoted must not be mistaken for serving."""
    assert _active_revision([{"revisionName": "web-2", "percent": 0, "tag": "c-abc"}]) == ""
    assert _active_revision([{"revisionName": "web-2", "tag": "c-abc"}]) == ""


def test_two_revisions_at_100_is_refused():
    """Nonsensical, but the `len(active) == 1` guard is what makes it unambiguous."""
    assert _active_revision([
        {"revisionName": "web-1", "percent": 100},
        {"revisionName": "web-2", "percent": 100},
    ]) == ""


def test_both_preflights_use_the_shared_predicate():
    """They were two copies of one rule and could drift apart; now they cannot, because there
    is one rule. Asserted on comment-stripped source so an explanatory comment cannot satisfy
    it — and the point is not that the string appears but that no inline copy remains."""
    body = "\n".join(
        l for l in (REPO / "infra" / "gcp" / "setup_scheduler.sh").read_text().splitlines()
        if not l.lstrip().startswith("#")
    )
    assert body.count("serving_revision web") == 2, (
        "both Store Audit preflights must resolve the serving revision through the shared "
        f"helper; found {body.count('serving_revision web')} call(s)"
    )
    assert 'percent") == 100' not in body and 'percent")==100' not in body, (
        "setup_scheduler.sh has grown its own copy of the predicate again"
    )


def _secrets_for(calls: list[str], job: str) -> str:
    for c in calls:
        if c.startswith(f"run jobs create {job} ") or c.startswith(f"run jobs update {job} "):
            parts = c.split()
            return parts[parts.index("--set-secrets") + 1]
    raise AssertionError(f"no create/update recorded for {job}")


def test_search_index_key_is_not_mounted_unless_the_lane_is_armed(tmp_path):
    """A secret that may not exist must not be mounted unconditionally.

    Cloud Run resolves secret refs at create/update time, so mounting a name that does not
    exist does NOT merely leave the lane inert — `gcloud run jobs update` fails, and under
    `set -e` that aborts the whole reconcile. Confirmed in prod 2026-08-26:
    CATALOG_SERVING_INDEX_API_KEY does not exist, the live job mounted it anyway, and the
    run died there before reaching the scheduler section.
    """
    secrets = _secrets_for(_run(tmp_path, {}), "commerce-index-search-index")
    assert "CATALOG_SERVING_INDEX_API_KEY" not in secrets, (
        "the API key must not be mounted while SEARCH_INDEX_PUBLICATION_WORKER is false"
    )
    # The DSNs it genuinely needs are still there — this is a narrowing, not a removal.
    assert "DATABASE_URL=DATABASE_URL_NOVERIFY:latest" in secrets
    assert "PCI_KB_DATABASE_URL=PCI_KB_DATABASE_URL_NOVERIFY:latest" in secrets


def test_search_index_key_IS_mounted_once_the_lane_is_armed(tmp_path):
    """Arming the lane is the point at which the secret is expected to exist."""
    secrets = _secrets_for(
        _run(tmp_path, {"SEARCH_INDEX_PUBLICATION_WORKER": "true"}),
        "commerce-index-search-index",
    )
    assert "CATALOG_SERVING_INDEX_API_KEY=CATALOG_SERVING_INDEX_API_KEY:latest" in secrets


def test_no_args_value_beginning_with_a_dash_uses_the_space_form():
    """`--args "-m,..."` is rejected by gcloud, and the plan-shim cannot catch it.

    gcloud's parser reads a value beginning with `-` as the next FLAG and fails with
    "argument --args: expected one argument". The `--args=` form binds it.

    Confirmed against prod 2026-08-26: the reconcile aborted at
    derive-offer-market-currency AFTER already updating ten jobs, so this is not a
    cosmetic preference — it makes those job definitions permanently un-updatable by the
    script, and it fails halfway through rather than up front.

    This is a SOURCE-TEXT assertion on purpose. The behavioural harness records what the
    script *would* invoke; it cannot reproduce gcloud's own argument parsing, so it is
    structurally blind to this class. A source check is the only thing that catches it
    before someone runs the script against production.
    """
    src = (REPO / "infra" / "gcp" / "setup_scheduler.sh").read_text(encoding="utf-8")
    # Join backslash continuations FIRST. Review found the evasion: splitting
    # `--args` from its value across two continued lines left the inspected line
    # ending in `\`, so the extracted "value" was a backslash and the guard
    # passed while gcloud still got the broken space form.
    joined, buf = [], ""
    for raw in src.splitlines():
        buf += raw[:-1] + " " if raw.rstrip().endswith("\\") else raw
        if not raw.rstrip().endswith("\\"):
            joined.append(buf); buf = ""
    if buf:
        joined.append(buf)
    offenders = []
    for i, line in enumerate(joined, 1):
        stripped = line.strip()
        if not stripped.startswith("--args ") and " --args " not in stripped:
            continue
        # the value gcloud would receive, after `--args `
        value = stripped.split("--args ", 1)[1].lstrip()
        if value[:1] in ("'", '"'):
            value = value[1:]
        if value.startswith("-") or value.startswith("$"):
            # `$VAR` is equally unsafe: the shell expands it before gcloud sees it, so a
            # variable holding "-m,..." fails exactly the same way.
            offenders.append(f"{i}: {stripped[:90]}")
    assert not offenders, (
        "these --args use the space-separated form with a value that begins with '-' "
        "(or a variable that may): gcloud will reject them. Use --args=<value>.\n  "
        + "\n  ".join(offenders)
    )


# ---- retailer-ingest-drain: the unattended retailer ingest Job ----------------------------
#
# Asserted on the gcloud line the script WOULD issue, not on its source: the overrides ride
# mkcrawljob's "$@" and only mean anything if they land AFTER its defaults, where gcloud takes the
# last occurrence. A source grep would pass with the override placed anywhere.
DRAIN = "retailer-ingest-drain"
DRAIN_TRIGGER = "retailer-ingest-drain-cron"
# The env the 2026-09-23 curated-ingest one-offs ran with. PIVOTA_SERVING_PRICING_REGIONS is US
# alone: the pipeline requires USD and the multi-region value carries a comma.
PROVEN_INGEST_ENV = {
    "ENABLE_INTAKE_IDENTITY_ENRICHMENT": "1",
    "ENABLE_INTAKE_IDENTITY_AUDIT": "1",
    "ENABLE_INTAKE_IDENTITY_BRAND_AUTHORED": "1",
    "ENABLE_INTAKE_IDENTITY_MIRROR": "1",
    "ENABLE_INTAKE_IDENTITY_SYNC": "1",
    "ENABLE_KBEAUTY_AGENT_DECISION_GATES": "true",
    "ENABLE_STORELESS_BRAND_CATALOG": "1",
    "INDEX_ELIGIBLE_READ": "1",
    "INDEX_ELIGIBLE_RECALL": "1",
    "INDEX_ELIGIBLE_SITEMAP": "1",
    "INDEXNOW_ENABLED": "true",
    "PDP_QUALITY_SCORE_SOURCE_BACKED_OPTIONAL_COMPONENTS": "1",
    "STRICT_BEAUTY_CATEGORY_TEXT_RECALL": "true",
    "PIVOTA_SERVING_PRICING_REGIONS": "US",
    "DB_STATEMENT_TIMEOUT_SECONDS": "30",
    "DB_COMMAND_TIMEOUT_SECONDS": "600",
    "CURATED_CRAWL_PAGE_ATTEMPTS": "5",
    "CRAWL_MIN_INTERVAL_SECONDS": "4",
    "CRAWL_BACKOFF_BASE_SECONDS": "15",
    "RETAILER_INGEST_LEASE_SECONDS": "4200",
    "PIVOTA_ENV": "production",
}


def _drain_call(calls: list[str]) -> list[str]:
    hits = [c for c in calls if c.startswith(f"run jobs create {DRAIN} ")
            or c.startswith(f"run jobs update {DRAIN} ")]
    assert len(hits) == 1, f"expected exactly one create/update of {DRAIN}, got {len(hits)}"
    return hits[0].split()


def _values(tokens: list[str], flag: str) -> list[str]:
    """Every value given for `flag`, in order, whether as `--flag v` or `--flag=v`."""
    out = []
    for i, t in enumerate(tokens):
        if t == flag and i + 1 < len(tokens):
            out.append(tokens[i + 1])
        elif t.startswith(flag + "="):
            out.append(t[len(flag) + 1:])
    return out


def _env(tokens: list[str]) -> dict[str, str]:
    (raw,) = _values(tokens, "--set-env-vars")  # ONE line: the reconcile replaces the whole set
    items = raw.split(",")
    env = {}
    for item in items:
        # gcloud splits on EVERY comma, so a comma inside a value leaves a fragment with no
        # `KEY=` of its own. That fragment is what this catches.
        assert re.fullmatch(r"[A-Z][A-Z0-9_]*=[^,]*", item), f"not a KEY=VALUE item: {item!r}"
        key, value = item.split("=", 1)
        assert key not in env, f"{key} set twice on one --set-env-vars line"
        env[key] = value
    return env


def _seconds(value: str) -> int:
    m = re.fullmatch(r"(\d+)s", value)
    assert m, f"unexpected duration {value!r}"
    return int(m.group(1))


def _gib(value: str) -> float:
    m = re.fullmatch(r"(\d+)(Gi|Mi)", value)
    assert m, f"unexpected memory {value!r}"
    return int(m.group(1)) / (1 if m.group(2) == "Gi" else 1024)


def test_the_drain_crawls_only_from_the_crawl_subnet(tmp_path):
    """The default subnet's NAT address is the payment IP; a retailer crawl must never use it."""
    tokens = _drain_call(_run(tmp_path, {}))
    assert _values(tokens, "--subnet") == ["pivota-crawl"], _values(tokens, "--subnet")
    assert _values(tokens, "--vpc-egress")[-1] == "all-traffic"


def test_the_drain_overrides_land_last(tmp_path):
    """gcloud takes the last occurrence, so the LAST value is the one the job gets."""
    tokens = _drain_call(_run(tmp_path, {}))
    assert _seconds(_values(tokens, "--task-timeout")[-1]) >= 3600, (
        "mkcrawljob's 300s default would kill a 20k-product crawl mid-stage"
    )
    assert _values(tokens, "--max-retries")[-1] == "0", (
        "the pipeline retries through its ledger; a Cloud Run retry re-crawls the store uncounted"
    )
    assert _gib(_values(tokens, "--memory")[-1]) >= 1
    assert _values(tokens, "--tasks")[-1] == "1"
    assert _values(tokens, "--parallelism")[-1] == "1"
    assert _values(tokens, "--command") == ["python"]
    assert _values(tokens, "--args") == ["-m,jobs.retailer_ingest_drain"]
    assert (REPO / "jobs" / "retailer_ingest_drain.py").is_file()


def test_the_drain_env_is_always_enabled_with_the_proven_env(tmp_path):
    """The TRIGGER is the arm/disarm switch; the env must not be one.

    It used to be a script input defaulting to 0, and because --set-env-vars replaces the whole env
    set, any run of this script for an unrelated job silently disarmed the drain. A leftover
    RETAILER_INGEST_DRAIN_ENABLED=0 in the operator's shell must not reach the job either."""
    for leftover in (None, "0"):
        run_dir = tmp_path / str(leftover)    # one call log per run
        run_dir.mkdir()
        calls = _run(run_dir, {"RETAILER_INGEST_DRAIN_ENABLED": leftover})
        tokens = _drain_call(calls)
        env = _env(tokens)
        assert env["RETAILER_INGEST_DRAIN_ENABLED"] == "1", leftover
        missing = {k: v for k, v in PROVEN_INGEST_ENV.items() if env.get(k) != v}
        assert not missing, f"env differs from the proven ingest env: {missing}"
        # The pipeline records the image it ran on (PIVOTA_COMMIT_SHA or IMAGE_SHA).
        assert env["PIVOTA_COMMIT_SHA"] == "a" * 40
        assert "--update-env-vars" not in tokens
        assert _values(tokens, "--set-secrets") == ["DATABASE_URL=DATABASE_URL:latest"]


def _drain_state_changes(calls: list[str]) -> set[tuple[str, str]]:
    return {c for c in _state_changes(calls) if c[1] == DRAIN_TRIGGER}


@pytest.mark.parametrize("paused_env", [None, "1", "0"])
def test_the_drain_trigger_is_every_30_minutes_utc_and_created_paused(tmp_path, paused_env):
    """Created paused even under PAUSED=0, which arms every OTHER trigger a run creates."""
    empty = tmp_path / "none.txt"
    empty.write_text("")
    calls = _run(tmp_path, {"EXISTING_TRIGGERS_FILE": str(empty), "PAUSED": paused_env,
                            # PAUSED=0 resumes the Store Audit lanes' creates too; irrelevant here.
                            "STORE_AUDIT_UCP_REPROBE_ARMED": "false",
                            "STORE_AUDIT_COMMERCE_REPROBE_ARMED": "false"})
    creates = [c for c in calls if c.startswith(f"scheduler jobs create http {DRAIN_TRIGGER} ")]
    assert len(creates) == 1, creates
    assert "--schedule=*/30 * * * * --time-zone=Etc/UTC" in creates[0]
    assert f"/jobs/{DRAIN}:run" in creates[0]
    assert _drain_state_changes(calls) == {("pause", DRAIN_TRIGGER)}


@pytest.mark.parametrize("overrides", [
    {},                                                    # a plain reconcile for another job
    {"PAUSED": "0"},                                       # arms NEW triggers only
    {"RETAILER_INGEST_DRAIN_ENABLED": "0"},                 # the retired input, left in a shell
    {"DISARM": "reviews-invitation-send-cron"},            # surgery on a different trigger
    {"ARM": "content-canonical-election-cron"},
], ids=["plain", "paused0", "legacy-flag", "disarm-other", "arm-other"])
def test_a_rerun_leaves_an_existing_drain_trigger_alone(tmp_path, overrides):
    """Whatever state the live trigger is in - paused or resumed by `gcloud scheduler jobs
    pause|resume` - a re-run issues neither pause nor resume for it, so that state stands. The
    `update` must still happen (the definition is reconciled), just never the state."""
    calls = _run(tmp_path, overrides)
    assert [c for c in calls if c.startswith(f"scheduler jobs update http {DRAIN_TRIGGER} ")]
    assert _drain_state_changes(calls) == set(), _drain_state_changes(calls)


@pytest.mark.parametrize("script", ["setup_scheduler.sh", "setup_monitoring.sh"])
def test_the_edited_scripts_parse(script):
    proc = subprocess.run(["bash", "-n", str(REPO / "infra" / "gcp" / script)],
                          capture_output=True, text=True)
    assert proc.returncode == 0, proc.stderr
