"""Elect ONE canonical ``pivota_signature_id`` per ``content_key``.

WHAT THIS FIXES. 474 content_keys in prod carry more than one sitemap-eligible,
renderable sig (551 redundant URLs; groups of 2, 3, 4, 5 and 7). Every sibling
serves HTTP 200 with the same title, the same Product JSON-LD, and a
SELF-referential ``<link rel="canonical">``. Two URLs, identical content, each
claiming to be canonical. pivota-agent-ui#280 stopped the SITEMAP emitting more
than one; it could not touch the pages, because the page has no way to know
which sibling the sitemap picked.

THE INVARIANT THIS MODULE EXISTS TO HOLD:

    the sig the sitemap advertises for a content_key
      ==
    the sig every sibling's PDP names in <link rel="canonical">

Break it and we have instructed the crawler to drop the URL we just submitted —
strictly worse than the duplicate. Holding it requires ONE source of truth, and
this table is it: the backend elects, the feed publishes ``canonical_sig_id``,
the gateway serves it in the ``canonical`` module, and both surfaces read
rather than compute.

WHY NOT LET THE SITEMAP KEEP DECIDING. Its rule (#280) is incumbency > sig
class > lexicographic, where incumbency means "already present in the committed
public/sitemap-products.xml". That is the RIGHT rule — a pure ordering would
have swapped 183 already-indexed URLs for brand-new ones when P3 made both
siblings renderable — but it is not a rule the gateway can evaluate. It lives
in a git-tracked artifact in another repo, regenerated by a cron, and a PDP
request cannot consult it. Incumbency is therefore imported ONCE (see
``scripts/elect_content_canonicals.py --seed-from-sitemap``) and from then on
stickiness is a stored fact rather than a property of a committed file.

That import is exact for the whole current population: all 474 duplicate groups
have EXACTLY ONE member in the live sitemap — zero have two, zero have none —
so there is no group where seeding has to guess.

THE STICKINESS RULE, stated once:

    A stored winner is re-elected ONLY when it is no longer a candidate.

Not when a "better" sig appears, not when sig classes differ, not when the
group grows. Re-electing on anything weaker re-opens exactly the URL churn #280
closed: a swapped canonical costs the old URL's accumulated index equity and
buys nothing, because the siblings are byte-identical content. The only thing
that justifies moving a URL is that the current one has stopped working.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from sqlalchemy import select

from db.catalog import catalog_products
from services.canonical_sitemap_candidates import (
    sitemap_candidate_join,
    sitemap_electable_filter,
    sitemap_widen_enabled,
)

# ``election_reason`` values — WHY this sig holds the URL. Stored verbatim so an
# operator can answer "why is THIS the URL?" without re-deriving anything.
# Re-election is deliberately NOT one of these: it is visible as
# ``elected_at <> updated_at``, which keeps the reason column answering one
# question instead of two.
REASON_SITEMAP_INCUMBENT = "sitemap_incumbent"
REASON_SOLE_CANDIDATE = "sole_candidate"
REASON_SIG_CLASS = "sig_class"
REASON_LEXICOGRAPHIC = "lexicographic"
# Returned by :func:`pick_winner` when a stored winner is retained. Never
# persisted — :func:`plan_elections` emits no write in that case.
REASON_STICKY = "sticky"


@dataclass(frozen=True)
class Election:
    content_key: str
    canonical_sig_id: str
    election_reason: str
    # The winner this replaces, if any. Every non-None value is a LIVE URL
    # moving, so the sweep reports them individually rather than as a count —
    # see scripts/elect_content_canonicals.py.
    replaced: Optional[str] = None


def _sig_hex_len(sig: str) -> int:
    """Length of the hex body, or -1 for anything not shaped like a sig.

    Byte-for-byte the same ordering key as pivota-agent-ui's
    ``preferSitemapId`` (scripts/sitemap_lib.mjs), deliberately: while the
    stored winner is authoritative, the FALLBACK both sides use when no winner
    is stored yet has to agree, or a freshly-minted content_key gets one answer
    from the sitemap and a different one from the gateway during the window
    before its first election.

    Worth recording that this layer is currently inert: of the 474 duplicate
    groups in prod, ZERO mix sig classes. It is kept because it costs nothing
    and because the sitemap has it.
    """
    return len(sig) - 4 if sig.startswith("sig_") else -1


def pick_winner(
    candidates: Sequence[str],
    *,
    stored: Optional[str] = None,
    incumbents: Optional[Iterable[str]] = None,
) -> Optional[Tuple[str, str]]:
    """Return ``(winning_sig, reason)`` for one content_key's candidate set.

    Layer order, highest first:

      0. STORED — the winner already elected, if it is still a candidate. This
         is the stickiness rule and it is unconditional: nothing outranks a
         working incumbent URL. Reported as ``REASON_STICKY`` so callers can
         tell "kept" from "chosen".
      1. SITEMAP INCUMBENT — used only while seeding, when ``incumbents`` is
         supplied from the live sitemap. Imports the index equity #280 was
         protecting.
      2. SIG CLASS — the longer sig (32-hex content sigs over legacy 24-hex).
      3. LEXICOGRAPHIC — a total order, so the answer is deterministic and does
         not depend on row order out of the database.

    Returns None when there are no candidates: the content_key has no
    advertisable URL at all, and the caller must leave any stored row ALONE
    rather than delete it. Deleting would drop the canonical tag from sibling
    pages that still serve, re-exposing the duplicate the moment the winner
    came back — and the renderability predicate behind the candidate set is
    deliberately conservative (under-advertise, never falsely drop), so "no
    candidates" is more often a transient read than a genuinely dead product.
    """
    pool = sorted({str(c).strip() for c in candidates if str(c or "").strip()})
    if not pool:
        return None

    if stored and stored in pool:
        return stored, REASON_STICKY

    if len(pool) == 1:
        return pool[0], REASON_SOLE_CANDIDATE

    if incumbents:
        present = [sig for sig in pool if sig in set(incumbents)]
        # Exactly one is the measured shape of every current duplicate group.
        # Two would mean the live sitemap is itself advertising a duplicate —
        # possible only against a sitemap generated before #280 — so fall
        # through to the deterministic layers rather than guess.
        if len(present) == 1:
            return present[0], REASON_SITEMAP_INCUMBENT

    widest = max(_sig_hex_len(sig) for sig in pool)
    top = [sig for sig in pool if _sig_hex_len(sig) == widest]
    if len(top) == 1:
        return top[0], REASON_SIG_CLASS
    return min(top), REASON_LEXICOGRAPHIC


def plan_elections(
    *,
    candidates_by_content_key: Dict[str, List[str]],
    stored_by_content_key: Dict[str, str],
    incumbents: Optional[Iterable[str]] = None,
) -> List[Election]:
    """Pure planner: candidate sets + current state -> the writes to make.

    Split out from the I/O so the decision logic is testable without a
    database — which matters more than usual here, because pivota-backend CI
    has been dark since the 2026-07-14 Actions billing outage and local suites
    are the only gate.

    Emits nothing for a content_key whose stored winner is still a candidate,
    so a steady-state sweep writes zero rows.
    """
    incumbent_set = set(incumbents or ())
    planned: List[Election] = []
    for content_key, candidates in candidates_by_content_key.items():
        stored = stored_by_content_key.get(content_key)
        chosen = pick_winner(
            candidates,
            stored=stored,
            incumbents=incumbent_set or None,
        )
        if chosen is None:
            # No advertisable URL right now. Leave any stored row untouched.
            continue
        winner, reason = chosen
        if reason == REASON_STICKY:
            continue
        planned.append(
            Election(
                content_key=content_key,
                canonical_sig_id=winner,
                election_reason=reason,
                replaced=stored,
            )
        )
    return planned


def candidates_query(*, widen: Optional[bool] = None):
    """SELECT (content_key, pivota_signature_id) for every advertisable row.

    Uses ``sitemap_electable_filter`` — the SAME eligibility + renderability
    the feed publishes — so the elector cannot crown a sig the feed will never
    emit. See services/canonical_sitemap_candidates for why that sharing is the
    load-bearing part.
    """
    effective_widen = sitemap_widen_enabled() if widen is None else widen
    return (
        select(
            catalog_products.c.content_key,
            catalog_products.c.pivota_signature_id,
        )
        .select_from(sitemap_candidate_join(widen=effective_widen))
        .where(
            sitemap_electable_filter(widen=effective_widen),
            # Rows with no minted sig pass the WIDENED identity term (they
            # qualify on content_key alone) but can never BE a URL, so they are
            # not candidates for holding one.
            catalog_products.c.pivota_signature_id.isnot(None),
        )
        .order_by(
            catalog_products.c.content_key.asc(),
            catalog_products.c.pivota_signature_id.asc(),
        )
    )


UPSERT_ELECTION_SQL = """
INSERT INTO content_canonical_election (
    content_key, canonical_sig_id, election_reason, elected_at, updated_at
) VALUES (
    :content_key, :canonical_sig_id, :election_reason, NOW(), NOW()
)
ON CONFLICT (content_key) DO UPDATE SET
    canonical_sig_id = EXCLUDED.canonical_sig_id,
    election_reason  = EXCLUDED.election_reason,
    -- elected_at is NOT touched: it records when this content_key FIRST got a
    -- canonical URL, so `elected_at = updated_at` stays a clean "never moved"
    -- signal and a re-election is visible as the two diverging.
    updated_at       = NOW()
WHERE content_canonical_election.canonical_sig_id
      IS DISTINCT FROM EXCLUDED.canonical_sig_id
"""
