"""Elect ONE canonical ``pivota_signature_id`` per ``content_key``.

WHAT THIS FIXES. 474 content_keys in prod carry more than one sitemap-eligible,
renderable sig (551 redundant URLs; groups of 2, 3, 4, 5 and 7). Every sibling
serves HTTP 200 with the same title, the same Product JSON-LD, and a
SELF-referential ``<link rel="canonical">``. Two URLs, identical content, each
claiming to be canonical. pivota-agent-ui#280 stopped the SITEMAP emitting more
than one; it could not touch the pages, because the page has no way to know
which sibling the sitemap picked.

THE INVARIANT THIS MODULE EXISTS TO HOLD:

    the sig the sitemap advertises for a content_key
      ==
    the sig every sibling's PDP names in <link rel="canonical">

Break it and we have instructed the crawler to drop the URL we just submitted —
strictly worse than the duplicate. Holding it requires ONE source of truth, and
this table is it: the backend elects, the feed publishes ``canonical_sig_id``,
the gateway serves it in the ``canonical`` module, and both surfaces read
rather than compute.

WHY NOT LET THE SITEMAP KEEP DECIDING. Its rule (#280) is incumbency > sig
class > lexicographic, where incumbency means "already present in the committed
public/sitemap-products.xml". That is the RIGHT rule — a pure ordering would
have swapped 183 already-indexed URLs for brand-new ones when P3 made both
siblings renderable — but it is not a rule the gateway can evaluate. It lives
in a git-tracked artifact in another repo, regenerated by a cron, and a PDP
request cannot consult it. Incumbency is therefore imported ONCE (see
``scripts/elect_content_canonicals.py --seed-from-sitemap``) and from then on
stickiness is a stored fact rather than a property of a committed file.

That import is exact for the whole current population: all 474 duplicate groups
have EXACTLY ONE member in the live sitemap — zero have two, zero have none —
so there is no group where seeding has to guess.

THE STICKINESS RULE, stated once:

    A stored winner is re-elected ONLY when it is no longer a candidate.

Not when a "better" sig appears, not when sig classes differ, not when the
group grows. Re-electing on anything weaker re-opens exactly the URL churn #280
closed: a swapped canonical costs the old URL's accumulated index equity and
buys nothing, because the siblings are byte-identical content. The only thing
that justifies moving a URL is that the current one has stopped working.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

from sqlalchemy import select

from db.catalog import catalog_products
from services.canonical_sitemap_candidates import (
    sitemap_candidate_join,
    sitemap_electable_filter,
    sitemap_widen_enabled,
)

# ``election_reason`` values — WHY this sig holds the URL. Stored verbatim so an
# operator can answer "why is THIS the URL?" without re-deriving anything.
# Re-election is deliberately NOT one of these: it is visible as
# ``elected_at <> updated_at``, which keeps the reason column answering one
# question instead of two.
REASON_DEDUPE_KEEPER = "dedupe_keeper"
REASON_SITEMAP_INCUMBENT = "sitemap_incumbent"
REASON_SOLE_CANDIDATE = "sole_candidate"
REASON_SIG_CLASS = "sig_class"
REASON_LEXICOGRAPHIC = "lexicographic"
# Returned by :func:`pick_winner` when a stored winner is retained. Never
# persisted — :func:`plan_elections` emits no write in that case.
REASON_STICKY = "sticky"


@dataclass(frozen=True)
class Election:
    content_key: str
    canonical_sig_id: str
    election_reason: str
    # The winner this replaces, if any. Every non-None value is a LIVE URL
    # moving, so the sweep reports them individually rather than as a count —
    # see scripts/elect_content_canonicals.py.
    replaced: Optional[str] = None


def _sig_hex_len(sig: str) -> int:
    """Length of the hex body, or -1 for anything not shaped like a sig.

    Byte-for-byte the same ordering key as pivota-agent-ui's
    ``preferSitemapId`` (scripts/sitemap_lib.mjs), deliberately: while the
    stored winner is authoritative, the FALLBACK both sides use when no winner
    is stored yet has to agree, or a freshly-minted content_key gets one answer
    from the sitemap and a different one from the gateway during the window
    before its first election.

    Worth recording that this layer is currently inert: of the 474 duplicate
    groups in prod, ZERO mix sig classes. It is kept because it costs nothing
    and because the sitemap has it.
    """
    return len(sig) - 4 if sig.startswith("sig_") else -1


def pick_winner(
    candidates: Sequence[str],
    *,
    stored: Optional[str] = None,
    incumbents: Optional[Iterable[str]] = None,
    keeper: Optional[str] = None,
) -> Optional[Tuple[str, str]]:
    """Return ``(winning_sig, reason)`` for one content_key's candidate set.

    Layer order, highest first:

      0. STORED — the winner already elected, if it is still a candidate. This
         is the stickiness rule and it is unconditional: nothing outranks a
         working incumbent URL. Reported as ``REASON_STICKY`` so callers can
         tell "kept" from "chosen".
      1. SITEMAP INCUMBENT — used only while seeding, when ``incumbents`` is
         supplied from the live sitemap. Imports the index equity #280 was
         protecting.
      2. SIG CLASS — the longer sig (32-hex content sigs over legacy 24-hex).
      3. LEXICOGRAPHIC — a total order, so the answer is deterministic and does
         not depend on row order out of the database.

    Returns None when there are no candidates: the content_key has no
    advertisable URL at all, and the caller must leave any stored row ALONE
    rather than delete it. Deleting would drop the canonical tag from sibling
    pages that still serve, re-exposing the duplicate the moment the winner
    came back — and the renderability predicate behind the candidate set is
    deliberately conservative (under-advertise, never falsely drop), so "no
    candidates" is more often a transient read than a genuinely dead product.
    """
    pool = sorted({str(c).strip() for c in candidates if str(c or "").strip()})
    if not pool:
        return None

    # LAYER -1 — the step-5 KEEPER, above even stickiness.
    #
    # Excluding tombstones (`not_tombstoned`) removes the tombstone from the
    # pool; it does NOT make the election prefer the KEEPER. With one survivor
    # those are the same thing, which is why it looked sufficient — 336 of the
    # 340 tombstone-bearing groups in prod have exactly one. With two survivors
    # they diverge, and measured, lexicographic picks a non-keeper in 6 of the
    # 11 such groups:
    #
    #   tombstone T -> keeper K   (#1833 canonicalises T at K)
    #   election    -> E != K     (lexicographic over {K, E})
    #   sitemap     -> E
    #
    # T points at K, K points at E, the sitemap advertises E. A two-hop
    # canonical CHAIN — not a contradiction (E is self-canonical, so nothing
    # points away from what we advertise) but Google discounts chains, and it is
    # avoidable for free.
    #
    # Ranked above `stored` deliberately, breaking the stickiness rule that
    # governs every other layer. The keeper is an explicit row-layer decision
    # (suppression_metadata.keeper_product_key, 2026-07-10); disagreeing with it
    # does not preserve equity, it splits equity across a chain. Where they
    # conflict, agreeing with #1833 is worth more than holding a URL still —
    # and a stored non-keeper winner is exactly the state that produces the
    # chain, so refusing to move it would make the defect permanent.
    if keeper and keeper in pool:
        return keeper, REASON_DEDUPE_KEEPER

    if stored and stored in pool:
        return stored, REASON_STICKY

    if len(pool) == 1:
        return pool[0], REASON_SOLE_CANDIDATE

    narrowed_by_incumbency = False
    if incumbents:
        present = [sig for sig in pool if sig in set(incumbents)]
        # NARROW the pool to the incumbents rather than requiring exactly one.
        #
        # Exactly one is the measured shape of every current duplicate group,
        # but two is reachable against a sitemap generated before #280 — and the
        # earlier "fall through rather than guess" reading was wrong twice over.
        # Falling through ordered the WHOLE pool including non-incumbents, so it
        # could crown a brand-new sig over two already-indexed ones; and there
        # was never a guess to avoid, because layers 2-3 are a total order and
        # decide among incumbents perfectly well.
        #
        # Narrowing also restores parity with preferSitemapId, which applies
        # incumbency PAIRWISE and therefore keeps ordering among the incumbents.
        # A differential run over 400 candidate/incumbent combinations found 60
        # mismatches, ALL in this >=2-incumbent class — e.g. candidates
        # {A,B,C} with incumbents {B,C}: the sitemap picks B, the old code here
        # picked A. Seed-time only (post-seed the stored value dominates both
        # sides), so it was index-equity loss rather than an invariant break —
        # but equity loss for no reason.
        if present:
            pool = present
            narrowed_by_incumbency = True

    widest = max(_sig_hex_len(sig) for sig in pool)
    top = [sig for sig in pool if _sig_hex_len(sig) == widest]
    winner = top[0] if len(top) == 1 else min(top)
    if narrowed_by_incumbency:
        # The incumbency layer is what confined the choice, even when a lower
        # layer broke the final tie — report the layer that actually decided
        # the outcome, or the audit column lies about why this URL was kept.
        return winner, REASON_SITEMAP_INCUMBENT
    return winner, REASON_SIG_CLASS if len(top) == 1 else REASON_LEXICOGRAPHIC


def plan_elections(
    *,
    candidates_by_content_key: Dict[str, List[str]],
    stored_by_content_key: Dict[str, str],
    incumbents: Optional[Iterable[str]] = None,
    keeper_by_content_key: Optional[Dict[str, str]] = None,
) -> List[Election]:
    """Pure planner: candidate sets + current state -> the writes to make.

    Split out from the I/O so the decision logic is testable without a
    database — which matters more than usual here, because pivota-backend CI
    has been dark since the 2026-07-14 Actions billing outage and local suites
    are the only gate.

    Emits nothing for a content_key whose stored winner is still a candidate,
    so a steady-state sweep writes zero rows.
    """
    incumbent_set = set(incumbents or ())
    keepers = keeper_by_content_key or {}
    planned: List[Election] = []
    for content_key, candidates in candidates_by_content_key.items():
        stored = stored_by_content_key.get(content_key)
        chosen = pick_winner(
            candidates,
            stored=stored,
            incumbents=incumbent_set or None,
            keeper=keepers.get(content_key),
        )
        if chosen is None:
            # No advertisable URL right now. Leave any stored row untouched.
            continue
        winner, reason = chosen
        if reason == REASON_STICKY:
            continue
        planned.append(
            Election(
                content_key=content_key,
                canonical_sig_id=winner,
                election_reason=reason,
                # ONLY when the winner actually CHANGES. This was an unconditional
                # `replaced=stored`, which made `replaced` truthy whenever a
                # content_key had any stored winner — including when the newly
                # chosen winner is that very same sig.
                #
                # It is not a cosmetic counter. `replacements` is what the
                # scheduled workflow alarms on ("N elected canonical URL(s) MOVED
                # — each is a live URL changing"), and what the rollout runbook
                # names as its convergence gate. MEASURED against prod right after
                # the 2026-07-26 seed: a steady-state sweep reported
                # `replacements: 587` with `written: 0` — all 587 had
                # `from == to`. So the alarm would have fired on EVERY 6h run
                # forever, and the runbook's `replacements: 0` gate could never
                # pass, on a corpus that is in fact perfectly converged.
                #
                # The 587 are the `dedupe_keeper` cohort specifically: that rung
                # sits ABOVE the sticky rung, so it re-elects outright and never
                # reaches the `REASON_STICKY` short-circuit above that would
                # otherwise have skipped an unchanged winner.
                #
                # `written` was already honest — UPSERT_ELECTION_SQL carries
                # `WHERE canonical_sig_id IS DISTINCT FROM EXCLUDED.canonical_sig_id`
                # — which is why the DB was right while the report was not. This
                # brings the report in line with the write.
                #
                # Note this is the SECOND time this field has misled an operator in
                # the opposite direction: on a SEED run the table is empty, so
                # `replacements` is structurally 0 no matter how many URLs move,
                # which is why `moved_from_sitemap` had to be added. `replaced`
                # answers "did the STORED value change", and it is only ever a
                # proxy for "did a live URL move" — read `moved_from_sitemap` for
                # the latter.
                replaced=stored if stored and stored != winner else None,
            )
        )
    return planned


def candidates_query(*, widen: Optional[bool] = None):
    """SELECT (content_key, pivota_signature_id) for every advertisable row.

    Uses ``sitemap_electable_filter`` — the SAME eligibility + renderability
    the feed publishes — so the elector cannot crown a sig the feed will never
    emit. See services/canonical_sitemap_candidates for why that sharing is the
    load-bearing part.
    """
    effective_widen = sitemap_widen_enabled() if widen is None else widen
    return (
        select(
            catalog_products.c.content_key,
            catalog_products.c.pivota_signature_id,
        )
        .select_from(sitemap_candidate_join(widen=effective_widen))
        .where(
            sitemap_electable_filter(widen=effective_widen),
            # Rows with no minted sig pass the WIDENED identity term (they
            # qualify on content_key alone) but can never BE a URL, so they are
            # not candidates for holding one.
            #
            # LIKE, not just IS NOT NULL: under INDEX_ELIGIBLE_SITEMAP the
            # identity term is satisfied by index_eligible alone, so a row whose
            # pivota_signature_id is set but NOT sig_-shaped would otherwise be
            # electable — and the stored value is what both readers hand to
            # agent-ui to build a URL out of. The readers now re-check the shape
            # too, but the right place to refuse is before it is stored.
            catalog_products.c.pivota_signature_id.like("sig\\_%", escape="\\"),
        )
        .order_by(
            catalog_products.c.content_key.asc(),
            catalog_products.c.pivota_signature_id.asc(),
        )
    )


# The step-5 keeper for every content_key that has one, as a SIG.
#
# Mirrors PIVOTA-Agent#1833's keeper LATERAL guard for guard — same join key
# (`suppression_metadata->>'keeper_product_key'`), same three conditions (same
# content_key, keeper not itself tombstoned, keeper has a sig). If the two ever
# disagree about who the keeper is, #1833 points the tombstone at one sig while
# this elects another, and the chain this exists to prevent comes back.
#
# DISTINCT because a group can hold several tombstones (up to 6 in prod) all
# naming the same keeper; ordering by sig makes a group whose tombstones somehow
# disagree resolve deterministically rather than by scan order.
KEEPER_SIGS_SQL = """
SELECT DISTINCT ON (loser.content_key)
       loser.content_key,
       keeper.pivota_signature_id AS keeper_sig_id
FROM catalog_products loser
JOIN catalog_products keeper
  ON keeper.product_key = loser.suppression_metadata->>'keeper_product_key'
 AND keeper.content_key = loser.content_key
 AND keeper.suppression_reason IS NULL
 AND keeper.pivota_signature_id IS NOT NULL
WHERE loser.suppression_reason IS NOT NULL
  AND loser.content_key IS NOT NULL
ORDER BY loser.content_key, keeper.pivota_signature_id
"""


_UPSERT_HEAD = """
INSERT INTO content_canonical_election (
    content_key, canonical_sig_id, election_reason, elected_at, updated_at
) VALUES """

# ONE copy of the conflict clause, shared by the single-row and multi-row forms
# below so they cannot drift. `elected_at` is NOT touched: it records when this
# content_key FIRST got a canonical URL, so `elected_at = updated_at` stays a
# clean "never moved" signal and a re-election is visible as the two diverging.
#
# The `IS DISTINCT FROM` guard is what makes `written` honest — a re-election that
# picks the SAME sig updates nothing at all.
_UPSERT_CONFLICT_TAIL = """
ON CONFLICT (content_key) DO UPDATE SET
    canonical_sig_id = EXCLUDED.canonical_sig_id,
    election_reason  = EXCLUDED.election_reason,
    updated_at       = NOW()
WHERE content_canonical_election.canonical_sig_id
      IS DISTINCT FROM EXCLUDED.canonical_sig_id
"""

UPSERT_ELECTION_SQL = (
    _UPSERT_HEAD
    + "(:content_key, :canonical_sig_id, :election_reason, NOW(), NOW())"
    + _UPSERT_CONFLICT_TAIL
)

# Postgres caps a statement at 65,535 bind parameters. At 3 per row that allows
# ~21,845 rows, but chunk far below it: a smaller statement keeps the parse cost
# and the peak memory sane, and bounds how much has to be re-sent if a chunk is
# retried.
UPSERT_CHUNK_ROWS = 500


def upsert_elections_sql(row_count: int) -> str:
    """Multi-row form of :data:`UPSERT_ELECTION_SQL` — ONE round trip for N rows.

    WHY THIS EXISTS, and why the obvious alternative does not work. The sweep used
    to write with ``for election in planned: await database.execute(UPSERT...)``,
    i.e. one network round trip per content_key — 4,266 of them on the seed run,
    which measured 7 to 30 MINUTES over the Railway public proxy with the whole
    lot inside a single transaction. That is not merely slow: interrupt the client
    mid-way and Postgres keeps an ORPHANED backend holding row locks on every
    content_key already inserted (no TCP keepalive through the proxy), so the next
    attempt blocks on those locks, looks like a connection hang, and invites
    another kill. Self-amplifying; it cost the 2026-07-26 seed several attempts.

    ``databases.Database.execute_many`` DOES NOT FIX THIS — verified against the
    installed 0.7.0, whose postgres backend is a plain Python loop over
    ``connection.execute`` with the comment "asyncpg uses prepared statements
    under the hood, so we just loop through multiple executes here". Same round
    trip count. Reaching for it is the intuitive fix and it is a no-op, so this
    builds a genuine single-statement multi-row INSERT instead.

    Parameters are named ``:content_key_0``, ``:canonical_sig_id_0``, … so the
    caller can hand ``databases`` one flat dict; see
    :func:`upsert_elections_params`.

    CALLER MUST PASS AT MOST ONE ROW PER content_key. Postgres rejects a
    multi-row ``ON CONFLICT DO UPDATE`` that would touch the same conflict target
    twice ("cannot affect row a second time"), which the per-row loop could never
    hit. ``plan_elections`` is keyed by content_key so it cannot produce a
    duplicate, and :func:`upsert_elections_params` asserts it rather than trusting
    that to stay true.
    """
    if row_count < 1:
        raise ValueError("row_count must be >= 1")
    values = ", ".join(
        f"(:content_key_{i}, :canonical_sig_id_{i}, :election_reason_{i}, NOW(), NOW())"
        for i in range(row_count)
    )
    return _UPSERT_HEAD + values + _UPSERT_CONFLICT_TAIL


def upsert_elections_params(elections: Sequence["Election"]) -> Dict[str, Any]:
    """Flatten elections into the bind dict :func:`upsert_elections_sql` expects."""
    seen: Set[str] = set()
    params: Dict[str, Any] = {}
    for i, election in enumerate(elections):
        if election.content_key in seen:
            # Would make Postgres reject the whole statement; fail loudly here
            # with the offending key rather than on an opaque server error.
            raise ValueError(
                "duplicate content_key in one upsert batch: "
                f"{election.content_key!r}"
            )
        seen.add(election.content_key)
        params[f"content_key_{i}"] = election.content_key
        params[f"canonical_sig_id_{i}"] = election.canonical_sig_id
        params[f"election_reason_{i}"] = election.election_reason
    return params
