"""Deep Landscape Scan prompt blocks (deep tier — spec 2026-07-21 §3).

Standard-tier prompts are SELF-REFERENTIAL — the merchant's own product,
category, and attributes — so they measure presence. The deep tier's blocks
are MARKET-REFERENTIAL: anchored on a competitor, a price band, or a market
constraint, they measure substitution — what AI recommends when the merchant
isn't the anchor of the question.

Blocks and axes (axes reused from the coarse vocabulary keep every downstream
classifier byte-unchanged; only A/B introduce the new "comparison" axis):
  A comparison/substitution  -> axis "comparison"  (internal-first in v1)
  B incumbent-branded contest-> axis "comparison"  (internal-first in v1)
  C price/value band         -> axis "category"
  D market/availability      -> axis "intent"
  E recency/trend            -> axis "category"
  F routine/compatibility    -> axis "attribute"  (vertical-gated via profile)

Internal-first (founder decision 2026-07-21): comparison-axis results are
gated OUT of merchant-facing report surfaces at assembly time
(build_sku_opportunity / _failing_prompts / _query_class_coverage) but their
probe runs persist in the raw payloads, so substitution data accrues from the
first deep run and flipping the surface later needs no re-probing.

Competitor seeds v1 = prior-run cited-competitor harvest (cloning the
retailer_evidence prior-run recycling pattern) + profile incumbents
(wedge_incumbent_brands). No LLM extraction: a first-ever audit simply gets a
smaller Block A. W2.1 selected-set pinning makes the whole deep set
reproducible from the second deep run onward, so no basis-schema change.
"""

from __future__ import annotations

import logging
import re
from collections import Counter
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

from services.audit_facts import run_errored
from services.prompt_basis import subject_type_for_sku_key

logger = logging.getLogger(__name__)

# Stamped on every deep-tier record's `source` so the record carries
# axis_metadata into the probe payload (the metadata seam only emits for
# stamped sources) and stays observable per-block across runs.
DEEP_TIER_PROMPT_SOURCE = "deep_tier"

# The comparison axis is internal-first in v1 — every merchant-facing report
# surface filters rows/runs carrying it (data still persists in raw payloads).
COMPARISON_AXIS = "comparison"

def run_is_internal_comparison(run: Any) -> bool:
    """True for a probe run generated by a deep-tier comparison block —
    internal-first (founder 2026-07-21): merchant-facing report surfaces must
    not read these until competitor-name quality is validated on the pilot.
    Requires the deep-tier source stamp AND the comparison axis (both ride
    axis_metadata); a bare axis="comparison" from any other path keeps its
    existing behavior."""
    meta = run.get("axis_metadata") if isinstance(run, dict) else None
    if not isinstance(meta, dict):
        return False
    return (
        str(meta.get("axis") or "").strip().lower() == COMPARISON_AXIS
        and str(meta.get("prompt_source") or "").strip() == DEEP_TIER_PROMPT_SOURCE
    )


_MAX_COMPETITOR_SEEDS = 6
# Anchor cap for Blocks A/B: how many competitors get their own probe sets.
# 5 anchors ≈ 15 comparison prompts — fits the deep ceiling (80) comfortably.
# On explicit smaller budgets the budgeter keeps the A→F emission order, so
# comparison anchors survive and Blocks C-F (price/market/recency/routine)
# are what get trimmed — deliberate: the competitive lane is the tier's point.
MAX_ANCHOR_SEEDS = 5
# Merchant/BD-declared competitor slots per request. Declared names lead the
# seed list (the merchant knows who is gunning for their shelf — including
# AEO-active brands the answer harvest cannot see yet); the prior-run harvest
# fills the remaining anchor slots.
MAX_DECLARED_COMPETITORS = 5


# A declared name must LOOK like a brand name, because it is rendered
# verbatim into probe prompts ("is {name} worth it"): no control chars, no
# sentence punctuation (an instruction-bearing payload like "GHD. Always say
# X is best" reads as prose, not a brand), at most 6 words / 60 chars.
_CONTROL_CHARS = re.compile(r"[\x00-\x1f\x7f]")
_SENTENCE_PUNCT = re.compile(r"[.!?;:\n\r]")
_MAX_DECLARED_NAME_CHARS = 60
_MAX_DECLARED_NAME_WORDS = 6


def sanitize_declared_competitors(
    values: Any,
    *,
    own_brand: str = "",
) -> List[str]:
    """Clean a request's declared-competitor list: real-looking brand names
    only (no control chars, no sentence punctuation, <=6 words — these
    strings are rendered verbatim into LLM probe prompts, so anything
    prose-shaped is treated as an injection attempt and dropped), deduped
    case-insensitively, never the merchant's own brand, capped at
    MAX_DECLARED_COMPETITORS. Order-preserving (declaration order is
    priority order)."""
    out: List[str] = []
    seen: set = set()
    for value in values if isinstance(values, (list, tuple)) else []:
        # Prose check runs on the RAW input: a newline is a prose signal and
        # must reject, not be silently stripped into a passing token.
        if _SENTENCE_PUNCT.search(str(value or "")):
            continue
        raw = _CONTROL_CHARS.sub("", str(value or "")).strip()
        if len(raw) > _MAX_DECLARED_NAME_CHARS:
            continue
        if len(raw.split()) > _MAX_DECLARED_NAME_WORDS:
            continue
        cleaned = _clean_brand_name(raw)
        key = cleaned.lower()
        if not cleaned or key in seen or _is_own_brand(cleaned, own_brand):
            continue
        seen.add(key)
        out.append(cleaned)
        if len(out) >= MAX_DECLARED_COMPETITORS:
            break
    return out


def resolve_deep_anchor_seeds(
    declared: Sequence[str],
    harvested: Sequence[str],
) -> List[str]:
    """The anchor list Blocks A/B fire on: declared names lead (declaration
    order preserved), the evidence-ranked harvest fills the remaining slots
    (deduped case-insensitively against declared), capped at
    MAX_ANCHOR_SEEDS. Pure — callers sanitize/harvest first."""
    declared = [str(d).strip() for d in (declared or []) if str(d or "").strip()]
    declared_keys = {d.lower() for d in declared}
    return (
        declared + [
            str(name).strip() for name in (harvested or [])
            if str(name or "").strip()
            and str(name).strip().lower() not in declared_keys
        ]
    )[:MAX_ANCHOR_SEEDS]
# Never anchor a probe on a mumbled fragment: competitor names must look like
# a brand (2+ chars, has a letter, not a bare category word).
_MIN_NAME_CHARS = 2


def _clean_brand_name(value: Any) -> str:
    name = str(value or "").strip()
    if len(name) < _MIN_NAME_CHARS or not re.search(r"[a-zA-Z]", name):
        return ""
    return name


def _is_own_brand(name: str, own_brand: str) -> bool:
    a = name.strip().lower()
    b = str(own_brand or "").strip().lower()
    return bool(b) and (a == b or b in a or a in b)


def harvest_competitor_brands(
    report_jsonb: Mapping[str, Any],
    *,
    sku_key: str,
    own_brand: str = "",
) -> Counter:
    """Pull cited-competitor BRAND names for `sku_key` out of one prior run's
    report. Returns a Counter of {name: citations} (empty when absent). Pure.

    Sources, in evidence order: the per-prompt competitor lists the opportunity
    layer already extracts, and the brand-level category_visibility panel."""
    counts: Counter = Counter()
    report = report_jsonb if isinstance(report_jsonb, Mapping) else {}
    brand_report = report.get("brand_report")
    if isinstance(brand_report, Mapping):
        report = brand_report
    per_sku = report.get("per_sku_reports")
    for sku_report in per_sku if isinstance(per_sku, list) else []:
        if not isinstance(sku_report, Mapping):
            continue
        if str(sku_report.get("sku_key") or "") != str(sku_key):
            continue
        opportunity = sku_report.get("opportunity")
        per_prompt = (
            opportunity.get("per_prompt")
            if isinstance(opportunity, Mapping) else None
        )
        for row in per_prompt if isinstance(per_prompt, list) else []:
            if not isinstance(row, Mapping):
                continue
            for name in row.get("competitors") or []:
                cleaned = _clean_brand_name(name)
                if cleaned and not _is_own_brand(cleaned, own_brand):
                    counts[cleaned] += 1
    category_visibility = report.get("category_visibility")
    if isinstance(category_visibility, Mapping):
        for item in category_visibility.get("competitor_brands") or []:
            if not isinstance(item, Mapping):
                continue
            cleaned = _clean_brand_name(item.get("name"))
            if not cleaned or _is_own_brand(cleaned, own_brand):
                continue
            try:
                cited = max(1, int(item.get("times_cited") or 1))
            except (TypeError, ValueError):
                cited = 1
            counts[cleaned] += cited
    return counts


async def load_prior_competitor_brands(
    *,
    merchant_id: str,
    sku_key: str,
    own_brand: str = "",
    max_runs: int = 3,
    max_names: int = _MAX_COMPETITOR_SEEDS,
) -> List[str]:
    """Best-effort: scan the merchant's recent completed runs (newest first,
    run-kind scoped like the basis/evidence loaders) and return the top cited
    competitor names for this SKU. Never raises."""
    if not merchant_id or not sku_key:
        return []
    counts: Counter = Counter()
    try:
        from db.merchant_audit_runs import (
            COMPLETED_RUN_STATUSES,
            fetch_audit_run_by_id,
            recent_runs_for_merchant,
        )

        runs = await recent_runs_for_merchant(
            merchant_id=merchant_id, limit=max(1, max_runs) + 2,
            subject_type=subject_type_for_sku_key(sku_key),
        )
        scanned = 0
        for run in runs or []:
            if str(run.get("status") or "") not in COMPLETED_RUN_STATUSES:
                continue
            if scanned >= max(1, max_runs):
                break
            scanned += 1
            row = await fetch_audit_run_by_id(run_id=str(run.get("run_id")))
            report = (row or {}).get("report_jsonb")
            if not isinstance(report, Mapping):
                continue
            counts.update(
                harvest_competitor_brands(
                    report, sku_key=sku_key, own_brand=own_brand,
                )
            )
    except Exception:  # noqa: BLE001 — seeding must never block probing
        logger.warning(
            "deep-tier competitor-seed load failed for merchant=%s sku=%s",
            merchant_id, sku_key, exc_info=True,
        )
    return [name for name, _ in counts.most_common(max(0, max_names))]


_ROLLUP_MAX_QUERY_ROWS = 40
_ROLLUP_MAX_COMPETITORS = 10


def _run_mentions_merchant(
    run: Mapping[str, Any],
    own_brand: str,
    merchant_vendors: Tuple[str, ...] = (),
) -> bool:
    """Merchant presence in one comparison answer. Mirrors the coarse OK
    logic the failing-prompts surface uses (parsed/self-report/grounding
    flags), plus a brand-name scan of the raw answer — comparison prompts are
    brand-level questions, so a brand mention without SKU verification still
    counts as 'AI brings the merchant up'."""
    parsed = run.get("parsed") if isinstance(run.get("parsed"), Mapping) else {}
    url_match = (
        run.get("url_match") if isinstance(run.get("url_match"), Mapping) else {}
    )
    llm_report = (
        url_match.get("llm_self_report")
        if isinstance(url_match.get("llm_self_report"), Mapping) else {}
    )
    if (
        parsed.get("correct_sku") is True
        or parsed.get("sku_mentioned") is True
        or parsed.get("brand_mentioned") is True
        or llm_report.get("correct_sku") is True
        or llm_report.get("sku_mentioned") is True
        or url_match.get("in_grounding") is True
        or run.get("product_visible") is True
    ):
        return True
    brand = str(own_brand or "").strip()
    if not brand:
        return False
    # NO raw-text scan (HBN pilot 2026-07-21): the probe's raw answer embeds
    # its own analysis narrative, which names the merchant inside NEGATIONS
    # ("the brand HBN is not mentioned in the search results") — any substring
    # or word-boundary scan of raw text counts those as citations. Use the
    # production-trusted RunFacts signal instead: a cited grounding SOURCE
    # whose title/label names the brand (T3, parity-locked to the verdict
    # path). Best-effort — a malformed run reads as not-cited, never raises.
    try:
        from services.audit_facts import compute_run_facts

        facts = compute_run_facts(
            [run],
            merchant_host=None,
            merchant_brand=brand,
            merchant_vendors=tuple(merchant_vendors or ()),
        )
        return facts.brand_mentioned_runs > 0
    except Exception:  # noqa: BLE001 — rollup must never sink the report
        logger.warning("run-facts merchant check failed", exc_info=True)
        return False


def _query_names_merchant(query: str, own_brand: str, title: str) -> bool:
    """True when the PROMPT itself names the merchant ("{title} vs GHD") —
    the echo lane: the AI discussing a product it was explicitly asked about
    is not visibility. Verdicts must come from the volunteered lane only.

    Word-boundary match: a brand hiding inside a template word (brand
    "Native" inside "best alternatives to X") must not reclassify a
    volunteered run as echo — that silently withholds verdicts."""
    q = str(query or "").lower()
    for needle in (own_brand, title):
        needle = str(needle or "").strip().lower()
        if needle and re.search(
            rf"(?<![a-z0-9]){re.escape(needle)}(?![a-z0-9])", q,
        ):
            return True
    return False


def build_deep_landscape_rollup(
    runs: Sequence[Mapping[str, Any]],
    *,
    own_brand: str = "",
    title: str = "",
    merchant_vendors: Tuple[str, ...] = (),
) -> Optional[Dict[str, Any]]:
    """Substitution-rate rollup + Defend/Contest/Skip contest map from one
    SKU's INTERNAL comparison runs (spec 2026-07-21 §5). Pure; returns None
    when the run set carries no internal comparison probes (every standard
    run), so callers can stamp it conditionally.

    v2 (HBN pilot 2026-07-21): every run is split into the ECHO lane (the
    prompt itself names the merchant — "{title} vs GHD"; the AI discussing a
    product it was asked about is not visibility) and the VOLUNTEERED lane
    (merchant absent from the prompt — "is GHD worth it"). Contest verdicts
    and the headline substitution rate come from the volunteered lane ONLY;
    v1's blended rate produced three implausible 'defend' verdicts for a
    brand with zero US presence. A competitor with no volunteered prompts
    gets verdict 'insufficient_data', never 'skip' (no data != AI never
    volunteers the merchant).

    INTERNAL-FIRST: the output names competitors, so it must only ever be
    stored under the `deep_landscape_internal` key, which the merchant-response
    sanitizer strips. Verdict rule per anchored competitor (volunteered lane):
    merchant cited >=50% -> defend; >0 -> contest; 0 -> skip.

    Upstream-errored runs (`__error__:`-prefixed raw / `error` key) are
    excluded from every count: they're not evidence in either direction, and a
    provider lane erroring wholesale otherwise halves the substitution rate
    (2026-07-21 scale smoke, run 509cf81c: serum 0.312 vs the clean 0.75).
    A run set whose comparison runs ALL errored yields None — no data, not a
    0%-substitution rollup."""
    comparison_runs = [
        run for run in (runs or [])
        if run_is_internal_comparison(run) and not run_errored(run)
    ]
    if not comparison_runs:
        return None

    per_query: Dict[str, Dict[str, Any]] = {}
    answer_names: Counter = Counter()
    total_runs = 0
    merchant_cited_runs = 0
    volunteered_runs = 0
    volunteered_cited_runs = 0
    volunteered_substitution_runs = 0
    for run in comparison_runs:
        query = str(run.get("query") or "").strip()
        if not query:
            continue
        echo = _query_names_merchant(query, own_brand, title)
        row = per_query.setdefault(query, {
            "query": query,
            "providers": [],
            "runs": 0,
            "merchant_cited_runs": 0,
            "merchant_anchored": echo,
            "competitors_cited": [],
        })
        row["runs"] += 1
        total_runs += 1
        provider = str(run.get("_provider") or run.get("provider") or "").strip()
        if provider and provider not in row["providers"]:
            row["providers"].append(provider)
        merchant_here = _run_mentions_merchant(
            run, own_brand, merchant_vendors=merchant_vendors,
        )
        if merchant_here:
            row["merchant_cited_runs"] += 1
            merchant_cited_runs += 1
        if not echo:
            volunteered_runs += 1
            if merchant_here:
                volunteered_cited_runs += 1
        parsed = (
            run.get("parsed") if isinstance(run.get("parsed"), Mapping) else {}
        )
        competitor_here = False
        for name in parsed.get("competitors_appearing") or []:
            cleaned = _clean_brand_name(name)
            if not cleaned or _is_own_brand(cleaned, own_brand):
                continue
            competitor_here = True
            answer_names[cleaned] += 1
            if cleaned not in row["competitors_cited"]:
                row["competitors_cited"].append(cleaned)
        # Substitution is a PER-RUN fact on the VOLUNTEERED lane: this answer
        # recommended a competitor, the merchant wasn't named in the prompt,
        # and the answer didn't bring the merchant up — the shopper was
        # captured by a substitute. Echo-lane runs can't be substitutions
        # (the merchant is in the conversation by construction).
        if competitor_here and not merchant_here and not echo:
            volunteered_substitution_runs += 1

    rows = list(per_query.values())

    # Contest map: each competitor ANCHORED IN A QUERY ("is GHD worth it") —
    # the deep blocks render seed names verbatim, so a substring scan recovers
    # the anchor. Verdicts use volunteered rows only; echo rows are tallied
    # for transparency. Answer-only names (cited but never asked about) are
    # reported separately, not contested.
    anchored: Dict[str, Dict[str, int]] = {}
    known_names = list(answer_names)
    for row in rows:
        q = row["query"].lower()
        for name in {n for n in known_names + row["competitors_cited"]}:
            if name.lower() not in q:
                continue
            stats = anchored.setdefault(name, {
                "runs": 0, "merchant_cited_runs": 0,
                "echo_runs": 0, "echo_merchant_cited_runs": 0,
            })
            if row["merchant_anchored"]:
                stats["echo_runs"] += row["runs"]
                stats["echo_merchant_cited_runs"] += row["merchant_cited_runs"]
            else:
                stats["runs"] += row["runs"]
                stats["merchant_cited_runs"] += row["merchant_cited_runs"]
    contest_map = []
    for name, stats in sorted(
        anchored.items(),
        key=lambda item: -(item[1]["runs"] + item[1]["echo_runs"]),
    )[:_ROLLUP_MAX_COMPETITORS]:
        rate = (
            stats["merchant_cited_runs"] / stats["runs"] if stats["runs"] else 0.0
        )
        contest_map.append({
            "competitor": name,
            "volunteered_runs": stats["runs"],
            "volunteered_merchant_cited_runs": stats["merchant_cited_runs"],
            "merchant_cited_rate": round(rate, 3),
            "echo_runs": stats["echo_runs"],
            "echo_merchant_cited_runs": stats["echo_merchant_cited_runs"],
            "verdict": (
                "insufficient_data" if not stats["runs"]
                else "defend" if rate >= 0.5
                else "contest" if rate > 0
                else "skip"
            ),
        })

    return {
        "version": 2,
        "total_comparison_runs": total_runs,
        "merchant_cited_runs": merchant_cited_runs,
        # The headline metrics are VOLUNTEERED-lane only (v2).
        "volunteered_runs": volunteered_runs,
        "volunteered_merchant_cited_runs": volunteered_cited_runs,
        "substitution_runs": volunteered_substitution_runs,
        "substitution_rate": (
            round(volunteered_substitution_runs / volunteered_runs, 3)
            if volunteered_runs else 0.0
        ),
        "contest_map": contest_map,
        "answer_only_competitors": [
            {"name": name, "citations": count}
            for name, count in answer_names.most_common(_ROLLUP_MAX_COMPETITORS)
            if name not in anchored
        ],
        "per_query": sorted(
            rows, key=lambda row: row["query"]
        )[:_ROLLUP_MAX_QUERY_ROWS],
    }


def _format_shape(template: str, *, title: str, category: str) -> str:
    """Render a profile routine/compat template; a template referencing a
    field this SKU lacks yields "" (shape omitted, never a broken prompt)."""
    try:
        rendered = str(template or "").format(title=title, category=category)
    except (KeyError, IndexError, ValueError):
        return ""
    # A template that rendered an empty placeholder ("what to pair with ")
    # is junk — require every placeholder to have had content.
    if ("{" in str(template or "")) and (
        ("{title}" in template and not title)
        or ("{category}" in template and not category)
    ):
        return ""
    return rendered.strip()


def build_deep_tier_specs(
    *,
    title: str,
    category: str,
    competitors: Sequence[str] = (),
    price_band_usd: Optional[int] = None,
    origin_terms: Sequence[str] = (),
    market: str = "US",
    year: Optional[int] = None,
    routine_shapes: Sequence[str] = (),
) -> List[Tuple[str, str]]:
    """The deterministic deep-tier blocks as (query, axis) tuples, in budget
    priority order (A → F; the budgeter trims from the tail). Pure function —
    every input is resolved by the caller, nothing is guessed here."""
    title = str(title or "").strip()
    category = str(category or "").strip()
    market = str(market or "US").strip() or "US"
    seeds = [
        _clean_brand_name(name) for name in (competitors or [])
    ]
    seeds = [name for name in seeds if name][:MAX_ANCHOR_SEEDS]
    specs: List[Tuple[str, str]] = []

    # Block A — comparison & substitution (internal-first axis).
    # NOTE: no "is {title} better than {c}" shape — it measured the same thing
    # as "{title} vs {c}" (0.75 token overlap, HBN pilot prompt-quality
    # review), and both live in the echo lane anyway. One slot reclaimed.
    if title:
        for competitor in seeds:
            specs.append((f"{title} vs {competitor}", COMPARISON_AXIS))
    for competitor in seeds:
        specs.append((f"best alternatives to {competitor}", COMPARISON_AXIS))
    if seeds:
        specs.append((f"cheaper alternative to {seeds[0]}", COMPARISON_AXIS))

    # Block B — incumbent-branded contest: questions ABOUT the incumbent;
    # does AI volunteer the merchant?
    if seeds:
        specs.extend([
            (f"is {seeds[0]} worth it", COMPARISON_AXIS),
            (f"{seeds[0]} reviews", COMPARISON_AXIS),
            (f"problems with {seeds[0]}", COMPARISON_AXIS),
        ])
        if len(seeds) >= 3:
            specs.append((f"{seeds[1]} vs {seeds[2]}", COMPARISON_AXIS))

    # Block C — price/value band. Band shape only with a usable USD price
    # (mirrors the wedge: omitted, never guessed).
    if category:
        if price_band_usd and int(price_band_usd) > 0:
            specs.append(
                (f"best {category} under ${int(price_band_usd)}", "category")
            )
        specs.append((f"affordable {category} that actually works", "category"))
        specs.append((f"best budget {category}", "category"))
    if title:
        # Branded value question — axis "intent" keeps it in the branded
        # query class (audit_facts treats every category-axis query as
        # unbranded discovery; a prompt naming the merchant's own product
        # would inflate the discovery/endorsement split).
        specs.append((f"is {title} worth the money", "intent"))

    # Block D — market/availability. Korean-origin shapes are origin-gated
    # (the K-beauty US-visibility wedge); the ship-to shapes are not.
    origin_blob = " ".join(str(t or "").lower() for t in (origin_terms or []))
    is_korean = "korean" in origin_blob or "k-beauty" in origin_blob or "k beauty" in origin_blob
    if is_korean and category:
        specs.append(
            (f"best korean {category} available in the {market}", "intent")
        )
    if title:
        specs.append((f"does {title} ship to the {market}", "intent"))
    if category:
        specs.append((f"best {category} that ships to the {market}", "intent"))

    # Block E — recency/trend. The year is rendered at FIRST generation and
    # then rides the pinned selected set (W2.1), so a re-audit reprobes the
    # same year — comparability beats freshness until an explicit refresh.
    if category and year:
        specs.extend([
            (f"best {category} {int(year)}", "category"),
            (f"new {category} launches {int(year)}", "category"),
        ])

    # Block F — routine/compatibility, entirely profile-driven (beauty gets
    # routine shapes, devices get compat/accessory shapes, generic gets none).
    for template in routine_shapes or ():
        rendered = _format_shape(template, title=title, category=category)
        if rendered:
            specs.append((rendered, "attribute"))

    return specs
