"""Deep Landscape Scan prompt blocks (deep tier — spec 2026-07-21 §3).

Standard-tier prompts are SELF-REFERENTIAL — the merchant's own product,
category, and attributes — so they measure presence. The deep tier's blocks
are MARKET-REFERENTIAL: anchored on a competitor, a price band, or a market
constraint, they measure substitution — what AI recommends when the merchant
isn't the anchor of the question.

Blocks and axes (axes reused from the coarse vocabulary keep every downstream
classifier byte-unchanged; only A/B introduce the new "comparison" axis):
  A comparison/substitution  -> axis "comparison"  (internal-first in v1)
  B incumbent-branded contest-> axis "comparison"  (internal-first in v1)
  C price/value band         -> axis "category"
  D market/availability      -> axis "intent"
  E recency/trend            -> axis "category"
  F routine/compatibility    -> axis "attribute"  (vertical-gated via profile)

Internal-first (founder decision 2026-07-21): comparison-axis results are
gated OUT of merchant-facing report surfaces at assembly time
(build_sku_opportunity / _failing_prompts / _query_class_coverage) but their
probe runs persist in the raw payloads, so substitution data accrues from the
first deep run and flipping the surface later needs no re-probing.

Competitor seeds v1 = prior-run cited-competitor harvest (cloning the
retailer_evidence prior-run recycling pattern) + profile incumbents
(wedge_incumbent_brands). No LLM extraction: a first-ever audit simply gets a
smaller Block A. W2.1 selected-set pinning makes the whole deep set
reproducible from the second deep run onward, so no basis-schema change.
"""

from __future__ import annotations

import logging
import re
from collections import Counter
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

from services.prompt_basis import subject_type_for_sku_key

logger = logging.getLogger(__name__)

# Stamped on every deep-tier record's `source` so the record carries
# axis_metadata into the probe payload (the metadata seam only emits for
# stamped sources) and stays observable per-block across runs.
DEEP_TIER_PROMPT_SOURCE = "deep_tier"

# The comparison axis is internal-first in v1 — every merchant-facing report
# surface filters rows/runs carrying it (data still persists in raw payloads).
COMPARISON_AXIS = "comparison"

def run_is_internal_comparison(run: Any) -> bool:
    """True for a probe run generated by a deep-tier comparison block —
    internal-first (founder 2026-07-21): merchant-facing report surfaces must
    not read these until competitor-name quality is validated on the pilot.
    Requires the deep-tier source stamp AND the comparison axis (both ride
    axis_metadata); a bare axis="comparison" from any other path keeps its
    existing behavior."""
    meta = run.get("axis_metadata") if isinstance(run, dict) else None
    if not isinstance(meta, dict):
        return False
    return (
        str(meta.get("axis") or "").strip().lower() == COMPARISON_AXIS
        and str(meta.get("prompt_source") or "").strip() == DEEP_TIER_PROMPT_SOURCE
    )


_MAX_COMPETITOR_SEEDS = 6
# Never anchor a probe on a mumbled fragment: competitor names must look like
# a brand (2+ chars, has a letter, not a bare category word).
_MIN_NAME_CHARS = 2


def _clean_brand_name(value: Any) -> str:
    name = str(value or "").strip()
    if len(name) < _MIN_NAME_CHARS or not re.search(r"[a-zA-Z]", name):
        return ""
    return name


def _is_own_brand(name: str, own_brand: str) -> bool:
    a = name.strip().lower()
    b = str(own_brand or "").strip().lower()
    return bool(b) and (a == b or b in a or a in b)


def harvest_competitor_brands(
    report_jsonb: Mapping[str, Any],
    *,
    sku_key: str,
    own_brand: str = "",
) -> Counter:
    """Pull cited-competitor BRAND names for `sku_key` out of one prior run's
    report. Returns a Counter of {name: citations} (empty when absent). Pure.

    Sources, in evidence order: the per-prompt competitor lists the opportunity
    layer already extracts, and the brand-level category_visibility panel."""
    counts: Counter = Counter()
    report = report_jsonb if isinstance(report_jsonb, Mapping) else {}
    brand_report = report.get("brand_report")
    if isinstance(brand_report, Mapping):
        report = brand_report
    per_sku = report.get("per_sku_reports")
    for sku_report in per_sku if isinstance(per_sku, list) else []:
        if not isinstance(sku_report, Mapping):
            continue
        if str(sku_report.get("sku_key") or "") != str(sku_key):
            continue
        opportunity = sku_report.get("opportunity")
        per_prompt = (
            opportunity.get("per_prompt")
            if isinstance(opportunity, Mapping) else None
        )
        for row in per_prompt if isinstance(per_prompt, list) else []:
            if not isinstance(row, Mapping):
                continue
            for name in row.get("competitors") or []:
                cleaned = _clean_brand_name(name)
                if cleaned and not _is_own_brand(cleaned, own_brand):
                    counts[cleaned] += 1
    category_visibility = report.get("category_visibility")
    if isinstance(category_visibility, Mapping):
        for item in category_visibility.get("competitor_brands") or []:
            if not isinstance(item, Mapping):
                continue
            cleaned = _clean_brand_name(item.get("name"))
            if not cleaned or _is_own_brand(cleaned, own_brand):
                continue
            try:
                cited = max(1, int(item.get("times_cited") or 1))
            except (TypeError, ValueError):
                cited = 1
            counts[cleaned] += cited
    return counts


async def load_prior_competitor_brands(
    *,
    merchant_id: str,
    sku_key: str,
    own_brand: str = "",
    max_runs: int = 3,
    max_names: int = _MAX_COMPETITOR_SEEDS,
) -> List[str]:
    """Best-effort: scan the merchant's recent completed runs (newest first,
    run-kind scoped like the basis/evidence loaders) and return the top cited
    competitor names for this SKU. Never raises."""
    if not merchant_id or not sku_key:
        return []
    counts: Counter = Counter()
    try:
        from db.merchant_audit_runs import (
            COMPLETED_RUN_STATUSES,
            fetch_audit_run_by_id,
            recent_runs_for_merchant,
        )

        runs = await recent_runs_for_merchant(
            merchant_id=merchant_id, limit=max(1, max_runs) + 2,
            subject_type=subject_type_for_sku_key(sku_key),
        )
        scanned = 0
        for run in runs or []:
            if str(run.get("status") or "") not in COMPLETED_RUN_STATUSES:
                continue
            if scanned >= max(1, max_runs):
                break
            scanned += 1
            row = await fetch_audit_run_by_id(run_id=str(run.get("run_id")))
            report = (row or {}).get("report_jsonb")
            if not isinstance(report, Mapping):
                continue
            counts.update(
                harvest_competitor_brands(
                    report, sku_key=sku_key, own_brand=own_brand,
                )
            )
    except Exception:  # noqa: BLE001 — seeding must never block probing
        logger.warning(
            "deep-tier competitor-seed load failed for merchant=%s sku=%s",
            merchant_id, sku_key, exc_info=True,
        )
    return [name for name, _ in counts.most_common(max(0, max_names))]


def _format_shape(template: str, *, title: str, category: str) -> str:
    """Render a profile routine/compat template; a template referencing a
    field this SKU lacks yields "" (shape omitted, never a broken prompt)."""
    try:
        rendered = str(template or "").format(title=title, category=category)
    except (KeyError, IndexError, ValueError):
        return ""
    # A template that rendered an empty placeholder ("what to pair with ")
    # is junk — require every placeholder to have had content.
    if ("{" in str(template or "")) and (
        ("{title}" in template and not title)
        or ("{category}" in template and not category)
    ):
        return ""
    return rendered.strip()


def build_deep_tier_specs(
    *,
    title: str,
    category: str,
    competitors: Sequence[str] = (),
    price_band_usd: Optional[int] = None,
    origin_terms: Sequence[str] = (),
    market: str = "US",
    year: Optional[int] = None,
    routine_shapes: Sequence[str] = (),
) -> List[Tuple[str, str]]:
    """The deterministic deep-tier blocks as (query, axis) tuples, in budget
    priority order (A → F; the budgeter trims from the tail). Pure function —
    every input is resolved by the caller, nothing is guessed here."""
    title = str(title or "").strip()
    category = str(category or "").strip()
    market = str(market or "US").strip() or "US"
    seeds = [
        _clean_brand_name(name) for name in (competitors or [])
    ]
    seeds = [name for name in seeds if name][:3]
    specs: List[Tuple[str, str]] = []

    # Block A — comparison & substitution (internal-first axis).
    if title:
        for competitor in seeds:
            specs.append((f"{title} vs {competitor}", COMPARISON_AXIS))
    for competitor in seeds:
        specs.append((f"best alternatives to {competitor}", COMPARISON_AXIS))
    if seeds:
        if title:
            specs.append((f"is {title} better than {seeds[0]}", COMPARISON_AXIS))
        specs.append((f"cheaper alternative to {seeds[0]}", COMPARISON_AXIS))

    # Block B — incumbent-branded contest: questions ABOUT the incumbent;
    # does AI volunteer the merchant?
    if seeds:
        specs.extend([
            (f"is {seeds[0]} worth it", COMPARISON_AXIS),
            (f"{seeds[0]} reviews", COMPARISON_AXIS),
            (f"problems with {seeds[0]}", COMPARISON_AXIS),
        ])
        if len(seeds) >= 3:
            specs.append((f"{seeds[1]} vs {seeds[2]}", COMPARISON_AXIS))

    # Block C — price/value band. Band shape only with a usable USD price
    # (mirrors the wedge: omitted, never guessed).
    if category:
        if price_band_usd and int(price_band_usd) > 0:
            specs.append(
                (f"best {category} under ${int(price_band_usd)}", "category")
            )
        specs.append((f"affordable {category} that actually works", "category"))
        specs.append((f"best budget {category}", "category"))
    if title:
        # Branded value question — axis "intent" keeps it in the branded
        # query class (audit_facts treats every category-axis query as
        # unbranded discovery; a prompt naming the merchant's own product
        # would inflate the discovery/endorsement split).
        specs.append((f"is {title} worth the money", "intent"))

    # Block D — market/availability. Korean-origin shapes are origin-gated
    # (the K-beauty US-visibility wedge); the ship-to shapes are not.
    origin_blob = " ".join(str(t or "").lower() for t in (origin_terms or []))
    is_korean = "korean" in origin_blob or "k-beauty" in origin_blob or "k beauty" in origin_blob
    if is_korean and category:
        specs.append(
            (f"best korean {category} available in the {market}", "intent")
        )
    if title:
        specs.append((f"does {title} ship to the {market}", "intent"))
    if category:
        specs.append((f"best {category} that ships to the {market}", "intent"))

    # Block E — recency/trend. The year is rendered at FIRST generation and
    # then rides the pinned selected set (W2.1), so a re-audit reprobes the
    # same year — comparability beats freshness until an explicit refresh.
    if category and year:
        specs.extend([
            (f"best {category} {int(year)}", "category"),
            (f"new {category} launches {int(year)}", "category"),
        ])

    # Block F — routine/compatibility, entirely profile-driven (beauty gets
    # routine shapes, devices get compat/accessory shapes, generic gets none).
    for template in routine_shapes or ():
        rendered = _format_shape(template, title=title, category=category)
        if rendered:
            specs.append((rendered, "attribute"))

    return specs
