#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export PYTHONDONTWRITEBYTECODE=1

# 100% enable profile for no-user environments (compatibility-safe).
export RELIABILITY_BUDGET_ENABLED="${RELIABILITY_BUDGET_ENABLED:-true}"
export PAYMENT_ROUTING_V2_ENABLED="${PAYMENT_ROUTING_V2_ENABLED:-true}"
export PAYMENT_ROUTING_V2_MERCHANT_ALLOWLIST="${PAYMENT_ROUTING_V2_MERCHANT_ALLOWLIST:-}"
export CATALOG_RELIABILITY_V2_ENABLED="${CATALOG_RELIABILITY_V2_ENABLED:-true}"
export CATALOG_RELIABILITY_V2_LOCAL_FALLBACK_ON_DELEGATE_FAIL="${CATALOG_RELIABILITY_V2_LOCAL_FALLBACK_ON_DELEGATE_FAIL:-false}"
export CATALOG_UPSTREAM_V2_SHOPPING_TIMEOUT_CAP_SECONDS="${CATALOG_UPSTREAM_V2_SHOPPING_TIMEOUT_CAP_SECONDS:-1.1}"

echo "== Reliability v2 100% endpoint smoke =="
echo "flags:"
echo " - RELIABILITY_BUDGET_ENABLED=$RELIABILITY_BUDGET_ENABLED"
echo " - PAYMENT_ROUTING_V2_ENABLED=$PAYMENT_ROUTING_V2_ENABLED"
echo " - CATALOG_RELIABILITY_V2_ENABLED=$CATALOG_RELIABILITY_V2_ENABLED"
echo " - CATALOG_RELIABILITY_V2_LOCAL_FALLBACK_ON_DELEGATE_FAIL=$CATALOG_RELIABILITY_V2_LOCAL_FALLBACK_ON_DELEGATE_FAIL"

python3 scripts/smoke_reliability_v2_100_endpoints.py
